Terrain 3D
maplibre/maplibre-gl-js pull request #1022
Opened 2022-02-24 13:44 UTC by wipfli

@prozessor13 thank you for all the work you did to make 3D happen in MapLibre GL JS. 

This pull request is a continuation of #165 with the goal to merge the `terrain3d` branch into `main`.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-02-24 14:10 UTC, wipfli commented
Houpsi, I merged an old version of `main`. Correcting...

2022-02-24 18:45 UTC, HarelM commented on src/data/dem_data.test.ts
> +            max,
Since this is a test I would not duplicate the code but instead hard code the expected values here.

2022-02-24 18:53 UTC, HarelM commented on src/render/draw_circle.ts
> +    terrain: any;
This needs to be typed.

2022-02-24 18:56 UTC, HarelM commented on src/render/draw_symbol.ts
> +    terrain: any;
Same here

2022-02-24 19:02 UTC, HarelM commented
My bad, I started to review this too early... :-(
Let me know when this is ready for review.
Make sure to address the FIXME comments and the lint warnings.
Thanks again for all the hard work @prozessor13! Truly appreciated!

2022-02-26 13:34 UTC, zstadler commented
I'm looking forward to the merge of this PR!

Note that a label appears fully while its associated line is barely seen.

![image](https://user-images.githubusercontent.com/1304610/155845161-fce8718c-9a04-49cc-bf07-52a979666c73.png)
https://wipfli.github.io/maplibre-terrain3d/#14.48/31.46119/35.36986/-87.2/80

IMHO, this is not a show-stopper for the merge.

2022-02-26 18:56 UTC, HarelM commented
@prozessor13 thanks for the info.
I'll be working to fix small issues I see such as typings, lint, etc.
For every issue we open that is related to Terrain 3D we should decide if this is a show stopper in order to get this merged or not. This indication will be written foreach feature.

2022-02-26 19:43 UTC, HarelM commented on src/data/dem_data.test.ts
> +            max,
Image is randomly generated so the test needs to do the same logic. This is not ideal but I'm not planning on changing this as part of this PR...

2022-03-09 10:24 UTC, wipfli commented
Browser test passed. Good sign for #1024

2022-03-09 20:25 UTC, HarelM commented
@prozessor13 ping me here when you finish the fixes and would like me to start the review.
Also it would be good to close the issues that are fixed in this PR so that we know which issues are still relevant after we merge this. This can be done later too of course...

2022-03-12 20:22 UTC, HarelM requested changes
Overall looks very good! I have some questions and change requests.

2022-03-12 20:22 UTC, HarelM commented on src/ui/marker.ts
> +            const metresPerPixel = 40075016.686 * Math.abs(Math.cos(this._lngLat.lat * Math.PI / 180)) / Math.pow(2, this._map.transform.tileZoom + 8);
Move hard coded value to a const or place it elsehwere

2022-03-12 20:22 UTC, HarelM commented on src/ui/marker.ts
> +            const metresPerPixel = 40075016.686 * Math.abs(Math.cos(this._lngLat.lat * Math.PI / 180)) / Math.pow(2, this._map.transform.tileZoom + 8);
Move hard coded value to a const or place it elsehwere

2022-03-12 20:22 UTC, HarelM commented on src/ui/marker.ts
> +    _opacityTimeout: any;
There's a `TimeoutID` or something similar that can be used as a type here.

2022-03-12 20:22 UTC, HarelM commented on src/ui/marker.ts
> +    _opacityTimeout: any;
There's a `TimeoutID` or something similar that can be used as a type here.

2022-03-12 20:22 UTC, HarelM commented on src/ui/map.ts
> +        this.fire(new Event('terrain'));
probably better to add the current state to the event - i.e. added/removed?

2022-03-12 20:22 UTC, HarelM commented on src/ui/map.ts
> +        this.fire(new Event('terrain'));
probably better to add the current state to the event - i.e. added/removed?

2022-03-12 20:22 UTC, HarelM commented on src/symbol/placement.ts
> +                null;
Is is possible here to return 0 and not a null getElevation method? I see that there's a check a few lines ahead that maybe can be simplified?

2022-03-12 20:22 UTC, HarelM commented on src/symbol/placement.ts
> +                null;
Is is possible here to return 0 and not a null getElevation method? I see that there's a check a few lines ahead that maybe can be simplified?

2022-03-12 20:22 UTC, HarelM commented on src/style/style.ts
> +        this.terrainSourceCache = new TerrainSourceCache(this);
When I see a constructor that receives `this` I get nervous... Can we pass something smaller?

2022-03-12 20:22 UTC, HarelM commented on src/style/style.ts
> +        this.terrainSourceCache = new TerrainSourceCache(this);
When I see a constructor that receives `this` I get nervous... Can we pass something smaller?

2022-03-12 20:48 UTC, HarelM commented
For some reason everything I wrote was written twice. Thanks Github! :-(
I merged main and fixed the tests. I also did some minor refactoring to things I thought should be different but I didn't write it as a review to reduce load.
See the following commit: https://github.com/maplibre/maplibre-gl-js/pull/1022/commits/e4674f52942c374786439a07deecb932bd70879c

2022-03-12 20:56 UTC, HarelM commented
I've resolved the duplicate code review comments.
I still need to go over the main newly added classes which are a bit too much right now, so I'll continue it later on.
@prozessor13 can we change the status of the PR to ready for review?

2022-03-12 21:00 UTC, HarelM commented
Make sure to open the hidden conversations (load more... button) in order to see all the review comments I wrote.

2022-03-13 22:26 UTC, birkskyum commented
I'll start to go through this PR as well. It's quite intimidating due to the size, but if it's completely impossible to chop up, I guess we'll have to manage. I see these spikes when I launch the demo (could it be a data or boundary issue?) - but apart from that all the visual look great! 

<img width="1276" alt="Screenshot 2022-03-13 at 23 19 30" src="https://user-images.githubusercontent.com/74932975/158081699-61e9d50c-3353-415e-8c06-f3e3c00c2a41.png">

2022-03-14 06:00 UTC, wipfli commented
We haven't had reports about these spikes. Can you open an issue?

2022-03-14 08:24 UTC, birkskyum commented
> We haven't had reports about these spikes. Can you open an issue?

I investigated a bit and found that this issue only exist in Brave and Brave Nighly. Everything works great in chrome, safari, edge, firefox and orion - so I think we can safely leave this for the Brave team.

2022-03-14 09:57 UTC, prozessor13 commented
Hi Birk,

i dont know how to split the PR, und even if i have an idea, it would be a huge amount of work. I think the current important thing is, that the 3d code do not affect the existing 2d implementation. Please take a look especially onto this. In future releases it will make sense to mix the 3d & 2d code, because at some places the 2d code will benefit from the 3d code (e.g. in transform.js). This can then be done in granular PRs.

Thx for your help!

2022-03-14 12:06 UTC, birkskyum commented
@prozessor13 , can I set it as ready for review, or are you still planning some changes?

2022-03-14 12:26 UTC, birkskyum commented on src/shaders/circle.fragment.glsl
> +varying float v_visibility;
Because it's a **varying** type, the definition from the vertex shader (src/shaders/circle.vertex.glsl) is automatically passed to the fragment shaders with a variable of same name. I think the native repo will still work after this, but let's try to compiling the c++ programs from the shaders and see for sure.

2022-03-14 13:10 UTC, prozessor13 commented
I do not plan changes, except the change-requests from the of code-review comments.

2022-03-14 14:34 UTC, birkskyum commented on src/shaders/symbol_icon.fragment.glsl
> +varying float v_visibility;
This float appear to be unused

2022-03-14 14:35 UTC, birkskyum commented on src/shaders/symbol_text_and_icon.fragment.glsl
> +varying float v_visibility;
Unused float?

2022-03-14 16:29 UTC, birkskyum commented on src/ui/handler_manager.ts
> +            //      this should be fixed in future-version
It would be great if you can open a feature request when the pr is through.

2022-03-14 16:31 UTC, birkskyum commented on src/render/draw_symbol.ts
> -import SymbolBucket, {addDynamicAttributes, SymbolBuffers} from '../data/bucket/symbol_bucket';
How come the import was split into three lines?

2022-03-14 17:00 UTC, birkskyum commented on src/shaders/fill_extrusion.vertex.glsl
> +attribute vec2 a_centroid;
Potentially breaking for native, because data isn't fed into it.

2022-03-14 17:11 UTC, birkskyum reviewed
I looked through the changes and added a few comments. The benchmarks doesn't show performance degradation, and I asked @ntadej for help verifying whether the shaders in any way break the test suite for the native repo. Looking forward to see this in main.

2022-03-14 17:49 UTC, ntadej commented
No, it wants to load the folder as module, I guess it at least uses some helpers there to list the shaders.

2022-03-14 21:22 UTC, birkskyum commented
I figured out how to run the generate-shader from the native repo using typescript [in this branch](https://github.com/maplibre/maplibre-gl-native/tree/generate-shaders-using-typescript/src/mbgl/programs), and the generated shader programs can be found in src/mbgl/programs.

2022-03-16 19:40 UTC, HarelM commented on src/render/draw_symbol.ts
> -import SymbolBucket, {addDynamicAttributes, SymbolBuffers} from '../data/bucket/symbol_bucket';
Types are imported below and not the whole classes. This is better I think.

2022-03-16 19:44 UTC, HarelM commented on src/render/draw_terrain.ts
> +    // draw tile-coords into framebuffer
use methods instead of comments - i.e. move this code to a method called `drawTileCoords` or something similar.
Same for the depth below.

2022-03-16 19:50 UTC, HarelM commented on src/source/source_cache.ts
> +                    const parent2 = tileID.scaledTo(Math.max(this._source.minzoom, 5));
Shouldn't this be configurable? What happens if zoom 5 tiles are not available?

2022-03-17 08:43 UTC, prozessor13 commented
Hello all,

currently i am very busy in my day-job. Thx for all your comments! i will answer asap.

Regards. Max.

2022-03-20 21:14 UTC, wipfli commented
@prozessor13 what is your timeline for the review process?

2022-03-20 21:16 UTC, wipfli commented
I can help resolving the conflicts introduced by #1109

2022-03-21 07:38 UTC, HarelM commented
@wipfli please do :-)

2022-03-21 09:18 UTC, prozessor13 commented on debug/terrain.html
> +    map.addTerrain('terrain', {exaggeration: 0.33});
I think both, source and layers are not the correct places. May a toplevel setting aka `light` could be used?

2022-03-21 09:28 UTC, prozessor13 commented on src/shaders/fill_extrusion.vertex.glsl
> +        float baseDelta = 10.0;
no, the height will be the same, only the *ground* area of the building is drawn 10 meters below terrain.

2022-03-21 09:31 UTC, prozessor13 commented on src/shaders/fill_extrusion_pattern.vertex.glsl
> +attribute vec2 a_centroid;
I can capsulate the addional attributes into the `ifdef #TERRAIN3D` pre-processor logic. Would this help?

2022-03-21 09:32 UTC, prozessor13 commented on src/shaders/symbol_icon.fragment.glsl
> +varying float v_visibility;
thx for the hint! i will remove this line.

2022-03-21 10:00 UTC, prozessor13 commented on src/source/source_cache.ts
> +                    const parent2 = tileID.scaledTo(Math.max(this._source.minzoom, 5));
> What happens if zoom 5 tiles are not available?

Minzoom is alreay checked, do you mean, if the maxzoom is below ZL 5? I will make a check as well!

> Shouldn't this be configurable?

I dont see much sense to make this configurable, because no one will understand this setting. It is only needed to get an elevation value for tiles outside of the FOV, to calculate the correct visibility in heavy tilted maps. I tested an implementation which loads all parent tiles of the current scene, but this was too much data, which are technically not needed.

Basically there are more ways to calculate needed tiles in terrain:

Mapbox loades only the requested zoomlevel (with LOD logic to the horizion), but in heavy titled maps with heavy terrain you see missing tiles near the camera, because the algo calculates all needed tiles based on elevation 0. But if there exists a very rough (e.g. ZL 5) elevation values the FOV <-> AABB intersection calculation can handle the Z-Axis correct.

Cesium for example does the other approach -> it loads all tiles starting at Zoomlevel 0, and then goes deeper and deeper to the requested zoomlevel. With this way you can calculate visibility right at every time, but i takes much more time to render, while the other logic only loads one or two additionally tiles.

Finally:
What may make sense: Make the number of parent loaded zoomlevels configurable? But this has definitely an impact on load-time/data-transfer, so i think the minimum setting will always the best setting.

2022-03-21 10:13 UTC, prozessor13 commented on src/style/style.ts
> +        this.terrainSourceCache = new TerrainSourceCache(this);
Yes you are right! :)

I will think about a refacturing. I would we be happy with an Elevation-Object working as a singleton, completely independed of style or any other stuff. Than also the tons of: `if (terrainSourceCache && terrainSourceCache.isEnabled())` commands will go away. What do you think?

2022-03-21 10:16 UTC, prozessor13 commented on src/symbol/placement.ts
> +                null;
Do you mean a method which retruns 0? If yes, i already had this, but this has a big impact on performance in 2D, because it will called very often!

2022-03-21 10:22 UTC, prozessor13 commented on src/ui/marker.ts
> +    _opacityTimeout: any;
OK. great. I will have a look!

2022-03-21 10:22 UTC, HarelM commented on debug/terrain.html
> +    map.addTerrain('terrain', {exaggeration: 0.33});
I see your point, since hillshading is a layer that can be drawn between other layers it behaves differently than this one.
I don't have a good udea how to call this though in the style.
@wipfli @birkskyum do you have suggestions?

2022-03-21 11:31 UTC, HarelM commented on src/symbol/placement.ts
> +                null;
Really? But the there's still a check to see if the function is null or not, isn't it the same?
In any case feel free to resolve this conversation.

2022-03-21 12:14 UTC, HarelM commented on src/style/style.ts
> +        this.terrainSourceCache = new TerrainSourceCache(this);
Sounds good in general, but we need to remember that some work is done in the workers which do not share the same memory space, I'm not 100% sure I know how to address this, but this is something we should keep in mind.

2022-03-21 12:45 UTC, prozessor13 commented on src/style/style.ts
> +        this.terrainSourceCache = new TerrainSourceCache(this);
Ohh, you are right, i will keep this in mind!

2022-03-22 14:16 UTC, wipfli commented
We are facing issues with precision. I think this is related to `gl-matrix` and how it handles `fromValues()` versus `[]`. @timokorkalainen do you have any clue how to fix the failing unit test? This one fails at the moment `npx jest src/geo/transform.test.ts`

2022-03-22 15:36 UTC, timokorkalainen commented
No actually it is the test that is at fault. It would be better to use a non-whole number as the width for the transform. Shall I make a PR to fix the test here or main?

2022-03-22 17:54 UTC, wipfli commented
#1120 fixed the failing test. Thanks @timokorkalainen!

2022-03-23 08:14 UTC, prozessor13 commented
@wipfli yesterday I started a refacture process based on the comments from @HarelM. I think this will take at least one or two weeks, because i cannot work fulltime on it. Basically with the following roadmap:

- split TerrainSourceCache into
   * TerrainSourceCache, which handles the covering *raster-dem* Source and knows which RTT tiles should render
   * Terrain, which handles all necessery framebuffer RTT rendering and mesh logic
- remove cross references between TerrainSourceCache, Transform, Style, ...
- move some code from Painter into the Terrain-class
- add tests
- may allow loading terrain via style? proposal:

in style:
```
{
   sources: { terrain: { type: 'raster-dem', ... }, ... },
   terrain: { source: "terrain", exaggeration: 0.33 },
   layers: [ ... ],
   ...
}
```
in code:
```
map.setTerrain({ source: "terrain", exaggeration: 0.33 }); // to add terrain
map.setTerrain(null); // to remove terrain
```
What do you think?

2022-03-23 08:16 UTC, wipfli commented
I think this is great!

2022-03-23 08:52 UTC, HarelM commented
Can we think of a valid situation where one would need more than one source for the terrain? Maybe low-res/high-res? Divided by states/countries? I'm asking because this definition is basically saying there's only one source.
Otherwise, this sounds good to me. Maybe posing a message on slack and asking for ideas regarding the schema change can help here.

2022-03-23 08:54 UTC, HarelM commented
Thanks again @prozessor13 for doing all the heavy lifting!

2022-03-23 11:01 UTC, prozessor13 commented
I think merge sources should not a feature of 3D, instead of source. Because when you need this feature in 3D then you need the logic at least in hillshading as well.

2022-03-23 11:04 UTC, HarelM commented
But since hill shading is a layer one can create multiple layers referencing different sources, right?

2022-03-23 12:26 UTC, prozessor13 commented
ok, you are right. Should i wait with the Style implementation, and only implement `setTerrain`? In future versions such a logic can then be implemented in TerrainSourceCache.

2022-03-23 12:51 UTC, VehpuS commented
I'm chiming in as an outsider just to say that I think not tying this pull request with style loading logic seems like a better approach to me, as it reduces the complexity of the proposed change and reduces the friction with existing features (== the risk of introducing new bugs to them).

I'm obviously slightly biassed towards the complexity reduction approach also as someone eager to see the feature introduced, though ;)

2022-03-23 14:43 UTC, HarelM commented
@prozessor13 I would focus on fixing the code review comments first.
We can do the style changes in another PR although I'm not very fond of this idea as I think it should be delivered in the same maplibre version.
We can continue the style discussion in the skack channel.

2022-03-30 13:19 UTC, prozessor13 commented on src/source/source_cache.ts
> +                    const parent2 = tileID.scaledTo(Math.max(this._source.minzoom, 5));
Didnt make it configurable, instead i added tests.
https://github.com/maplibre/maplibre-gl-js/pull/1022/commits/485db090b0c5a31e49313391813314db79da8ad5

2022-03-30 13:23 UTC, prozessor13 commented on src/render/draw_symbol.ts
> -import SymbolBucket, {addDynamicAttributes, SymbolBuffers} from '../data/bucket/symbol_bucket';
nothing to do here, right?

2022-03-30 13:25 UTC, prozessor13 commented on src/ui/handler_manager.ts
> +            //      this should be fixed in future-version
https://github.com/maplibre/maplibre-gl-js/issues/1024

2022-03-30 13:26 UTC, prozessor13 commented on src/shaders/symbol_text_and_icon.fragment.glsl
> +varying float v_visibility;
Thx for the hint, removed!

2022-03-30 13:30 UTC, prozessor13 commented on src/style/style.ts
> +        this.terrainSourceCache = new TerrainSourceCache(this);
This is now completely refactured. See [setTerrain](https://github.com/maplibre/maplibre-gl-js/blob/terrain3d/src/style/style.ts#L491)

2022-03-30 13:32 UTC, prozessor13 commented on src/ui/map.ts
> +        this.fire(new Event('terrain'));
With the new setTerrain Method i removed the `terrain` Event. Any proposals how to re-implement it?

2022-03-30 13:47 UTC, prozessor13 commented on src/ui/marker.ts
> +            const metresPerPixel = 40075016.686 * Math.abs(Math.cos(this._lngLat.lat * Math.PI / 180)) / Math.pow(2, this._map.transform.tileZoom + 8);
This needs some refacturing. Created an issue.

2022-03-30 13:51 UTC, prozessor13 commented on src/shaders/collision_box.vertex.glsl
> +// FIXME-3D! use 3d coordinates
This is an outdated FIXME, checkin will follow soon.

2022-03-30 13:57 UTC, prozessor13 commented on src/render/draw_fill.ts
> +        const terrainCoord = painter.style.terrainSourceCache.isEnabled() ? coord : null;
With the new refactured Code `terrain` is an instance Variable of `style`. In 2D this instance variable is not setted. So all
 
      if (painter.style.terrainSourceCache.isEnabled())

are replaced by

     if (painter.style.terrain)

What do you think about this?

2022-03-30 14:00 UTC, prozessor13 commented on src/render/painter.ts
> +            if (isTerrainEnabled) {
I created [render_to_texture.ts](https://github.com/maplibre/maplibre-gl-js/blob/485db090b0c5a31e49313391813314db79da8ad5/src/render/render_to_texture.ts) with all the render to texture logic

2022-03-30 14:03 UTC, prozessor13 commented on debug/terrain.html
> +    map.addTerrain('terrain', {exaggeration: 0.33});
I created the Style.setTerrain Method with TerrainOptions as argument.
```
export type TerrainOptions = {
    source: string;
    exaggeration?: number;
    elevationOffset?: number;
};
```
In my opinion i would allow this object in top-level style definition. What do you think?

2022-03-30 14:08 UTC, prozessor13 commented on src/geo/transform.ts
> +        const fovAboveCenter2 = 2 * horizonAngle * (0.5 + offset.y / (horizon * 2));
add the `horizon` key to all variablenames. e.g. `fovCenterToHorizon`, checkin will follow soon.

2022-03-30 14:16 UTC, prozessor13 commented on src/geo/transform.ts
> +    terrainSourceCache: TerrainSourceCache;
in the refactured code there is still the terrain-object saved in the `transform.terrain` instance variable. If it is really needed to remove this variable from transform, i will create a pull-request after the merge, because removing this needs quite a lot of changes during the whole maplibre-code, and with a new pull-request this will be much more clear. ok?

2022-03-30 17:10 UTC, HarelM commented on debug/terrain.html
> +    map.addTerrain('terrain', {exaggeration: 0.33});
Sounds good to me.

2022-03-30 17:11 UTC, HarelM commented on src/render/draw_fill.ts
> +        const terrainCoord = painter.style.terrainSourceCache.isEnabled() ? coord : null;
feels a lot better.

2022-03-30 18:17 UTC, HarelM commented
@prozessor13 thanks for taking care of all the code review required changes!
Regarding the usage of `Terrain` in `Transform.ts` I think we can improve this as I've looked at the code and most of the terrain class is not in use in transform. there are a few places where it is used (and not only checked for null) and these places are very specific.
For this I would consider creating an interface that has only that functionality and use that interface in the transform class:
something like:
```ts
export interface IElevationProvider {
    getEelvation(tileID: OverscaledTileID, x: number, y: number, extent: number = EXTENT): number;
    getMinMaxElevation(tileID): { min: number; max: number; }
    pointCoordinate(P: Point): MercatorCoordinate;
}
```
Other than this, I think this looks fine.
Feels to me like it's ready to be merged.
@wipfli @birkskyum any comments?

2022-03-30 18:49 UTC, wipfli commented
Nothing from my side other than big thanks to @prozessor13 for going though all the review comments :)

2022-03-30 19:38 UTC, birkskyum commented
No inquiries from my side :)

2022-03-30 19:40 UTC, HarelM commented
@birkskyum can you go over the code review comments that you added to make sure you are OK with the responses, or add suggestions? I think I saw things that weren't addressed...?

2022-03-30 19:45 UTC, birkskyum commented on src/shaders/fill_extrusion_pattern.vertex.glsl
> +attribute vec2 a_centroid;
I think it would actually

2022-03-30 19:48 UTC, birkskyum commented on src/shaders/fill_extrusion.vertex.glsl
> +attribute vec2 a_centroid;
With regard to native, there need to be an opt-in terrain3d flag somewhere, because the native code will try to use the shader without the a_centroid as it has no concept of terrain3d.

2022-03-31 13:05 UTC, RNMBuser commented
Could you please take a look at https://github.com/maplibre/maplibre-gl-js/issues/1137 ? I think this may affect vector tiles as well.

2022-03-31 14:07 UTC, prozessor13 commented on src/shaders/fill_extrusion.vertex.glsl
> +attribute vec2 a_centroid;
Ok, i will encapsulate all the additional shader-code with the #TERRAIN3D preprocessor

2022-03-31 14:24 UTC, prozessor13 commented
> ```ts
> export interface IElevationProvider {
>     getEelvation(tileID: OverscaledTileID, x: number, y: number, extent: number = EXTENT): number;
>     getMinMaxElevation(tileID): { min: number; max: number; }
>     pointCoordinate(P: Point): MercatorCoordinate;
> }
> ```

Sorry, but I already do not know what you exactly mean. I can make Terrain implements IElevationProvider, but getElevation, getMinMaxElevation & pointCoordinate will use at least 80% of the internal Terrain-class code, so i cannot create a *small* version of Terrain.ts. My approach would be, that i remove transform.terrain completely and pass terrain as argument to the transform methods when they need terrain.

2022-03-31 14:32 UTC, prozessor13 commented on src/shaders/fill_extrusion.vertex.glsl
> +attribute vec2 a_centroid;
done in https://github.com/maplibre/maplibre-gl-js/pull/1022/commits/1d9683f6ceebeaa04e900a9c2d80eb6680a6ecae

2022-03-31 14:33 UTC, prozessor13 commented on src/shaders/fill_extrusion_pattern.vertex.glsl
> +attribute vec2 a_centroid;
fixed in https://github.com/maplibre/maplibre-gl-js/pull/1022/commits/1d9683f6ceebeaa04e900a9c2d80eb6680a6ecae

2022-03-31 14:36 UTC, HarelM commented
Please check of it make sense to split the passing of terrain object on one hand and keeping a Boolean of "useTerrain" on the other hand.
Passing terrain object send like the right approach to me in general.

2022-03-31 16:32 UTC, prozessor13 commented
Ok, then i will implement the 'passing terrain as argument' option. This will take some hours, I will try to find the time in the next days. Also i will try to write some more tests!

On the other side it would be great if someone else could implement the `TerrainOptions` spezification into the v8 stylesheet definition.

2022-03-31 16:46 UTC, HarelM commented
I'll see if I can make a PR against this branch to help with the remaining items you mentioned.

2022-03-31 18:02 UTC, HarelM commented
I've created #1138 for the spec update.

2022-03-31 18:10 UTC, HarelM commented on src/ui/map.ts
> +        this.fire(new Event('terrain'));
I think you can do the same in the `style.ts` when setting or removing the terrain object, can't you (i.e. in `style#setTerrain(...)`?

2022-03-31 18:13 UTC, HarelM commented
All major conversations (code review comments) have been addressed.
There are two conversations related to tests that needs to be addressed and the last comment about the Terrain object in `transform.ts`.
This is ready to be merged when the above are addressed from my point of view.

2022-04-06 09:01 UTC, prozessor13 commented on src/ui/map.ts
> +        this.fire(new Event('terrain'));
I added a event in the form of:

      this.map.fire(new Event('terrain', {terrain: options}));

OK?

2022-04-06 09:03 UTC, HarelM commented on src/ui/map.ts
> +        this.fire(new Event('terrain'));
Sure

2022-04-06 09:12 UTC, HarelM commented
Seems like there are typings issue with the latest commit, probably a problematic return value related to coordinates.
I have labeled all the issues related to terrain 3d with a terrain3d label so it will be easier to filter, we can also add other labels such as critical or whatever if we think something should be fixed before we merge this.
I think the last commit was addressing my last code review comment besides adding tests and merging the style-spec branch into this branch so we are making great progress!

2022-04-07 14:30 UTC, prozessor13 commented on src/geo/transform.ts
> +    recalculateZoom() {
added in https://github.com/maplibre/maplibre-gl-js/commit/c2ab1b42bca0e33e99987e68f50f91a47e4c0c5d

2022-04-08 20:29 UTC, HarelM commented
I've took this branch for a spin in my project to see how it behaves in a complicated (real life) scenario.
Unfortunately, when using the terrain the app breaks and the console has a lot of errors.
I'll see if I can create a minimal reproduction and open the relevant issues.
Bottom line, unfortunately, still not ready to be merged unless we want to create a pre-release version to allow other people to test it and report issues.
What I did in order to test this if anyone is interested:
1. Clone the repo, checkout this branch and build it (with codegen and everything)
2. Copy the dist folder to the node_modules/maplibre-gl/dist of the project I'm testing
3. Build the project and run it
4. [Optional] I'm also using the patch-package npm package to allow CI to build it or reduce the work for other people

2022-04-09 18:56 UTC, HarelM requested changes

2022-04-09 18:56 UTC, HarelM commented on src/render/terrain.ts
> +        if (!tile) return null;
This function should never return `null`.
I see it is being using in query render features where the calling method assumes the return value is a valid point and not null.
The return value of `transform.pointCoordinate` is never null as well, and this method should be the same in terms of behavior.
The use case which I found this to fail is when passing the `0,0` point. it will return from the framebuffer also and array of `0,0,0,0`, which will in turn try to search in coordsIndex array which in my case was only 20 members long resulting in tileID undefined.
I think it's worth, as I mentioned earlier, to try and unit test this method to make sure all use cases are covered, and this one can be the first use case.

2022-04-10 20:29 UTC, HarelM commented on src/source/terrain_source_cache.ts
> +    sourceCache: SourceCache;
After a long debug I found that this reference might be problematic:
Consider the following scenario:
1. Add raster-dem source
2. setTerrain to the above added source
3. remove raster-dem source

Since this part of the code does not listen to changes in the source cache it will keep a reference to an already removed and deleted source cache.
I'm not sure I know how to fix this though :-(

2022-04-11 06:40 UTC, prozessor13 commented on src/render/terrain.ts
> +        if (!tile) return null;
terrain.pointCoordinate is only called from transform.pointCoordinate, so the `null` can easily be catched and transform.pointCoordinate can fallback into 2D calculation.
furthermore i will have a look onto the `0,0` point thing!

Beside this i think it is currently important to not loosing in very detailed problems. Better create tickets with states like blocker/major/minor issue.

2022-04-11 06:40 UTC, prozessor13 commented on src/source/terrain_source_cache.ts
> +    sourceCache: SourceCache;
What is the behaviour when deleting a source for a normal layer?

2022-04-11 06:46 UTC, HarelM commented on src/render/terrain.ts
> +        if (!tile) return null;
I'll open an issue about it for better tracking, no problem. Just giving a heads up that I think this is probably a blocker as it fills the console with errors.

2022-04-11 06:47 UTC, prozessor13 commented
> Unfortunately, when using the terrain the app breaks and the console has a lot of errors.

What do you mean with *the app break*? Which errors? Mobile or Deskop?

2022-04-11 06:47 UTC, HarelM commented on src/render/terrain.ts
> +        if (!tile) return null;
I just though it will be more useful if I comment here about the actual line of code that is problematic after I debugged it.

2022-04-11 06:49 UTC, HarelM commented on src/source/terrain_source_cache.ts
> +    sourceCache: SourceCache;
In normal layers you can't delete a source if it is part of a layer - you have to remove the layer first.
When removing a source it removes its source cache and thus creates an issue here.

2022-04-11 06:55 UTC, HarelM commented
> What do you mean with the app break? Which errors? Mobile or Deskop?

The errors in the console are errors related to the two places I commented yesterday.
In some cases when I tested it on desktop chrome, which I need to still identify the exact scenario, the map stops responding to gestures and you can't pan the map using the mouse.

Let's fix the above two errors and I'll test again to see if I can reproduce the last issue where the map stops responding to gestures.

2022-04-11 07:03 UTC, prozessor13 commented on src/source/terrain_source_cache.ts
> +    sourceCache: SourceCache;
Ah ok. This is a good behaviour, and should be not to complicated to implement.

2022-04-11 07:05 UTC, HarelM commented on src/render/terrain.ts
> +        if (!tile) return null;
#1180

2022-04-11 07:05 UTC, prozessor13 commented
Ok, i will focus on that!

2022-04-11 19:37 UTC, HarelM commented on src/ui/marker.ts
> +            const lnglat = this._map.unproject(this._pos);
Need to check here if `this._map` is still defined before calling this method due to race condition when removing the marker.
See #1181. I can send a PR to fix this I think.

2022-04-12 18:21 UTC, prozessor13 commented
Hello all,

i created a new issue-label **Terrain 3D Blocker**. So, for blocking issues (e.g. must fixed before merge) please tag with this label, so i can focus on the right things.

Thanks in advance!

2022-04-13 00:03 UTC, thunderkid commented
![3dMapLibreBrave](https://user-images.githubusercontent.com/6183356/163073085-398b2a32-2280-4028-923a-87e91ac5e9a7.PNG)

I'm finding that the demo link on this page behaves strangely in the Brave browser (V1.37.113 - Apr 12, 2022 running on Windows 10 21H1 19043.1586 and also on a couple of older Brave versions that I checked). The 3d terrain works, but with random spikes all over it as shown in this screen capture. These persist when moving around. On Chrome it's working fine on the same machine.

2022-04-13 04:40 UTC, HarelM commented
This is a problem with brave, feel free to open a defect for them. In general I've seen bad behavior of brave with maplibre not only in terrain 3D.

2022-04-14 20:53 UTC, HarelM commented on src/source/terrain_source_cache.ts
> +    sourceCache: SourceCache;
#1183

2022-04-14 20:57 UTC, HarelM commented
#1166 is the only blocking issue according to the labels.
Once fixed I tend to say that this branch can be merged.
@wipfli what do you think?

2022-04-15 06:08 UTC, wipfli commented
I really like how well terrain 3D works now and can't stop looking at maps of the Alps in 3D mode. Thanks @prozessor13 for all the work you put into this. I think I found another bug related to toggling terrain on and off, see #1185. Once addressed, I think we can merge this to main and create a pre-release.

2022-05-12 14:53 UTC, HarelM approved these changes

2022-05-12 14:54 UTC, merged

2022-08-26 08:55 UTC, birkskyum commented
There's some progress no this Brave issue. It turns out that as a quick-fix they reverted the z-value on these spikes, so tiny spikes still appear, but all the big ones now appear as holes in the terrain instead, which is less invasive but still a bug.

Chrome:
<img width="685" alt="Screen Shot 2022-08-26 at 10 52 56" src="https://user-images.githubusercontent.com/74932975/186866719-458775aa-89e0-4e18-b53b-89744955883d.png">

Brave:
<img width="684" alt="Screen Shot 2022-08-26 at 10 53 01" src="https://user-images.githubusercontent.com/74932975/186866696-a81c51a9-6e1d-4c51-8cba-72040ba3b946.png">