WIP: Generate type declaration file for style-spec module
maplibre/maplibre-gl-js pull request #1116
Opened 2022-03-21 17:51 UTC by achou11

Fixes #1107 

This is (so far) my naïve attempt to generate the appropriate type declaration file for the `style-spec` module. I'm not really an expert in how to do this and I tried my best to keep it in line with the process for doing it for the gl module. I'm fully prepared to change as much as needed based as there are still a couple of issues with the generated file (which I will point out in comments) - hoping that feedback will fill those holes.

Generating a cleanish file required some small source changes, of which I'm not sure are okay/safe in the context of versioning. Feedback most welcomed!

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [ ] ~Include before/after visuals or gifs if this PR includes visual changes.~
 - [ ] ~Write tests for all new functionality.~
 - [ ] ~Document any changes to public APIs.~
 - [ ] ~Post benchmark scores.~
 - [ ] ~Manually test the debug page.~
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-03-21 17:53 UTC, achou11 commented on src/style-spec/dist/index.d.ts
> +import Point from '@mapbox/point-geometry';
> Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!

just making sure, but is the inclusion of this line okay given the ^ in the PR template?

2022-03-21 17:54 UTC, achou11 commented on src/style-spec/dist/index.d.ts
> +	 as v8,
not sure what to do about these invalid lines. would it be okay to omit or is there something that needs to be adjusted in the source?

2022-03-21 17:55 UTC, achou11 commented on src/style-spec/dist/index.d.ts
> +export {};
not sure what's generating this line, if anyone who's more knowledgeable knows

2022-03-21 17:55 UTC, HarelM commented on src/style-spec/dist/index.d.ts
> +import Point from '@mapbox/point-geometry';
No, this file should not be checked in.

2022-03-21 17:56 UTC, achou11 commented on src/style-spec/expression/parsing_error.ts
> +class ExpressionParsingError extends Error {
opted to rename this class because it conflicts with the `ParsingError` in `style-spec/error/parsing_error.ts` when generating the types via `dts-bundle-generator`. not sure if this is safe or necessary to begin with

2022-03-21 17:57 UTC, achou11 commented on src/style-spec/package.json
> +    "generate-typings": "node --loader ts-node/esm --experimental-specifier-resolution=node build/generate-typings.ts"
wasn't sure if it made sense to keep this script within the `style-spec` module or if it's preferred to have it in the parent module scope

2022-03-21 17:57 UTC, HarelM commented on src/style-spec/expression/index.ts
> +import ExpressionParsingError from './parsing_error';
Is there another place where this name is used? Is this why you changed the name?

2022-03-21 17:59 UTC, achou11 commented on src/style-spec/expression/index.ts
> +import ExpressionParsingError from './parsing_error';
See https://github.com/maplibre/maplibre-gl-js/pull/1116#discussion_r831394848 for the context of why I changed the name. Not sure if it's a necessary change but it played more nicely with the dts generator

2022-03-21 17:59 UTC, achou11 commented on src/style-spec/dist/index.d.ts
> +import Point from '@mapbox/point-geometry';
just to clarify, are you talking about the declaration file or just that line? if the latter, what's the workaround?

2022-03-21 17:59 UTC, HarelM commented on src/style-spec/build/generate-typings.ts
> +import fs from "fs";
I would not create a duplicate file here, but instead, make the other existing file generate both typings.

2022-03-21 18:00 UTC, achou11 commented on src/style-spec/build/generate-typings.ts
> +import fs from "fs";
makes sense! will fix

2022-03-21 18:01 UTC, HarelM requested changes
Thanks for stepping up!!
Note that in order to test this I used to copy the file into the node_modules folder of the project I wanted to see that works, otherwise it's hard to test this...

2022-03-21 18:02 UTC, HarelM commented on src/style-spec/dist/index.d.ts
> +import Point from '@mapbox/point-geometry';
The entire file.

2022-03-21 18:03 UTC, HarelM commented on src/style-spec/dist/index.d.ts
> +	 as v8,
I needed to remove all imports that had "as ..." in order for the tool to work

2022-03-21 18:04 UTC, achou11 commented
> Thanks for stepping up!! Note that in order to test this I used to copy the file into the node_modules folder of the project I wanted to see that works, otherwise it's hard to test this...

Thanks for the quick initial review! and yeah luckily i have a direct need for this as I mentioned in the issue 😄 so far the types themselves seem okay, but yeah this PR mostly needs help from a structure point of view, which you've already provided most of the necessary input on

2022-03-21 18:05 UTC, HarelM commented on src/style-spec/dist/index.d.ts
> +export {};
No clue. But feel free to contact the developer of the package, he is super responsive!

2022-03-21 18:06 UTC, HarelM commented on src/style-spec/package.json
> +    "generate-typings": "node --loader ts-node/esm --experimental-specifier-resolution=node build/generate-typings.ts"
Better to have it in the parent package

2022-03-21 18:07 UTC, HarelM commented on src/style-spec/expression/parsing_error.ts
> +class ExpressionParsingError extends Error {
Yea, this seems somewhat problematic as it might break the public API... :-/ not sure I have an idea how to fix this though...

2022-03-21 18:22 UTC, achou11 commented on src/style-spec/dist/index.d.ts
> +import Point from '@mapbox/point-geometry';
gotcha. will probably keep it as this PR is being reviewed for now to make it easier to review the generated types, if that's okay?

2022-03-21 18:34 UTC, achou11 commented on src/style-spec/expression/parsing_error.ts
> +class ExpressionParsingError extends Error {
damn 😭 i don't really have enough context or knowledge to know how to proceed, but any ideas are much appreciated!

2022-03-21 18:36 UTC, achou11 commented on build/generate-typings.ts
> +    childProcess.execSync(`dts-bundle-generator --no-check -o ${outputFile} ${moduleBasePath}/style-spec.ts`);
do any other flags need to be passed for this? i see that `-umd-module-name` is used for the gl types process - will style-spec need something similar?

2022-03-21 19:04 UTC, HarelM commented on build/generate-typings.ts
> +    childProcess.execSync(`dts-bundle-generator --no-check -o ${outputFile} ${moduleBasePath}/style-spec.ts`);
I don't believe so, no.

2022-03-21 19:06 UTC, HarelM commented on build/generate-typings.ts
> +    let types = fs.readFileSync(outputFile, 'utf8');
I'm not sure this hack is needed in this case, it's only relevant due to umd stuff I believe

2022-03-21 19:09 UTC, HarelM commented on src/style-spec/expression/parsing_error.ts
> +class ExpressionParsingError extends Error {
Both parse error types are used in the generated types of stylespec? If not then I would only change the one that is not being used/exported... If there's no other option, we will need to release this only as part if a breaking change version I guess...

2022-03-21 19:11 UTC, HarelM commented on build/generate-typings.ts
> +    let types = fs.readFileSync(outputFile, 'utf8');
I.e. If the generated file is fine for your usage don't do the extra edit of the file (these 4 lines after the exec)

2022-03-21 19:13 UTC, HarelM commented on src/style-spec/dist/index.d.ts
> +import Point from '@mapbox/point-geometry';
If the types are working for you when you use them in your project I think it's good enough, I don't plan to review the generated file, just FYI :-)

2022-03-21 19:36 UTC, achou11 commented on src/style-spec/dist/index.d.ts
> +	 as v8,
are you referring to imports only for the ones in question (`latest` and `v8`), or others as well?

2022-03-21 19:38 UTC, achou11 commented on src/style-spec/expression/parsing_error.ts
> +class ExpressionParsingError extends Error {
yeah i believe so. At least that's how it looks to me after a relatively brief check of the source

2022-03-21 19:39 UTC, achou11 commented on src/style-spec/composite.ts
> +export default function composite(style) {
addressed via https://github.com/maplibre/maplibre-gl-js/pull/1116/commits/eca7f166e0cbcccc8773666730c2908e545fb52e

2022-03-21 19:42 UTC, HarelM commented on src/style-spec/composite.ts
> + * @param {object} style an uncomposited Mapbox GL Style
Maplibre not mapbox, I think...

2022-03-21 19:46 UTC, achou11 commented on src/style-spec/composite.ts
> + * @param {object} style an uncomposited Mapbox GL Style
haha whoops! i copied from the readme in the mapbox project. my bad 😅

2022-03-21 19:47 UTC, HarelM commented on src/style-spec/dist/index.d.ts
> +import Point from '@mapbox/point-geometry';
There're many places were types can be improved, no doubt, so every little step forward will help :-)
I think this is important to have in this library, breaking a single error class name should not be a justification not to add this.

2022-03-21 19:49 UTC, HarelM commented on src/style-spec/composite.ts
> + * @param {object} style an uncomposited Mapbox GL Style
Make sure you don't copy stuff from mapbox as their license forbids it...

2022-03-21 19:49 UTC, achou11 commented on src/style-spec/composite.ts
> +export default function composite(style) {
ah whoops. guess i should do that for `migrate` and `format` too? Is it okay to just use `any` for now or would you prefer the proper style spec typings and all 😅

2022-03-21 19:54 UTC, achou11 commented on src/style-spec/composite.ts
> +export default function composite(style) {
also tbh not sure i'm familiar enough to properly update the types 😄

2022-03-21 20:06 UTC, HarelM commented on src/style-spec/composite.ts
> +export default function composite(style) {
According to the code below `style` looks like of type `StyleSpecification` or something similar, I don't remember by heart...

2022-03-21 20:10 UTC, achou11 commented on src/style-spec/composite.ts
> +export default function composite(style) {
yeah i think that's right, although the tests for it seem to use v7 of the style spec, which doesn't align with the type (has `version: 8`)

2022-04-06 08:50 UTC, HarelM commented
Where are we with this PR? is it ready to be merged or should it be converted to draft until it is ready?

2022-04-06 12:29 UTC, achou11 commented
let's convert to a draft for now. sorry just haven't had the bandwidth to fix the issues with it yet 😅

2022-07-06 02:12 UTC, closed without merging