Encode hash char in render result path
maplibre/maplibre-gl-js pull request #1121
Opened 2022-03-23 17:36 UTC by drwestco

Bugfix for render test results page. Some of the test paths have '#' chars, which need to be encoded for the expected/actual/diff images to show.

2022-03-23 19:43 UTC, HarelM approved these changes

2022-03-23 19:44 UTC, HarelM commented
BTW, IIRC the way it worked before was using base64 string so that the html has everything in it and is not related to relative path etc.
You can consider adding back this logic... :-)

2022-03-23 20:56 UTC, drwestco commented
Yeah, I noticed the base64 approach from the old page. Seemed redundant, when the saved PNGs are right there.

2022-04-06 08:49 UTC, HarelM commented
But then this file can't be upload and it only servers for local usage.
If you encode it in base64 then you can upload the file to github actions artifacts for example and be able to see it without the need to re-run it...

2022-04-07 19:49 UTC, HarelM requested changes
Instead of fixing the url and in order to allow viewing this file everywhere I believe reverting to the base64 is a better solution.

2022-04-12 19:10 UTC, HarelM commented
@drwestco any chance to address the review comments so this PR can be merged?
Thanks!!

2022-04-13 20:12 UTC, HarelM approved these changes

2022-04-14 04:16 UTC, merged