Add terrain to style spec
maplibre/maplibre-gl-js pull request #1138
Opened 2022-03-31 17:57 UTC by HarelM

Add terrain to style spec and apply it when setting a style.
@prozessor13 @wipfli @birkskyum please review and let me know if I missed something.
I've used the debug page to make sure it works, nothing extra.

2022-04-02 12:41 UTC, wipfli commented
Adding this will make some manual updates on the docs website necessary. Please open an issue in maplibre/maplibre-gl-js-docs such that we don't forget...

<img src="https://user-images.githubusercontent.com/53421382/161383752-29dcedb3-6667-4136-8d92-d14157a0169e.png" width=550>

2022-04-02 12:42 UTC, wipfli commented on debug/terrain.html
> +    style.sources.terrain = {
Should we check that `style.sources` is not undefined?

2022-04-02 12:46 UTC, HarelM commented on debug/terrain.html
> +    style.sources.terrain = {
Well... We assume a lot when fetching this style, so assuming it has sources is OK I believe...

2022-04-02 12:52 UTC, wipfli commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
Actually I don't know what `elevationOffset` does. Can you explain it to me and put a more explicit description in the doc string?

2022-04-02 12:53 UTC, wipfli commented on src/style-spec/reference/v8.json
> +      "default": 1.0,
I have a vague memory that a good value was also 0.33. Are we sure that 1.0 is the default we want?

2022-04-02 12:54 UTC, wipfli requested changes
Thanks @HarelM. This looks good to me in general. Please update the doc string for `elevationOffset`.

2022-04-02 13:10 UTC, wipfli commented
Exaggeration 1:

<img src="https://user-images.githubusercontent.com/53421382/161384762-277b1cf6-4fd3-43a9-bf08-2d848b4bb562.png" width=650>

Exaggeration 0.33:

<img src="https://user-images.githubusercontent.com/53421382/161384793-9d1b9521-0753-49a8-a89f-298f56117a3d.png" width=650>

http://0.0.0.0:9966/debug/terrain.html#11.29/46.4557/8.1334/12.8/57

2022-04-02 13:10 UTC, wipfli commented
Maybe this is the wrong thread to discuss the right default value for `exaggeration`. But a value of 1 with the tiles provided by the debug example source seems too much for me.

2022-04-02 13:12 UTC, HarelM commented
This is the wrong thread IMHO, I've simply copied the value from the code...

2022-04-02 13:13 UTC, wipfli commented
Looks like exaggeration is discussed here https://github.com/maplibre/maplibre-gl-js/issues/1047

2022-04-02 13:14 UTC, HarelM commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
This is an offset "up" to prevent problems in places below see level like the Dead Sea, I'm not sure what to write here honestly...

2022-04-02 13:31 UTC, wipfli commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
Where is the default value of 450 coming from?

2022-04-02 13:31 UTC, wipfli commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
http://0.0.0.0:9966/debug/terrain.html#15.19/31.630547/35.576456/136.8/59 in the Dead Sea looks identical for different values of elevationOffset. Am I missing something?

2022-04-02 13:51 UTC, wipfli commented
Here we don't need a terrain, right?

2022-04-02 13:51 UTC, HarelM commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
I think it got white due to rendering issues when setting this to lower values, not sure if this was an initial problem that got sorted out or not...

2022-04-02 13:54 UTC, HarelM commented
The generation code seems to work, so I don't think anything social is needed... Feel free to experiment with it.

2022-04-02 14:03 UTC, wipfli commented
Do we need to update `validate_style.ts`?

https://github.com/maplibre/maplibre-gl-js/blob/f1587249d082dc1992bdedc606c7ada84a232c71/src/style/validate_style.ts#L26-L28

2022-04-02 14:04 UTC, wipfli commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
@prozessor13 can you comment on the status of `elevationOffset`?

2022-04-02 14:07 UTC, wipfli commented
And are there any tests we should add?

2022-04-02 19:58 UTC, HarelM commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
When I set `elevationOffset: 1` I get an assertion error which causes the map to stop responding when I pan near the dead sea.
I couldn't reproduce this with the regular `elevationOffset`.
![image](https://user-images.githubusercontent.com/3269297/161399198-6c267a9d-8bab-4028-ba32-7cc36070d1e3.png)

2022-04-02 20:03 UTC, HarelM commented
See https://github.com/maplibre/maplibre-gl-js-docs/issues/155 for the docs issue.

2022-04-02 20:06 UTC, HarelM commented
>Here we don't need a terrain, right?

I think the default case covers terrain well, it could probably cover light I believe:
```
default:
                return `${property.type.slice(0, 1).toUpperCase()}${property.type.slice(1)}Specification`;
```

2022-04-02 20:34 UTC, HarelM commented
I'll add some tests and also probably I need to add some code to `style-spec/validate` library.
Moving this to be a draft until I'm done.

2022-04-04 10:16 UTC, prozessor13 commented on src/style/style.ts
> +    setTerrain(options?: TerrainSpecification) {
I think some additional checks are required:

* `this._checkLoaded();`
* `if (!this.sourceCaches[options.source]) throw new Error(`cannot load terrain, because there exists no source with ID: ${options.source}`);

But i can create them after merge as well, as you like.

2022-04-04 10:24 UTC, prozessor13 commented on debug/terrain.html
> +fetch('https://static.maptoolkit.net/styles/toursprung/terrain.json').then((req) => req.json()).then((style) => {
Complete offtopic, but we have to switch away from our toursprung-terrain style. So i think its better to create a terrain stylesheet with the terrain tag already included.
May a minimal style with only one raster-laster of free satellite images draped over terrain.

But for me this is a separate discussion and not a topic of this PR.

2022-04-04 10:29 UTC, prozessor13 commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
The offset is/was necesarry because otherwise the near/far clippingplanes drops out areas below zero. But this is may already obsolete? I will test this, and ideally create a test ;)

2022-04-04 10:33 UTC, prozessor13 reviewed
Hi Harel, thanks for doing this! All comments from my side are more like notes, not change requests. So its looking good to merge!

Regards. Max.

2022-04-04 14:21 UTC, HarelM commented on debug/terrain.html
> +fetch('https://static.maptoolkit.net/styles/toursprung/terrain.json').then((req) => req.json()).then((style) => {
I've answered in the #1159 thread - it would be great to create a small style with data hosted in the demotiles repo if we want to keep this html file.

2022-04-04 14:22 UTC, HarelM commented
Thanks for the review @prozessor13! I'll add the validation logic later tonight (I hope) and after it will be reviewed I'll merge this to the 3d branch.

2022-04-04 15:17 UTC, HarelM commented
@wipfli @birkskyum I was unable to add the validation code, not sure what's wrong.
The minute I added the code related to terrain validation the tests started failing (all of them like there's something wrong with the build and not with the code itself).
If you have some time to look at this it would be great.
If not, we can always add this later as I don't think this is a stopper to merge this to the terrain branch.

2022-04-04 15:22 UTC, HarelM commented
p.s: relevant code:
added code to `validate.ts`, `validate_style.min.ts`, `validate_style.ts` (same as `light` basically)
and the following file `validate_terrain.ts`:
```ts
import { validate, ValidationError } from "../style-spec";
import getType from "../util/get_type";

export default function validateTerrain(options: any) {

    const terrain = options.value;
    const styleSpec = options.styleSpec;
    const terrainSpec = styleSpec.terrain;
    const style = options.style;

    let errors = [];

    const rootType = getType(terrain);
    if (terrain === undefined) {
        return errors;
    } else if (rootType !== 'object') {
        errors = errors.concat([new ValidationError('terrain', terrain, `object expected, ${rootType} found`)]);
        return errors;
    }

    for (const key in terrain) {
        if (terrainSpec[key]) {
            errors = errors.concat(validate({
                key,
                value: terrain[key],
                valueSpec: terrainSpec[key],
                style,
                styleSpec
            }));
        } else {
            errors = errors.concat([new ValidationError(key, terrain[key], `unknown property "${key}"`)]);
        }
    }

    return errors;
}
```

2022-04-05 19:34 UTC, HarelM commented on src/style-spec/reference/v8.json
> +      "doc": "The elevation offset.",
This will be addressed in terrain branch, resolving this conversation.

2022-04-05 19:40 UTC, HarelM commented
The problem was with wrong imports suggested by the IDE :-(
In any case this is now solved.
The only thing I've added since the review is a validator for the terrain and covered it with tests (which doesn't exist for the other validators unfortunately...).
I believe this is ready to be merged to the terrain branch.

2022-04-06 09:22 UTC, wipfli approved these changes
Thanks for adding the terrain validation code and also nice that you added a first test!

2022-04-06 09:22 UTC, merged