Fixes related to console errors and some typings improvement in terrain branch
maplibre/maplibre-gl-js pull request #1182
Opened 2022-04-12 19:02 UTC by HarelM

Fixes #1180 and also addresses the marker timeout issue when a marker is removed.
@wipfli @prozessor13 Feel free to review.

2022-04-13 05:40 UTC, prozessor13 reviewed
Thanks for this pull request! Great Work :)

To fix the [0, 0] thing, i think there needs a change in https://github.com/maplibre/maplibre-gl-js/blob/terrain3d/src/render/terrain.ts#L329. Please try:

    gl.readPixels(p.x, painter.height / devicePixelRatio - p.y - 1, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, rgba);

It looks like that the y-coordinate is calculated wrong (from 1 to height, instead of 0 to height-1), so the `py - 1` should does the trick. Hopefully with this fix the map gets more stable under the mousepointer when panning in heavy tilted terrain.

2022-04-13 19:45 UTC, HarelM commented
@prozessor13 thanks for the input! adding a `- 1` seems to solve the issue.
However, I wanted to create a test to imitate the code that runs but was unable to fully understand how webgl framebuffers work :-(
The following is the test I started for the `terrain.ts` file i.e. `terrain.test.ts`:
```ts
import Point from "@mapbox/point-geometry";
import Terrain from "./terrain";
import gl from 'gl';
import Context from "../gl/context";

describe('Terrain', () => {
    test('pointCoordiate should not return null', () => {
        const style = {
            map: {
                painter: {
                    context: new Context(gl(10, 10)),
                    width: 10,
                    height: 10
                }
            }
        } as any;
        const terrain = new Terrain(style, {} as any, {} as any);
        
        const coordinate = terrain.pointCoordinate(new Point(0,0));

        expect(coordinate).not.toBeNull();
    });
});
```

Any help would be appreciated in order to make the test fail when the `- 1` is missing and passing when we add the `- 1`.
I know I should ramp up with webgl etc going forward, but that's the best I can do at the moment.
I guess there's a need to fill the `_fbo` and the `_coordsIndex` the right way, which is done by the program and not the code here, but we should be able to mock that in this test I believe...
Feel free to push a test file directly to this branch if you happen to work on it.
I'll continue tomorrow I believe.

2022-04-14 05:37 UTC, prozessor13 commented
Hmm. To get this test working i think it would be the easiest to fake all webgl classes/opjects, like: (NOTE: this code is not teststed!)

```` typescript
describe('Terrain', () => {
    test('pointCoordiate should not return null', () => {
        const x = null, y = null, tileID = null, framebuffers = [];
        const style = {
            map: {
                painter: {
                    height: 10,
                    context: {
                        gl: {
                            readPixels: (_x, _y) => {
                                x = _x;
                                y = _y;
                            }
                        }
                    },
                    bindFramebuffer: {
                        set: fb => {
                            framebuffers.push(fb);
                        }
                    }
                }
            }
        } as any;
        const sourceCache = {
            getTileByID: id => {
                tileID = id;
                return new OverscaledTileID(1, 0, 1, 0, 0);
            }
        } as any;
        const terrain = new Terrain(style, sourceCache, {} as any);
        terrain.getFramebuffer = fb => {
            return { framebuffer: fb };
        };
        terrain.getElevation = () => 123;
        for (let i = 0; i < 256; i++) terrain._coordsIndex[i] = i;
        
        const coordinate = terrain.pointCoordinate(new Point(0,0));

        expect(coordinate).not.toBeNull();
        // check others: x, y, tileID, framebuffers, coordinate
    });
});
````

2022-04-14 05:48 UTC, HarelM commented
I've started with mocking a lot of things but I saw that I need to mock too many stuff.
I prefer not to mock a function in a class I test to make sure it works as closely to the original and only mock external dependencies.
Having said that, your approach might be faster.
P.S. `_coordsIndex` is being filled outside this class, right? Shouldn't it be a public and a not private member?

2022-04-14 06:05 UTC, prozessor13 commented
Yes you are right, _coordsIndex should be public.

To test the math behind terrain.pointCoordinate i think it is fine to write these mockups, and to test the whole webgl stuff i think it will much easier to write integration-tests and compare results visually. Doing this it would be easy to implement a debug flag, which then writes the coords/depth framebuffers to screen.
But the problem with integration tests are, that they are not working when terrain is enabled. Last week I debugged several hours to make integration tests working without success. I will create a ticket for this.

2022-04-14 08:02 UTC, HarelM commented
In general, testing the whole webgl stuff in integration tests is probably the right approach, having said that, I think that in our specific case using a single framebuffer should be something we should be able to mock - not just for the sake of not mocking class function but also since it's a good reference to how to be able to mock low level things.
I agree that if it is super complicated and the test code becomes very complex it is not the right direction, but I think that using the `gl` package in unit tests and using actual data inside the buffers can help imitating these exact interesting scenarios in unit tests which is super powerful.
I know I personally need to better educate myself in this, but if you could help out in instructing me how to get data into a framebuffer in the test code it can help me a lot.

2022-04-14 10:20 UTC, prozessor13 commented
Ok good point! A framebuffer reads/writes data to a texture or to the screen (which is may internally a texture as well, dont know?). So the way to prepare a mock framebuffer would be:

* create a RGBAImage, with already containing the mock-data, in our case the coords-data (= rgba encoded tile-coordinates)
* create a Texture for the RGBAImage
* create a framebuffer with the size of the RGBAImage
* attach the texture to the framebuffer via `colorAttachment.set`

With this scenario, i think it should be theretically possible to get the pointCoordinate thing working.
Starting with an empty texture and writing data into it (via the framebuffer) has to be done via `draw` calls. But draw-calls are even more complex. You need shaders, vertexbuffers and so on. We can make a call to discuss this in detail, but please next week :)

2022-04-14 19:23 UTC, HarelM commented
Ok, I think I managed to make it work, I'm not sure I'm 100% proud of the mocking I did, but when I remove the -1 the test fails which is what I wanted to achieve...
I think this is ready for review.

2022-04-14 19:46 UTC, wipfli requested changes
Thanks @HarelM for working on the blocking issues of the terrain 3d pull request. This goes in the right direction I think. Please add typings where requested.

2022-04-14 19:46 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Does not seem related to this pull request at first sight. Does maptiler have terrain tiles that we could use woth the examples api key?

2022-04-14 19:46 UTC, wipfli commented on src/geo/transform.test.ts
> +        } as any;
Can you cast to `Terrain`?

2022-04-14 19:46 UTC, wipfli commented on src/geo/transform.ts
> +            if (coordinate != null) {
The logic here is that if it is null, then it falls back to 2d?

2022-04-14 19:46 UTC, wipfli commented on src/render/terrain.ts
> +        gl.readPixels(p.x, painter.height / devicePixelRatio - p.y - 1, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, rgba);
Can you add a one line code comment why the `-1` is needed?

2022-04-14 19:46 UTC, wipfli commented on src/ui/marker.test.ts
> +        } as any;
`as any as Terrain`

2022-04-14 19:46 UTC, wipfli commented on src/ui/marker.test.ts
> +        jest.spyOn(global, 'clearTimeout');
Sorry I don't get how marker and settimeout are related...

2022-04-14 19:46 UTC, wipfli commented on src/render/terrain.test.ts
> +        } as any;
Add typing

2022-04-14 19:46 UTC, wipfli commented on src/render/terrain.test.ts
> +        } as any;
Add typing

2022-04-14 19:46 UTC, wipfli commented on src/render/terrain.test.ts
> +        const terrain = new Terrain(style, {} as any, {} as any);
Add typing

2022-04-14 19:50 UTC, HarelM commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
This page no longer works as the fetch is getting an error, so I fixed it a bit, but the terrain source I used is not very good, I didn't manage to use map tiler here unfortunately...

2022-04-14 19:51 UTC, HarelM commented on src/geo/transform.ts
> +            if (coordinate != null) {
Yes, not sure if it's actually needed after the fix of the -1, but I decided to keep it...

2022-04-14 19:53 UTC, HarelM commented on src/ui/marker.test.ts
> +        jest.spyOn(global, 'clearTimeout');
When moving the map the visibility of the markers change if they are behind a mountain. In order not to calculate this too many times, a timeout is used.
This is my understanding of the video at least...

2022-04-14 19:58 UTC, HarelM commented on src/render/terrain.ts
> +        gl.readPixels(p.x, painter.height / devicePixelRatio - p.y - 1, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, rgba);
This is regular array location math - if `height` is in the size of the array you need to reduce 1 in order to be inside the array range `(0..height-1)`.
I don't feel like a comment here is needed...

2022-04-14 20:02 UTC, HarelM commented
I feel like the "add typings" is a pay back for all the "add typings" I wrote in the past :-)
I've fixed them and answered all the other conversations.

2022-04-14 20:03 UTC, wipfli commented
Haha yes indeed

2022-04-14 20:04 UTC, wipfli commented on src/ui/marker.test.ts
> +        jest.spyOn(global, 'clearTimeout');
Ah interesting, thanks

2022-04-14 20:09 UTC, wipfli approved these changes

2022-04-14 20:41 UTC, merged

2022-04-15 12:57 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
I don't know if you still need these since you switched to the maptiler terrrain, but I made this N047E011 region mbtiles to match the location we used in the debug page

https://drive.google.com/drive/folders/1mur4b0O8_qWUWvO-S4-fb74K99bOESpZ?usp=sharing

A demo of it is here. https://stackblitz.com/edit/web-platform-fvinfs?file=index.html . You can see if you zoom out the terrain is only for that region.

2022-04-15 14:08 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
I also put a N045E007 demo tile there. which i think is more swiss alps. i tried to get Matterhorn, Switzerland, but that is close to the edge of the tile.

2022-04-15 14:38 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Oh wau, this is really cool. Can you help me unpack the mbtiles file into a bunch of files in a folder? There is a tool for this, right?

2022-04-15 14:40 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Is https://github.com/mapbox/mbutil the tool of choice?

2022-04-15 14:42 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Haha I am almost tempted to try converting this to PMTiles. @bdon do you think your adapter would work with terrain tiles?

2022-04-15 15:50 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
mbutil seems like it worked. I uploaded zip files with the extracted images to the same place
https://drive.google.com/drive/folders/1mur4b0O8_qWUWvO-S4-fb74K99bOESpZ?usp=sharing

2022-04-15 15:56 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Basically I just made these by going to https://www.eorc.jaxa.jp/ALOS/en/dataset/aw3d30/aw3d30_e.htm . There is a download page there that you need to register for a free accountt. Once you get to the download page you can download regions of geotiffs

Then I put the DSM.tif files from the downloads into a input folder, and run this script against them 
https://github.com/acalcutt/jaxa_AW3D30_to_MBTiles/blob/main/create_terrainrgb.sh
(i changed max zoom from 14 to 12 when i ran it because it doesn't really add anything and makes the file size much bigger)

2022-04-15 16:10 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Wau this worked! 

![image](https://user-images.githubusercontent.com/53421382/163594188-7d5e67d1-fd5c-48ad-9af1-25802cf6cec9.png)

2022-04-15 16:13 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
This bit is 43 MB. Do you know how large the planet would be if we only went to zoom level 12?

2022-04-15 16:16 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
...I guess it is much more than the 1 GB size limit on GitHub Pages.

2022-04-15 16:31 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
The planet mbtiles file I use, which is only to zoom level 12, is 446GB. 
https://drive.google.com/drive/folders/1tvJSr_4wq7kaxe1hOOGAK_oDWFYrMTcx

So yes, definitely over the 1G limit... haha. My understanding is you can't really compress the pngs files in any way as they are basically meant to be "raw" files. the size is about the same as the geotiffs I put into it.

I could probably do a a slightly bigger region though, a 1deg X 1deg file was about a 19MB images and generated a 43MB of files. 5deg x 5deg looks like it is about 300MB, so that may make it under 1G

2022-04-15 16:39 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Interesting. But all the ocean tiles are already compressed away, right?

2022-04-15 16:39 UTC, wipfli commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
I started a pull request in the demotiles repo. https://github.com/maplibre/demotiles/pull/5

2022-04-15 19:04 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
I made two pull requests against your branch. one to change the README and one to do a bigger area. Not sure if you want them both so I did them separately.

2022-04-17 07:09 UTC, bdon commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
@wipfli terrain tiles or raster images should work fine with the PMTiles adapter, but I haven't tested it, there might be some quirk of the current adapter that I need to fix :p but yeah, if you want to stick them into a Github repository you'll hit the size limit quickly.

2022-04-19 21:53 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
I tried to convert my terrainrgb mbtiles file to pmtiles here ( https://wifidb.net/demo/pmtiles/jaxa_terrainrgb_N047E011_0-12.pmtiles )

But I tried to use it based on the maplibre pmtiles demo page (combined with the terrain demo page here),
https://stackblitz.com/edit/web-platform-d2icls

Did I do anything wrong in that demo page?

2022-04-19 21:57 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
Seemed like it had converted ok...or at least saw all the tiles
```
pmtiles-convert jaxa_terrainrgb_N047E011_0-12.mbtiles jaxa_terrainrgb_N047E011_0-12.pmtiles
compression: disabled
Num tiles: 341
Num unique tiles: 341
Num leaves: 0
```

2022-04-19 22:07 UTC, acalcutt commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
actually, I think it does work. I threw it on my domain where the pmtiles file is located and it looks like it worked there
https://wifidb.net/demo/pmtiles/

2022-04-20 03:36 UTC, bdon commented on debug/terrain.html
> +                url: 'put-your-terrain-tile-source-url-here',
@acalcutt  The `pmtiles-convert` and your 2nd demo link seem to work fine.

For your stackblitz demo, it might be failing since you're doing a cross-origin request from stackblitz.com to your server, but your server is not returning CORS headers. The error message I'm seeing in Safari isn't great at indicating this.