fill: opacity per layer
maplibre/maplibre-gl-js pull request #1191
Opened 2022-04-19 16:49 UTC by tongust

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-04-19 16:58 UTC, tongust commented
This P/R is to resolve the open issue https://github.com/mapbox/mapbox-gl-js/issues/4090.

2022-05-03 19:04 UTC, wipfli commented
Looks interesting, thanks. Can you post the full CLI benchmark results? And can you ping me on slack?

2022-05-04 16:17 UTC, tongust commented
> Looks interesting, thanks. Can you post the full CLI benchmark results? And can you ping me on slack?
Updated all results in [above Benchmarks Benchmarks](https://github.com/maplibre/maplibre-gl-js/pull/1191#issuecomment-1102879894).

2022-05-04 18:12 UTC, HarelM commented
I'm not sure the name is intuitive, also I'm not sure I understand what it should solve.
Can you elaborate a bit more about this?
The triangles above are different but it's not clear why and what caused each rendering.

2022-05-05 09:23 UTC, tongust commented
> I'm not sure the name is intuitive, also I'm not sure I understand what it should solve. Can you elaborate a bit more about this? The triangles above are different but it's not clear why and what caused each rendering.

This pr is an attempt to address the legacy issue of mapbox ```https://github.com/mapbox/mapbox-gl-js/issues/4090```. The fill opacity style of main branch is per geometry, in some cases, per-layer is needed.

- Per-geometry (main branch). Each geometry is rendered immediately into main frame buffer (screen). And the results are: 
  - The opacity on overlapping area is changed. And it could be opaque if more geometries are stacked.
  - Its color is not same to the one of the last shape to add to the map.
 
- Per-layer. In each layer, every geometry is rendered into off-screen firstly and then all geometries of this layer are drawn into main frame buffer with some opacity. And the results are:
  - The opacity of whole layer is same.
  - The color is same to the one of top most shape.

And note that the per-layer opacity only supports fill type for now. For line and other type, they are in my TODO list.

2022-05-05 10:16 UTC, xabbu42 commented
@HarelM I think this feature is very important especially for lines as the current rendering is often not the desired effect. We have for example the use case of a semi-transparent street-network overlay over satellite images. currently intersections are two dark because multiple streets overlap. There are a lot of use-cases with images in multiple mapbox issues which would benefit from this.

@tongust It was my understanding that this is difficult to achieve in a performant way. Do you have any input on possible performance impact of this pull request with and without enabling the feature? 

I personally am not sure about the coverage of the benchmarks, but this seems as this should be covered so your change seems to not have any impact on existing styles. Is this result expected?

P.S. HillshadeLoad seems completely unproblematic and also almost certainly not connected to this pull request anyway. The difference just looks big in the graphic because this is a slow benchmark in general.

2022-05-05 16:46 UTC, tongust commented
> @HarelM I think this feature is very important especially for lines as the current rendering is often not the desired effect. We have for example the use case of a semi-transparent street-network overlay over satellite images. currently intersections are two dark because multiple streets overlap. There are a lot of use-cases with images in multiple mapbox issues which would benefit from this.
> 
> @tongust It was my understanding that this is difficult to achieve in a performant way. Do you have any input on possible performance impact of this pull request with and without enabling the feature?
> 
> I personally am not sure about the coverage of the benchmarks, but this seems as this should be covered so your change seems to not have any impact on existing styles. Is this result expected?
> 
> P.S. HillshadeLoad seems completely unproblematic and also almost certainly not connected to this pull request anyway. The difference just looks big in the graphic because this is a slow benchmark in general.

@xabbu42

- The per-layer opacity for line type is one of the TODOs. 

- Yes, impact is measured between main and the branch whose feature is forced to be enabled. There is no regression (especially for LayerFill).

![image](https://user-images.githubusercontent.com/13704175/166971473-78eb750c-30fc-46e7-a535-4b442a91bb63.png)

- Agree with you. This pr should have no imapct on existing styles, and the feature is disabled by default.

2022-05-05 17:41 UTC, HarelM commented
Thanks for the information!
Sorry for nagging, but in order to properly review this I need to better understand the design.
So some questions and requests:
1. How does it help to render the polygons in the offscreen canvas first? Does it merge the polygons in a way that overlapping polygons will be joint?
2. According to the explanation I would like to see a simpler tests: two polygons with the same color overlapping and creating a more opaque one before the fix and a smooth joint polygon after the fix, did I get it right?
3. A layer can have the opacity and color changed by data driven properties, how will this affect this feature?
4. Can you add some unit tests?

That's it for now, thanks a lot for all the hard work!

2022-05-07 17:34 UTC, tongust commented
> Thanks for the information! Sorry for nagging, but in order to properly review this I need to better understand the design. So some questions and requests:
> 
> 1. How does it help to render the polygons in the offscreen canvas first? Does it merge the polygons in a way that overlapping polygons will be joint?
> 2. According to the explanation I would like to see a simpler tests: two polygons with the same color overlapping and creating a more opaque one before the fix and a smooth joint polygon after the fix, did I get it right?
> 3. A layer can have the opacity and color changed by data driven properties, how will this affect this feature?
> 4. Can you add some unit tests?
> 
> That's it for now, thanks a lot for all the hard work!

@HarelM 

Sorry for the delayed reply.

### 1. About the design

Same to heatmap and hillshade types, one frame buffer object is created for fill to render to offscreen (not canvas actually). As we know, in painter, the [*offscreen* render pass](https://github.com/maplibre/maplibre-gl-js/blob/11ed977ab1c06be8d66aad58b9a13ca741552085/src/render/painter.ts#L406) is prior to others (opaque/translucent... passes).

For per-geometry opacity, there is no offscreen pass. Each geometry is drawn into canvas (screen) using alpha blending.

For per-layer opacity, there are two render passes. First one is offscreen pass. The color mode of rendering is set to 
```gl.blendFunc(gl.ONE, gl.ZERO);``` (additive blending), which means the destinated color = 1 x source color + 0 x background, namely the color will always be overridden by the latest geometry. In the second pass, the offscreen texture will be alpha-blended with the canvas in the same way as per-geometry opacity does.

![image](https://user-images.githubusercontent.com/13704175/167265266-54b5ddfd-e5fc-480b-a094-ab6c76aca866.png)

For example, there are two overlapping polygons red A and blue B. B is on the top of A. Their opacity is 0.5, and the background color is ```rgb(128, 128, 128)```

In per-geometry opacity, the process is:

- Alpha-blend A with background into screen: result color 0 = ```rgb(255, 0, 0)``` * 0.5 + ```rgb(128, 128, 128)``` * 0.5 = ```rgb(192, 64, 64)```
- Alpha-blend B with result color 0 into screen: final color = ```rgb(0, 0, 255)``` * 0.5 + ```rgb(192, 64, 64)``` * 0.5 = ```rgb(96,32,159)```

In per-layer opacity, the process is:

- Additive-blend A into fbo: result color 0 = ```rgb(255, 0, 0)```
- Additive-blend B into fbo: result color 1 = ```rgb(0, 0, 255)```
- Alpha-blend fbo with background into screen: final color = ```rgb(0, 0, 255)``` * 0.5 + ```rgb(128, 128, 128)``` * 0.5 = ```rgb(64,64,191)```


### 2. Sampler test cases
Here are the cases ([per-geometry opacity](https://codepen.io/L-Chen-MS/pen/KKQVWdY)):

|Current fill opacity| This new feature(by setting *fill-per-layer-opacity* as true) |
:-----------------------------:|:--------------------------------:
![image](https://user-images.githubusercontent.com/13704175/167264803-3582a398-2894-4e54-8496-50bd091b18e6.png)|![image](https://user-images.githubusercontent.com/13704175/167264810-c037cfbc-dfe5-4af6-a847-5113b6fbdf8c.png)

### 3. Data driven impact.

Good points! There was one bug here and now it is fixed. The opacity and color can be changed by data driven properties in per-layer opacity.

In below case, the opacity of left green geometry is 0.9 while the right one is 0.4.
![image](https://user-images.githubusercontent.com/13704175/167264960-bf6c0635-6b9e-41d1-bb53-a5e29a9ff0ae.png)


### 4. unit test.

Yes, the test draw_fill.test.ts is added.

2022-05-08 18:36 UTC, HarelM requested changes
Nit-picking.
I need someone to review the sharers code still.

2022-05-08 18:36 UTC, HarelM commented on src/render/draw_fill.ts
> +        const gl = painter.context.gl;
Should be extracted to another method

2022-05-08 18:36 UTC, HarelM commented on src/style-spec/reference/v8.json
> +    "fill-per-layer-opacity": {
I think `fill-opacity` should be the prefix. I tend to go the other way around, I.e. fill-opacity-per-geometry and have it true by default. IDK, just a thought. per-layer is still not intuitive enough for me...

2022-05-09 09:25 UTC, xabbu42 commented
Regarding the style spec changes. #48 seems to be related (correct me if I'm wrong). I personally don't know about the use cases for other blending modes but this seems the right time to discuss if we ever want to support other blending modes. In that case we have the option to make an enum setting instead of a boolean to add different blending modes.

2022-05-09 15:37 UTC, tongust commented on src/render/draw_fill.ts
> +        const gl = painter.context.gl;
Updated. Extract the per-layer render logic to a separated function

2022-05-09 15:37 UTC, tongust commented on src/style-spec/reference/v8.json
> +    "fill-per-layer-opacity": {
Agree with you, Renamed.

2022-05-09 16:22 UTC, HarelM commented on src/style-spec/reference/v8.json
> +          "js": "0.10.0",
These versions are probably wrong...?

2022-05-10 16:30 UTC, tongust commented on src/style-spec/reference/v8.json
> +          "js": "0.10.0",
Updated. Is v2.1.10 suitable?

2022-05-10 17:12 UTC, tongust commented
> Regarding the style spec changes. #48 seems to be related (correct me if I'm wrong). I personally don't know about the use cases for other blending modes but this seems the right time to discuss if we ever want to support other blending modes. In that case we have the option to make an enum setting instead of a boolean to add different blending modes.

@xabbu42 @HarelM 
#48 is a good reference, Enabling more blending modes is one powerful feature to maplibre, which needs well design and lots of coding tasks. I can change the opation as enum to support other modes in the future. But I don't think all other modes should be added into this PR. Maybe we can have several PRs to complete this wonderful feature, how do you think so?

2022-05-10 17:28 UTC, xabbu42 commented
I agree this PR should not be blocked just for supporting other layer types like line or more blending modes. The current limitations can be documented and we can add more support later without any backward compatibility problems.

If features as described in #48 will be possible and valuable in the future though, we should use an enum instead of a bool for the style spec already in this PR so that it is easier to add more blending modes later without any compatibility issues or inflating the spec with lots of not combinable bool settings.

Unfortunately I don't have the necessary knowledge to review the shader part.

2022-05-10 18:55 UTC, HarelM commented on src/style-spec/reference/v8.json
> +          "js": "0.10.0",
Sure, "js" will be the only one supporting this.
I just remembered you need to open an issue for the native repo in order to make sure this is implemented there in the future as well.

2022-05-10 18:58 UTC, HarelM commented
I'm not sure how urgent this is. We can make PRs against this branch to better define the spec possibilities. I prefer to take the time and define the spec well as it will be very hard to change it in the future...

2022-05-28 09:04 UTC, wipfli commented
I opened an issue in native to coordinate using the latest shaders, see https://github.com/maplibre/maplibre-gl-native/issues/293

2022-06-01 04:02 UTC, HarelM commented
I'm not sure from the name of the property and the options I understand what it does: comp-op is probably short for something (composition-operation?), I would advise against abbreviations...
Default and none are also not very descriptive.
Unfortunately, I don't have a suggestion for better names...

2022-06-01 17:50 UTC, tongust commented
> I'm not sure from the name of the property and the options I understand what it does: comp-op is probably short for something (composition-operation?), I would advise against abbreviations... Default and none are also not very descriptive. Unfortunately, I don't have a suggestion for better names...

@HarelM
- Renamed the property to ```fill-composite-operation``` refer to https://developer.apple.com/documentation/coreimage/methods_and_protocols_for_filter_creation/composite_operations.

- ```none``` to ```source-over``` refer to https://en.wikipedia.org/wiki/Alpha_compositing#:~:text=In%20computer%20graphics%2C%20alpha%20compositing,of%20partial%20or%20full%20transparency.

- ```normal``` to ```source-only``` refer to https://carto.com/help/tutorials/cartocss-compositing-operations/#alpha-composite-operations. Here the suffix ```-only``` is appended to make it more descriptive.

2022-06-08 05:18 UTC, HarelM commented
I believe this is good now. I'm happy with the new names.
The only question remaining in this thread is the per-line support. Let me know how you would like to move forward in this aspect.

2022-06-08 07:48 UTC, xabbu42 commented
What does source mean in this? I personally would assume the source to be the complete layer and destination to be the map, and that also seems to be how carto uses it. But this patch conceptually does not change how the layer gets composited on the map, instead it changes how the features of the layer are composited on the layer itself. So source here is a single line feature and destination is the layer before composing it on the map. At least to me this names are therefore confusing.

P.S. You are certainly right that implementation of other modes does not need to be part of this PR. Unfortunately for style spec changes we do need to already think about possible future features to avoid problems with backward compatibility in the future.

2022-06-08 15:31 UTC, tongust commented
> What does source mean in this? I personally would assume the source to be the complete layer and destination to be the map, and that also seems to be how carto uses it. But this patch conceptually does not change how the layer gets composited on the map, instead it changes how the features of the layer are composited on the layer itself. So source here is a single line feature and destination is the layer before composing it on the map. At least to me this names are therefore confusing.
> 
> P.S. You are certainly right that implementation of other modes does not need to be part of this PR. Unfortunately for style spec changes we do need to already think about possible future features to avoid problems with backward compatibility in the future.

@xabbu42 The source means the pixel to be drawn into the screen or offscreen in WebGL context (see https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc).

For composting each geometry of fill, the source means the latest geometry to be blended with rest geometries. The destination means the composted geometries, but it does not mean the map. So the `source` is the concept during the process of composting the geometrie.
For `source-only`, there are two composite operations: blend each geometry and blend this layer with the map.
For `source-over`, it could have two processes, too. But for performance, each geometry is blended into the map directly since the two composite operations are both `source-over`.

The name `fill-composite-operation` is a little confusing here. To distinguish with blending the layer with the map, `fill-geometry-composite-operation` should be better.

2022-06-08 16:24 UTC, xabbu42 commented
Thanks for the detailed explanations @tongust. So my confusion was not unfounded.

If we want to be flexibel in the future and support all manner of blending combinations it would make sense to have `layer-composite-operation` and `feature-composite-operation` (or `geometry-composite-operation`).

But if we only want to ever support some combinations with known use-cases I would prefer one property without the word operation (as the property potentially influences multiple different operations), something like `blending-mode` with values `feature-over` and `layer-over`.

I personally would have an obscure use case for `feature-copy` (or just `feature` or `source`?), that is for `layer-composite-operation` and `feature-composite-operation` set to `source`, but I'm not sure that is enough to add this capability to the library.

Just my 2 cents anyway.

2022-06-09 17:15 UTC, xabbu42 commented
I wonder if we can mark certain style spec features as experimental/use at your own risk. Then we could just go forward which changes like this, even include them in releases, without committing to support them exactly as they are implemented now.

2022-06-09 17:52 UTC, wipfli commented
Sounds like a good idea. It is really hard to never break the style spec but I think this should exactly be our goal... Mapbox aimed to never break the style spec, see https://github.com/mapbox/mapbox-gl-js/issues/6584

2022-06-14 11:50 UTC, xabbu42 commented
I made an issue to move this forward. I don't think this should block on that issue though. Imho it is enough to just document the new features in this branch as experimental as @HarelM suggested to merge it. We can add all the necessary code changes for experimental features retroactively after #1307 is resolved.

2022-06-20 10:19 UTC, HarelM commented
@xabbu42 where are we on this? Is the only pending comment is about the names?
I think the code it OK although I'm not very good with all the gl part so I assume this does what it should.

2022-06-23 17:08 UTC, xabbu42 commented
I tested the new debug page locally and it behaves as I would expect. As said I can't review the shader part. From my side the only thing missing is to document that this features are experimental and subject to change. Then we can merge this and postpone the decision on the final style spec.

2022-06-23 17:09 UTC, tongust commented
> Sure, per line can be a postponed to a different PR, but if it's something that can be added soon I think it would better to wait and merge them together and release a version that had them both. My 2 cents anyway...

@HarelM I am tring to extend the per-layer feature to the line, but unfortunately it is not easy job because gl codes of draw line are more complicate than ones of draw fill. Maybe we could split it out into another PR.

So if you agree not to wait for supporting line, the only pending comments are about the naming and claiming `Experimental` in the description.

@xabbu42 Thanks for your suggestions, I think it may be better to have below changes:
- `fill-composite-operation` to `fill-feature-composite-operation`
- `source-only` to `source`. And keep `source-over`. I personally think `source-over` is better than `feature-over` or `layer-over` since it is more popular.

2022-06-23 18:17 UTC, wipfli commented
Things to consider are:
* deprecation strategy
* overview of experimental parts
* version does not affect full style spec
* "available since" docs could have two versions, one for experimemtal and one for normal

2022-06-24 13:04 UTC, xabbu42 commented
@tongust: Just for clarification: the suggestions of feature-over and layer-over are meant as values for a single property blending-mode where there is more than one source and a value like source-over would not be clear.

For the separate property fill-feature-composite-operation source-over is perfectly fine and it would be silly to repeat the feature part which is already in the property name.

2022-06-24 13:26 UTC, xabbu42 commented
@wipfli I probably don't have the time today. Where would I find the info to join?

I do not have a strong opinion beyond what is already written in #1307 though.

2022-07-13 18:59 UTC, maxammann commented
> Things to consider are:
> 
>     * deprecation strategy
>     * overview of experimental parts
>     * version does not affect full style spec
>     * "available since" docs could have two versions, one for experimemtal and one for normal

Proposal based on "Rust ideas":

Essentially every, addition, removal or change to the style specification corresponds to a new version of the style spec. For example the addition of a **stable** feature would mean that we go from `v8` to `v8.1.0`. The addition of an **unstable** feature would not touch the style specification version. Whether a style property is **stable** or **unstable** can be specified in the style specification. This is similar to Rust stable features vs nightly features. 

If you want to use an **unstable** feature of the style specification then you have to specify it in the `style.json`:

```json
{
  "version": 8,
  "name": "OSM Liberty",
  "unstable-features": ["fill-comp-op", ...]
  ...
}
```

That way you have to opt-into unstable features in your style specification. **unstable-features** are only available if you use a nightly build of maplibre (can also be done runtime).

If you use this `style.json` in a maplibre implementation which does not support any of the `unstable-features` or `version` should reject the `style.json`. Same if *unstable* features are used in a stable configuration of maplibre (runtime or build-time).

@nyurik thats basically rust nightly/unstable features in maplibre :D

2022-07-13 19:33 UTC, HarelM commented
I was thinking more in the direction of a js property - i.e.:
```ts
import maplibre from 'maplibre-gl'
maplibre.useExperimetalFeatures = true;
```
Not sure I have a good reason as to why besides the fact that I want to change the spec as little as possible :-)
But it might be better to move this discussion to a different issue/PR/Discussion...

2022-08-31 14:00 UTC, JannikGM commented
I'm surprised I didn't comment here yet (I probably did on Slack?).

---

I feel this is a bit of a dangerous PR, because it can significantly raise rendering cost for a seemingly trivial property.
I also think that the parameterization isn't very reusable or flexible (..only works with fill type, no advanced blending modes, ..).

Maybe the shown approach is the more mapbox-ish thing to do, however, what I propose as an alternative is to add a new layer type (for advanced users) which can be used to split the layer stack into framebuffers.
Although, take this with a grain of salt, because I'm probably thinking about this a bit too technically (being a graphics programmer myself).

---

<details>

<summary><b> (Click here if you want to see my approach to this problem)</b><p></p></summary>

Introduce new layer types for starting rendering to framebuffer (setting a framebuffer) + stop rendering to framebuffer (resetting to default screen framebuffer) + blitting framebuffers.
More generally: grouping layers into some cache + drawing a cache.

**Example (layers from bottom to top):**

- type: cache-start, layoutProperties: { type: 'tiles' } layerId: basemap-cache
- type: background,  layerId: water
- type: fill,  layerId: land-rocks
- type: fill,  layerId: land-grass
- type: fill,  layerId: streets
- type: cache-end,  layerId: screen-rendering
- type: cache-draw, layoutProperties: { cache: 'basemap-cache', [...] },  layerId: basemap
- type: symbol+text,  layerId: street-labels

**What this means**

When rendering, the framebuffer would be set by the "cache-set" type layer.
The following layers after that would be rendered into that buffer until a "cache-reset" or another "cache-set".
Then, the framebuffer would be rendered using the "cache-draw" type layer and the street-labels would be drawn last.

This essentially creates layer-groups. This would make maplibre similar to how layers work in graphics editing software, where you can group a bunch of layers, and then composite them differently.
By providing parameters or filters to the blit, we'd be able to implement many more effects. CustomBlitLayer anyone?

There are at least 2 good strategies for the framebuffer: screen-space and tiles.
If the underlying layers don't change, one could also re-use the texture and improve map performance.
In the past, to get a similar effect, we'd initialize multiple mapbox instances, one for the basemap and one for animations.

Since terrain was added, something similar must already exist, too. Because for terrain you also need to render layers into a draping texture (ideally that is also tiled - I don't remember how that works in maplibre) for draping.

That said, it might be a bit tricky to make this work in the existing ecosystem, like CustomLayers, Heatmap or Hillshade, which already do something similar internally (but I think it's still very doable?).

**Design choices**

Aside from the layer types I mention here, it could also be parameterized differently, such as a "group-start" layer type which sets a framebuffer and a "group-end" layer type which would switch to the screen framebuffer and automatically also blit the current group.
However, I really like that you can draw a cache multiple times, as you might want to create effects like a glow (by first drawing the scene blurred, and then drawing the same scene sharp).

There might also be choices how nested groups would work or if they'd be allowed.

For 3D scenes it might be cool if the depth buffer remained the same, so where you place your group would suddenly be relevant (as you could place your layers infront of buildings [group before extruding buildings, blit after buildings], or behind buildings [group after rendering extruded buildings, blit after buildings]).

Also wether the the previous frame (or multiple?) would be cached etc. might be relevant (and if you could draw before writing to the framebuffer) . Such things could be used for effects like motion-blur.

**How to solve the original issue with my proposal?**

- [...]
- type: cache-set, layoutProperties: { type: 'tiles' } layerId: fill-per-layer-cache
- type: fill, layerId: fill-per-layer-contents
- type: cache-reset,  layerId: fill-per-layer-cache-end
- type: cache-draw, layoutProperties: { cache: 'fill-per-layer-cache', [...] }, paintProperties: { opacity: 0.5 },  layerId: fill-per-layer
- [...]

This is also similar to how this is implemented in this PR - except I propose that this technical detail is exposed for advanced user.

---

In fact, I did something similar for deck.gl (although it's quite hacky there, too). deck.gl is slightly better suited for it, because it has a layer hierarchy, rather than a list, and it takes whatever argument types you want (including WebGL textures/framebuffers). More importantly I don't need to modify deck.gl itself to implement this, I can just create my own layer outside of the deck.gl codebase.
So what I'd do in deck.gl is to wrap my layers in a "LayerGroup" and get a framebuffer which I can reference later.

That way, we can render some layers blurred (regardless of their type), or recolorize layers (including animations) without recomputing their entire content.

This is all very promising, but the issue with deck.gl is that I don't know what other layers do internally, and they also directly operate on WebGL, so a layer in a group can corrupt the "LayerGroup" renderer; also some built-in features of deck.gl are unaware of my cache.
I don't think this would be an issue for maplibre though.

</details>

---

2022-09-08 18:20 UTC, HarelM commented
@JannikGM there's a `CustomLayer` that one can use in order to do what you mentioned, I think.
Any chance you can show how this feature/issue can be implemented using this maplibre CustomLayer?
If this can be implemented, relatively easily, using a custom layer then this feature might be an edge case that can be solved this way and we wouldn't have to introduce this risk to maplibre's performance...?

2022-09-09 16:01 UTC, JannikGM commented
> @JannikGM there's a CustomLayer that one can use in order to do what you mentioned, I think.
> Any chance you can show how this feature/issue can be implemented using this maplibre CustomLayer?

I don't think you can implement my proposal (or this PR) in a custom-layer.
Either of these solutions (the one by tongust or mine) require changes to existing layers (tongust) or the render-algorithm (mine).
However, invoking existing layers (for tongust approach) or modifying the main render-algorithm (for my approach) is impossible from a custom-layer.

A custom-layer is merely an implementation of the (abstracted and simplified) mapbox layer interface where you get to run your own WebGL commands (or whatever else you want to do) when your layer gets rendered - however, it has no context about the layers which come before or after it, so it can't affect them.

That a layer has side-effects on other layers (as in my propsal) would also be something very new (hence, why I called the current PR more mapbox-ish).

> If this can be implemented, relatively easily, using a custom layer then this feature might be an edge case that can be solved this way and we wouldn't have to introduce this risk to maplibre's performance...?

To be clear: the performance risk only arises when people turn on the compositing mode for a fill layer, because at that point you end up with switching the framebuffer, which *can be* a costly operation. You also have to keep an extra framebuffer, for a 1080p resolution, that would likely be (2x 1920x1080 x 4 ~ 16MiB of video memory).
This cost of compositing might not be easy to understand for map-designers.
So the solution for the performance risk is to document that this can be a slow feature.
My proposal might be even worse in this regard.

The more serious issue with this PR (in my opinion), is that the implementation is in the fill layer, and not generic enough to be reusable with other layers or groups of layers. The solution to that is what I proposed, or at least moving it to the render-loop (similar to how we do terrain rendering probably).

---

I'm also fine with tongust approach, but I feel like we should implement it in the rendering loop (= so you could also have a source-comp operation on a symbol-layer for example) and not in each layer individually (leading to code duplication if we want to support other layers).
However, at that point, it would be similar to what I propose, with the exception that mine allows grouping multiple layers (for example, mixing a solid and fill layer, and then blending the combined result with an opacity).

For terrain rendering, we already render layers offscreen (= to a texture) in the main render loop, which is then draped over a terrain; so I assume that ingredients to this already exist. See this bit of code in the layer rendering loop which handles terrains:
https://github.com/maplibre/maplibre-gl-js/blob/f1252a01b8789f9bd038e1ebca5831daca8e5eb1/src/render/painter.ts#L474

Because it's so similar to a sub-problem of terrain rendering, I'd also be curious what @prozessor13 thinks (who is probably also most familiar with the revised maplibre layer rendering loop).

2022-10-13 05:43 UTC, prozessor13 commented
I did not digg in all details of this PR, and i can not say too much about gl-performance, but as @JannikGM already said, it is a similar scenario of rendering terrain. I think this feature would be very easy to integrate into the terrain-logic. Terrain-code currently already splits style-layers into stacks. e.g. a set of combinable layers which should be rendered to texture. So with some additions:
* create a new stack with only one layer when `comp-op` is setted
* drape the layer with opacity (or any other logic) to terrain

there would be (only in terrain3d) a general solution possible. 

Next. Your implementation, same as heatmap, is not compatible with 3d, because all is rendered to one big framebuffer, instead of rendered to tiles. Hillshade, in contrast to heatmap, creates a separate FBO (with a separate texture for each FBO) for every tile, and i think this is the way to go to work in 2d and 3d.
Render-to-texture uses the same logic, but instead of a separate FBOs connected to tiles, there exists a render-pool with currently a set of 30 FBOs. Theoretically this renderpool can be re-used, but i think an implementation the same way as the hillshade layer it should be good.

Overall i think this is a great feature, i would needed such a feature more than one time. To go around of this lack of functionality i always had to combine areas in vectortiles. possible, but a lot of work.

2024-01-09 14:22 UTC, HarelM commented
This has gone stale a bit, and we also moved the style-spec logic out of this repo.
Is this still interesting enough for someone to push forward or should we close this PR?

2024-01-16 00:40 UTC, sutarmin commented
Not feeling competent enough to push this forward, but it would be amazing to this feature implemented one way or another.

My use case is I'm drawing a `line` layer with several translucent lines representing a route. I can't use a single line for that because different bits can have different styling (representing road surface info). If I'm using any other `line-cap` than `round`, line junctions look ugly, but with `line-cap:round` lines overlap a bit, creating a weird visual effect. 

As I understand, such problems can be solved by the proposed feature.

<img width="421" alt="Screenshot 2024-01-16 at 03 30 52" src="https://github.com/maplibre/maplibre-gl-js/assets/2400312/203311bb-b9ae-4474-bfc0-536dd196cf9d">

2026-01-03 21:44 UTC, marinelbanea40-oss approved these changes

2026-05-13 23:44 UTC, CommanderStorm commented
this is a bit stale and we now have this discussion and a few PRs towards this.

- https://github.com/maplibre/maplibre/discussions/503

Lets close this PR as stale and thanks for everyone contributing to this

2026-05-13 23:44 UTC, closed without merging