icon-padding supports array
maplibre/maplibre-gl-js pull request #1289
Opened 2022-06-01 21:18 UTC by drwestco

Add new 'padding' type for style properties. Extend the behavior of icon-padding to support up to 4 values, including negative values, similar to how the CSS margin property works.

Replacement for #1237 - extending behavior of existing `icon-padding` instead of introducing a new property.

## Launch Checklist

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [X] Write tests for all new functionality.
 - [X] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-06-02 05:53 UTC, HarelM commented
This looks very good!
Can you share why a "padding" type is needed?
Is it because we can't write in the style "number or number array"?

2022-06-03 19:22 UTC, HarelM commented
I see, thanks for the extra info!
Few names that comes to mind for the "new" type:
Container, Rect, Wrapper, Border, BorderRect.
Not sure they are better than padding though.
I'll take a deeper look into the code now with the info you provided.

2022-06-08 05:29 UTC, HarelM commented on src/style-spec/expression/definitions/coercion.ts
> +            throw new RuntimeError(`Could not parse padding from value '${typeof input === 'string' ? input : String(JSON.stringify(input))}'`);
No Neff for the extra `String(`  I believe...?

2022-06-08 05:29 UTC, HarelM commented on src/style-spec/expression/definitions/coercion.ts
> +        } else if (this.type.kind === 'padding') {
I haven't seen tests for this part, can you please add?

2022-06-08 05:31 UTC, HarelM commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
Not sure I know what's expected of me with this comment...

2022-06-08 05:35 UTC, HarelM commented on src/style-spec/expression/index.ts
> +        if (specification.type === 'color' && typeof value === 'string') {
Seems like this is identical, why was this line changed?

2022-06-08 05:38 UTC, HarelM commented on src/style-spec/util/padding.ts
> +            input = [input];
Shouldn't this return an array of 4 identical numbers so that padding will always be an array of 4 values?

2022-06-08 05:42 UTC, HarelM requested changes
See my comments.
Overall looks very good!!
I think more tests are needed in the files you added the padding definition, parsing, serialization etc...

2022-06-08 13:48 UTC, drwestco commented on src/style-spec/expression/definitions/coercion.ts
> +            throw new RuntimeError(`Could not parse padding from value '${typeof input === 'string' ? input : String(JSON.stringify(input))}'`);
Copied from the Color code on line 86. Don't think it's needed there either.

2022-06-08 13:57 UTC, drwestco commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
I couldn't figure out what causes `Literal.serialize` to be called, and whether any code later deserializes the output. This was the only code I could find that takes `rgba` and turns it back into `Color`, not sure if this handles output of `Literal.serialize`, handles documented `Color` expressions (https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#color) or both.

When adding `Padding`, I searched the codebase how and where `Color` was used. So I added a `Padding` entry to `Literal.serialize` (not sure I needed to), but haven't found the place to parse the serialized padding.

2022-06-08 13:59 UTC, drwestco commented on src/style-spec/util/padding.ts
> +            input = [input];
Good point. I can directly return a Padding with 4 values here, since I know all the other checks will pass.

2022-06-08 14:20 UTC, HarelM commented on src/style-spec/expression/definitions/coercion.ts
> +            throw new RuntimeError(`Could not parse padding from value '${typeof input === 'string' ? input : String(JSON.stringify(input))}'`);
Please remove both then...

2022-06-09 18:29 UTC, drwestco commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
I've tried using various expressions on `icon-property`, `literal`, `interpolate`, etc., and can't figure out how to get `Literal.serialize` to ever be called. I added a `'padding'` entry here for symmetry, but this might all be dead code?

2022-06-10 10:05 UTC, xabbu42 commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
I also have an open question in https://github.com/maplibre/maplibre-gl-js/pull/645 about serialize. Do you know if all serialize methods are unused or only Literal.serialize? We should find out what the purpose of this methods is and document it somewhere.

2022-06-20 10:32 UTC, HarelM commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
I think this question is the only remaining blocker for merge. Unfortunately, I don't have a way to shed some light on this...

2022-06-20 18:38 UTC, drwestco commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
I don't think it should block the merge. I've updated the code to be consistent with Color WRT serialization/deserialization, so if this code path is active, the new icon-padding property will work. Determining whether this path is dead and can be cleaned up can be tackled as a separate issue.

I did see that `style.serialize()` is called when diffing the style as a result of calling `map.setStyle()`. The raw values of properties + expressions get serialized, not the parsed objects.

2022-06-20 20:02 UTC, drwestco commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
Web worker transfer will call a static `serialize` method on registered types, if it exists. It doesn't call any `serialize` instance methods, though. Running out of ideas how `Expression.prototype.serialize` could ever be called...

2022-06-20 20:26 UTC, drwestco commented on src/style-spec/expression/definitions/index.ts
> +    // REVIEW: Need an entry for 'padding' here, to consume values produced by Literal.serialize?
Follow-up issue #1312 added.

2022-06-21 19:24 UTC, HarelM commented on debug/setstyle.html
> +<script src='/debug/dark-demotiles.js'></script>
Shouldn't this be part of a different PR?

2022-06-21 20:51 UTC, HarelM commented on debug/setstyle.html
> +<script src='/debug/dark-demotiles.js'></script>
It would be better I believe. Although I think a lot more debug pages like this one are broken...

2022-06-22 17:34 UTC, HarelM commented on src/style-spec/expression/index.ts
> +        if (specification.type === 'color' && typeof value === 'string') {
I didn't get a answer for that... :-/

2022-06-22 18:11 UTC, HarelM commented on src/style-spec/expression/index.ts
> +        if (specification.type === 'color' && typeof value === 'string') {
Ok, cool, thanks.

2022-06-22 18:18 UTC, drwestco commented on src/symbol/collision_feature.ts
> +            let y1 = shaped.top * boxScale - padding[0];
I added unit tests for the `Padding` class, and render tests to verify asymmetric padding is honored on icons. Should I also update `collision_feature.test` to verify padding is respected on the generated bounding boxes?

2022-06-22 18:20 UTC, HarelM commented on src/symbol/collision_feature.ts
> +            let y1 = shaped.top * boxScale - padding[0];
I believe so, yes.

2022-06-22 20:11 UTC, drwestco commented on src/style-spec/expression/definitions/literal.ts
> +import {isValue, typeOf, Color, Padding} from '../values';
Correct.

2022-06-23 05:13 UTC, HarelM approved these changes
Thanks for all the effort!

2022-07-13 17:09 UTC, drwestco commented
Yes. The serialization code was removed in PR #1315

2022-07-13 19:47 UTC, HarelM commented on src/style-spec/util/interpolate.ts
> +    const fromVal = from.values;
Nit picking: I don't think these two variables `fromVal` and `toVal` are helping in any way - not from readability and not from shortening the code so I think they are redundant...

2022-07-13 19:48 UTC, HarelM commented on src/style-spec/util/padding.ts
> +    toArray(): [number, number, number, number] {
Is this function really needed? `values` property is public anyway...

2022-07-13 19:50 UTC, HarelM commented on src/style-spec/validate/validate_padding.ts
> +export default function validatePadding(options) {
Would be nice to have this function also covered with the relevant tests.

2022-07-13 19:51 UTC, HarelM commented on src/style/style_layer/symbol_style_layer.ts
> +    // Support text-padding in addition to icon-padding? Unclear how to apply asymmetric text-padding to the radius for collision circles.
Not sure I know what to do with this comment - is this a TODO?

2022-07-13 19:54 UTC, HarelM commented
Last few nit picking I stumbled upon before this can be merged. Sorry for all the back-and-forth...

2022-07-13 20:05 UTC, drwestco commented on src/style-spec/util/interpolate.ts
> +    const fromVal = from.values;
Personal preference, I guess. If I refer to a property more than twice, I tend to stick it in a local var so the minifier can chew on it.

2022-07-13 20:13 UTC, drwestco commented on src/style-spec/util/padding.ts
> +    toArray(): [number, number, number, number] {
I was following the design of the Color class. I'll see if this is actually used anywhere.

2022-07-13 22:12 UTC, drwestco commented on src/style-spec/util/padding.ts
> +    toArray(): [number, number, number, number] {
Color.toArray was used by serialization and Color.toString; Padding.toArray is unused and can be removed.

2022-07-13 22:59 UTC, drwestco commented on src/style/style_layer/symbol_style_layer.ts
> +    // Support text-padding in addition to icon-padding? Unclear how to apply asymmetric text-padding to the radius for collision circles.
Yes. Not sure there's a use case for extending text-padding like I did icon-padding. I can remove the comment and open an issue if that makes more sense.

2022-07-14 04:28 UTC, HarelM commented on src/style/style_layer/symbol_style_layer.ts
> +    // Support text-padding in addition to icon-padding? Unclear how to apply asymmetric text-padding to the radius for collision circles.
Yup, I think an issue would be better...

2022-07-14 11:58 UTC, HarelM approved these changes

2022-07-14 11:59 UTC, merged

2022-07-14 12:03 UTC, HarelM commented
Thanks a lot for bearing with all my annoying comments! :-)