Passing tile-data to Custom layer
maplibre/maplibre-gl-js pull request #1309
Opened 2022-06-17 14:53 UTC by Kanahiro

close #1305 (the concept is detailed in)

If codes are ok, I'll add some update to documents.

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-06-19 06:28 UTC, HarelM requested changes
See my comments, also please add some sort of unit test, not just render test...

2022-06-19 06:28 UTC, HarelM commented on test/integration/render/custom_layer_implementations.ts
> +import maplibregl from '../../../src/index';
Please import something more specific, importing all the namespace here doesn't look right.

2022-06-19 06:28 UTC, HarelM commented on test/integration/render/render.test.ts
> +    } else if (operation[0] === 'addCustomLayerWithWait') {
Is there a design alternative to this? I would like to avoid complicating the render test more with more operations...

2022-06-19 06:31 UTC, HarelM commented on test/integration/render/tests/custom-layer-js/tile-source/style.json
> +            "operations": [["addCustomLayerWithWait", "tile-source"]]
If I understand correctly, which I probably don't, this `tile-source` is not a "simple" one, but rather something that creates a triangular image, right?
If this is the case, I think it should have a better name, something like `rectangular-image-with-tiles` or anything else that will help someone understand what this class does by its name.

2022-06-20 09:43 UTC, Kanahiro commented on test/integration/render/render.test.ts
> +    } else if (operation[0] === 'addCustomLayerWithWait') {
Changed to use 'addCustomLayer' already exists and to run wait() in this operation.

2022-06-20 10:21 UTC, HarelM commented on src/style/style_layer.test.ts
> +describe('StyleLayer-CustomLayer', () => {
I don't think we need an extra `describe`s here. I think the main one is enough and the test name should be in the test.

2022-06-20 10:24 UTC, HarelM commented
I think `draw_custom.ts` might need a unit test as I think there is where the major changes were made, don't you think.
Otherwise looks good.
Thanks for all the time an effort put into this!

2022-06-20 11:05 UTC, Kanahiro commented
Thanks good suggestion. I've added unittest `draw_custom.test.ts`.

2022-06-20 11:42 UTC, HarelM approved these changes

2022-06-20 11:43 UTC, HarelM commented
One last thing, can you add a change log entry please?

2022-06-20 18:12 UTC, HarelM commented
@Kanahiro is this ready for review now?

2022-06-20 22:01 UTC, Kanahiro commented
Yes, finished!

2022-06-21 23:50 UTC, Kanahiro commented on src/style/style_layer/custom_style_layer.ts
> +import Tile from '../../source/tile';
Thanks for a comment. I didn't realized this.
Is it enough to remove @private mark or needed anything to do than it?
IMHO it is enough and should be because `Tile` class is exported as default.
If more details are needed for developers it may be good to append description in https://github.com/maplibre/maplibre-gl-js-docs .

2022-06-22 00:04 UTC, drwestco commented on src/style/style_layer/custom_style_layer.ts
> +import Tile from '../../source/tile';
The problem is all those properties on Tile are public, and who knows what happens when 3rd parties start messing with them. e.g., what's the difference between `Tile.texture` and `Tile.textures`?

2022-06-22 05:06 UTC, HarelM commented on src/style/style_layer/custom_style_layer.ts
> +import Tile from '../../source/tile';
I guess the same like custom layer, if you change them you take the risk...

2022-06-22 15:11 UTC, drwestco requested changes

2022-06-22 17:31 UTC, HarelM commented
@drwestco has good points in his comments, I agree with them.

2022-06-25 08:22 UTC, Kanahiro commented on src/render/draw_custom.ts
> +
I think it is good to treat this as opt-in paramater and in fact this process is invoked only when custom-layer has `source` property.

2022-06-25 08:31 UTC, wipfli commented on src/render/draw_custom.ts
> +
Since we are talking already about performance, would you mind to run the benchmarks on this pull request, @Kanahiro?

2022-06-25 08:37 UTC, Kanahiro commented on src/style/style_layer/custom_style_layer.ts
> +import Tile from '../../source/tile';
It is fact almost all of that props are not understandable for me and needed for 3rd party developer... Only tileIndex and texture are useful for a custom-layer developer (when raster-tile).

You mean to make a interface to expose tile-data safely like this, right?

```typescript
// each props are extracted `Tile`
type RasterTileData = {
  tileId: number[], // tile-index x,y,z
  texture: WebGLTexture
}

render(gl, matrix, tiles: RasterTileData[])
```

2022-06-25 13:09 UTC, Kanahiro commented on src/render/draw_custom.ts
> +
As far as I checked, it seems that a benchmark to test custom-layer doesn't exist so it have to be written. right?
It may need to be commited into `main` before this PR...

2022-06-25 13:12 UTC, wipfli commented on src/render/draw_custom.ts
> +
I don't know if there is a benchmark for custom-layer, but if there is none, it would be great if you could add one in a separate pull request.

2023-06-27 19:37 UTC, HarelM commented
@Kanahiro what's the status of this PR? Will you push it forward or close it?

2023-06-27 19:41 UTC, Kanahiro commented
@HarelM Sorr? I've lost this, I'll close this and open again when cleared some points.

2023-06-27 19:41 UTC, closed without merging

2024-04-16 17:25 UTC, lowriech commented
Did further implementation come out of this?  I'm interested in using it for custom terrain meshes.

2024-04-16 17:26 UTC, HarelM commented
Nope...