Add bench custom layer
maplibre/maplibre-gl-js pull request #1322
Opened 2022-06-25 13:31 UTC by Kanahiro

Added benchmark test for CustomLayer. related #1309 

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.

2022-07-12 08:59 UTC, wipfli commented
Thanks for contributing this benchmark, @Kanahiro. I can run the benchmark locally. I am just curious how the tents actually look like. Would you mind adding a debug page which shows what this custom layer does?

2022-07-19 20:18 UTC, Kanahiro commented
Hi @wipfli , thank you for reviewing.
The custom layer I added to bench is same to debug-pages's one.
https://github.com/maplibre/maplibre-gl-js/blob/main/test/debug-pages/custom3d.html

2022-07-21 20:15 UTC, wipfli commented on test/bench/benchmarks/customlayer.ts
> +    }
Here we are benchmarking how long it takes to create a map, add the custom layer and render it. I think it would be better if the createMap call was in setup() and then you would only have add custom layer and render in the benchmark function. This would be a bit like in https://github.com/maplibre/maplibre-gl-js/blob/main/test/bench/benchmarks/paint.ts

2022-07-21 20:16 UTC, wipfli requested changes
Thanks for the clarification about the debug page. Please move the createMap call to the setup function.

2022-08-06 02:28 UTC, Kanahiro commented
@wipfli 
Sorry for late response, I've fixed it.

2022-08-07 09:49 UTC, wipfli commented
Thanks for this, @Kanahiro. On my laptop, the benchmark runs in 20 microseconds. I wonder if this is too short for a benchmark? Maybe we should have more samples? I really don't know... What do you think? The other benchmarks seem to take longer...

![image](https://user-images.githubusercontent.com/53421382/183285180-195773fa-dd6f-46ff-afd5-80cd4083ae2b.png)

2022-08-07 11:41 UTC, Kanahiro commented
Your result is almost same to my machine.
I'm not sure but the cost to render custom-layer in current bench code may probably be too cheap...
Should we write custom-layer with 3d-model which has many vertex for benchmark?

2022-08-07 15:12 UTC, wipfli commented
Yes, that sounds like a good idea!

2022-09-08 18:13 UTC, HarelM commented
@wipfli @Kanahiro where are we with this PR? What's currently missing in order to merge this?

2022-09-08 18:30 UTC, wipfli commented
This benchmark runs much faster than the others I think. Should we target a similar overall duration for benchmarks such that they have similar complexity? Or is it not an issue if one benchmark is very fast? I am just a bit worried that we don't get meaningful results if the duration of a benchmark is too small compared to the precision of the time measurement...

2022-09-08 18:40 UTC, HarelM commented
Are we talking about the overall time or a single iteration? Because we can increase overall time by doing more iterations...

2022-09-08 18:52 UTC, wipfli commented
More iterations would be good I think. A single iteration is very fast if I remember correctly.

2022-09-13 13:42 UTC, xabbu42 commented
The benchmark code already runs a benchmark for a minimum amount of time, which means that this benchmark is run for 4500-5000 iterations according to the screenshot. We already have faster benchmarks like FunctionEvaluate which runs for over 16000 iterations on my machine. I think increasing the minimum time is a separate issue to this benchmark and should not be a blocker.

Also if you just make the custom layer itself more expensive, don't you just hide potential slowdowns in  the maplibre-gl-js code which we want to actually benchmark here? In my mind the the code specific to the benchmark itself should be as minimal and fast as possible in order to clearly show the speed of the benchmarked code in maplibre-gl-js.

2022-09-14 11:06 UTC, wipfli commented
I think you are right @xabbu42

2022-09-27 02:05 UTC, Kanahiro commented
Sorry late response.
With above discussion I understand it is ok to keep the bench tiny.
I resolved conflicts and ready to merge now.

2022-09-29 17:35 UTC, HarelM commented
@wipfli @xabbu42 any objections to merge this?

2022-09-29 17:56 UTC, wipfli commented
Good to merge from my side. Thanks @Kanahiro

2022-09-29 19:18 UTC, HarelM approved these changes

2022-09-29 19:18 UTC, merged