sort icons and text together so icons can overlap text
maplibre/maplibre-gl-js pull request #145
Opened 2021-04-27 14:17 UTC by xabbu42

This is a port of my pull request to mabox-gl-js: https://github.com/mapbox/mapbox-gl-js/pull/10123

This pull request attempts to fix issue https://github.com/mapbox/mapbox-gl-js/issues/10002 by sorting the icon and the text part of a symbol together instead of one after the other. I'm not sure if this is just a bug fix or a change in the style spec. I'm also not sure if this needs a port to maplibre-gl-native.

Keep in mind when reviewing this pull request that beside of javascript itself I'm not at all familiar
with any of the tech used (i.e. nodejs, webgl, flow etc).

## Launch Checklist

 - [x] confirm your changes do not include backports from Mapbox projects (unless with compliant license)
 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

2021-04-27 14:18 UTC, xabbu42 commented
I'll try to look at tests and benchmarks for maplibre-gl-js later.

2021-05-03 12:45 UTC, xabbu42 commented
All tests pass. I can't give meaningful benchmark results because of #76.

2021-05-03 12:55 UTC, xabbu42 commented
![Screenshot 2020-11-30 at 18 42 59](https://user-images.githubusercontent.com/98500/100644806-13500e00-333c-11eb-9483-90c236f4e363.png)
![Screenshot 2020-11-30 at 18 43 29](https://user-images.githubusercontent.com/98500/100644814-164afe80-333c-11eb-9f0f-6744e8e642c8.png)

This two screenshots show the visual difference for two overlapping symbols. The first is from main and the text of both symbols are visible despite the overlap. The second shows the fix where the icon of the overlapping symbol is drawn over the text.

2021-07-05 13:53 UTC, HarelM commented
I would love to fully review this, but I'm having a hard time understanding all the changes you made.
Can you please add some jsDocs above every method you changed describing what it does - input and output parameters so I can better understand what I'm seeing...?

2021-07-05 13:54 UTC, HarelM commented
Also adding a test or more would be great to make sure this is working as expected.

2021-07-05 17:29 UTC, xabbu42 commented
I will look into adding documentation and tests later this week. For now the following remarks may be helpful:

- its better to look at the diff ignoring whitespace
- essentially the old code had one function drawLayerSymbols which was called two times, once for the icon-* part and once for the text-* part. this had the side-effect of writing texts over all icons in the layer independent of sort-order.
- the new code only calls drawLayerSymbols once, and the single call handles the icon-* part and the text-* part together. the code which is the same for both is now in symbolState and is the equivalent of the code calculating the state variable in the old drawLayerSymbols function.

2021-07-06 05:22 UTC, HarelM commented on src/render/draw_symbol.js
> +function symbolsState(painter, coord, tile, bucket, layer, isText) {
Maybe `getSymbolState` instead?

2021-07-06 05:22 UTC, HarelM commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
I think this ifs parts can be simplified and made more readable.
`state` can be moved up outside the ifs parts reducing some of the duplication I think...
Please look into it.

2021-07-06 05:23 UTC, HarelM requested changes
See my comments.
Also as discussed, tests and some jsdocs.
Thanks!!

2021-07-06 09:40 UTC, xabbu42 commented on src/render/draw_symbol.js
> +function symbolsState(painter, coord, tile, bucket, layer, isText) {
done

2021-07-06 09:45 UTC, xabbu42 commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
No, the calls to symbolsState are not the same. The last argument is a boolean indicating if we want the state for the icon-* part or the text-* part.

2021-07-06 11:15 UTC, HarelM commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
but you have this value in a variable - `isText` and `isIcon`...?

2021-07-06 11:16 UTC, HarelM commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
Oh, wait, it can be that `hasText` and `hasIcon` be true, right?

2021-07-06 11:19 UTC, HarelM commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
What I'm saying is that the following code is duplicated almost completely:
```js
                const state = getSymbolsState(painter, coord, tile, bucket, layer, false); // or true
                const oldSegments = bucket.icon.segments.get();
                for (const segment of oldSegments) {
                    tileRenderState.push({
                        segments: new SegmentVector([segment]),
                        sortKey: ((segment.sortKey: any): number),
                        state
                    });
                }
```

2021-07-06 11:21 UTC, HarelM commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
I might be wrong... but I get the feeling this can be simplified and maybe reduce some of the code, I might be wrong...

2021-07-06 13:13 UTC, xabbu42 commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
You're right, I refactored that part.

2021-07-06 13:14 UTC, xabbu42 commented on src/render/draw_symbol.js
> +                    tileRenderState.push({
and yes, hasText and hasIcon can both be true for symbol layers with text-* and icon-* part.

2021-07-06 14:25 UTC, HarelM approved these changes

2021-07-06 14:26 UTC, HarelM commented
Missing tests and docs. :-)
The code looks good to me.

2021-07-06 20:27 UTC, HarelM requested changes
Sorry, mean to request tests and method documentation here instead of the conversation. My bad...

2021-07-08 07:24 UTC, xabbu42 commented
I just noticed that I move all the accesses to layer properties into the innermost loop (i.e. make them per symbol instead of per layer). That probably is a bad idea and I will fix that. But solving #76 would be really useful to catch things like that.

2021-07-08 07:40 UTC, HarelM commented
I agree. Also writing tests up front would help in these exact refactoring situations :-)

2021-07-10 10:28 UTC, xabbu42 commented
I will look into tests :-) but this specific case could only be catched by benchmarks. This is also why I decided to concentrate on getting the benchmarks to run first a I don't know the bigger picture enough to be confident that I did not introduce any performance regressions in this PR.

2021-07-10 10:31 UTC, HarelM commented
I agree about the focus on benchmarks, but a unit test here to make sure everything is drawn is a good fit here, I think...

2021-07-15 16:27 UTC, xabbu42 commented
I will be away for the next 3 weeks but plan to take this up again after that. If anyone wants to take over in the meantime, you're very welcome.

2021-09-03 06:51 UTC, HarelM commented
I've just merged the typescript branch into main so this creates a conflict in your file.
Can you please adjust as needed?
Also please add a note in the change log so I'll be able to merge.
Adding a test and migrating the code to typescript are the last steps. Sorry for the inconvenience.

2021-11-03 10:19 UTC, xabbu42 commented
I will get around to finish this pull request eventually.

2022-01-08 11:20 UTC, wipfli commented
This is related to #347, right?

2022-01-08 11:47 UTC, xabbu42 commented
No this is not related. #347 is about the available settings in the style to determine if two symbols are allowed to overlap or not. This is about how to draw two overlapping symbols.

P.S. I'll plan to take this pull request up again as soon as I'm comfortable with the benchmarks.

2022-01-26 19:11 UTC, HarelM commented
@drwestco any chance you could help with this as well? You did a great job at #347 and this is very similar in both tests and code.
It will be great if we can ship a version with both features...

2022-02-11 12:58 UTC, HarelM commented
@xabbu42 I tried to take the latest code from this PR and run the render tests (which we didn't have at the time of writing this PR).
There's a specific test there that should fail in case this code changes and basically facilitate for the test part of this PR, but it seems that there's something that is not working correctly in the code I copied as the following image stays the same:
![expected](https://user-images.githubusercontent.com/3269297/153595082-6d310065-80d7-47b6-ab22-7c0bd303538f.png)
`test/integration/render/tests/icon-opacity/text-and-icon`
to run this test in cmd:
`npm run test-render -- tests/icon-opacity/text-and-icon`
Any help would be appreciated.
I can create a branch in this repo to facilitate the ability to work together on this, let me know how I can help push this forward.

2022-02-11 19:18 UTC, HarelM commented
I've created PR #985 to replace this PR, but I'm not 100% sure the code is correct... :-(

2022-02-12 12:28 UTC, closed without merging