Added missing style-spec typings to publish
maplibre/maplibre-gl-js pull request #1470
Opened 2022-08-12 19:02 UTC by HarelM

## Launch Checklist

Related to #1107 #1116 #1468
This basically adds the missing step in the publish CI script which I assumed happens automatically but apparently it was a wrong assumption as the only thing that runs in the post install is the code generation that is needed in order to build the package but the type generation is not part of it.
My bad :-(

2022-08-12 19:22 UTC, wipfli requested changes
Ah thanks @HarelM for fixing this! Please update the lockfile

2022-08-12 19:22 UTC, wipfli commented on src/style-spec/package.json
> +  "version": "17.0.1",
Run npm install to update the lock file

2022-08-12 19:23 UTC, wipfli commented on src/style-spec/CHANGELOG.md
> +* Generated typings file as not created in the build process and was added in this version
```suggestion
* Generated typings file as not created in the build process and was added in this version [#1470](https://github.com/maplibre/maplibre-gl-js/pull/1470)
```

2022-08-13 04:17 UTC, HarelM commented on src/style-spec/package.json
> +  "version": "17.0.1",
There's no lock file for this package...

2022-08-13 05:03 UTC, wipfli commented on src/style-spec/package.json
> +  "version": "17.0.1",
Ah ok

2022-08-13 05:03 UTC, wipfli approved these changes

2022-08-13 05:04 UTC, merged