Adding a benchmark to measure time from map start to idle.
maplibre/maplibre-gl-js pull request #1544
Opened 2022-08-23 20:39 UTC by kircher1

I'm working on a different change to bring some potential speedup to the map's "loading" time.

I wasn't able to find a benchmark that measures this sort of metric, so this PR adds a `MapIdle` benchmark which measures the time from map construction to when it reaches the idle state. The benchmark pre-warms network caches during the setup phase i.e., it's not a cold, clear-cache test.

A new field is also added to the Benchmark base class that allows setting a different number of minimum iterations, as the default of 210 iterations is simply too many for this relatively longer running sort of benchmark.

FWIW, my machine is averaging ~680ms for this measurement, so it takes ~30s to run the benchmark on a given branch. Mileage will vary based on the machine.

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-08-23 21:27 UTC, kircher1 commented
The `HillshadeLoad` benchmark is similar in that it measures to the Idle event, but very different in that it only loads hill shade tiles. I added some class comments to that, and the related `MapLoad` benchmark. Please check for accuracy.

2022-08-24 04:08 UTC, HarelM commented
How would this work of I want to compare this to an older version? Is this test gets ignored?

2022-08-24 04:40 UTC, kircher1 commented
When I run a new benchmark locally, it appears to gracefully handle the fact that there is no corresponding test on the latest main or release build. So, we only get results for the current branch e.g.,

![image](https://user-images.githubusercontent.com/20366429/186329215-244e6a41-dd34-4769-8ccb-b4634b9091a8.png)

Rather than all 3 branches (like from the existing `Load` benchmark)

![image](https://user-images.githubusercontent.com/20366429/186329356-f068073a-2ef8-4933-8616-b76918fc00f8.png)

So once this benchmark gets committed/released, I assume the other branch results will light up. I think? Logic for grabbing the version of the benchmark js from main/etc is here: https://github.com/maplibre/maplibre-gl-js/blob/8ff0907681a441d04601c29716b56751a980c593/test/bench/versions/index.html#L18

2022-08-24 12:08 UTC, HarelM commented
Overall looks good to me.
@wipfli @xabbu42

2022-08-27 10:14 UTC, xabbu42 commented
While the web interface handled missing benchmark results gracefully, the command line script didn't. I pushed a fix directly to this pull request, I hope thats ok.

2022-08-27 11:49 UTC, xabbu42 requested changes
Some small corrections.

2022-08-27 11:49 UTC, xabbu42 commented on test/bench/lib/benchmark.ts
> -        return this._elapsed >= 500 && this._measurements.length > 210;
Please move the comment with the explanation to the new place of the constant.

2022-08-27 11:49 UTC, xabbu42 commented on test/bench/versions/benchmarks.ts
> +import Idle from '../benchmarks/map_idle';
Idle and Load are the only two benchmarks which to not follow the naming scheme of all the others. Perhaps it would be better to use MapIdle as name. I don't know...

Unfortunately we probably can't rename Load to MapLoad though.

2022-08-27 11:49 UTC, xabbu42 commented on test/bench/versions/benchmarks.ts
> +register('Idle', new Idle());
Same comment as above. Maybe its better to name it MapIdle?

2022-08-27 11:49 UTC, xabbu42 commented on test/bench/benchmarks/map_idle.ts
> +        this.minimumMeasurements = 40;
If I understand the comment for the original constant and the code of the regression function in statistics.ts correctly, this should be a sum of the first n integers, i.e. 55 to give 10 observations instead of the default of 210 for 20 observations.

2022-08-29 17:17 UTC, kircher1 commented on test/bench/versions/benchmarks.ts
> +import Idle from '../benchmarks/map_idle';
Yeah, I see your point. The naming is a little too vague. `Layout`/`Paint` are also a bit broad. They could be prefixed with Map too, and `HillShadeLoad` should have been named `HillShadeIdle`, but I think changing any of these will break the comparisons. I'll update to `MapIdle` though.

2022-08-29 17:50 UTC, kircher1 commented on test/bench/benchmarks/map_idle.ts
> +        this.minimumMeasurements = 40;
I bumped the number of measurements up to 55 and added a similar comment about the statistical regression.

2022-08-29 20:13 UTC, xabbu42 approved these changes
Everything good from my side. Thanks for the contribution!

2022-08-29 21:12 UTC, HarelM commented
Yea, something wrong with the coverage report, not sure why or what. I'll look into it.

2022-08-30 11:58 UTC, HarelM commented
Seems like the coverage fails on PRs that origin from a fork (which is most PRs) :-(

2022-08-30 11:59 UTC, HarelM commented
Since this doesn't change any production code this can be merged.
I'll see what I can do about this unit test pipeline...

2022-08-30 12:24 UTC, HarelM commented
@kircher1 can you merge from main so that I'd know everything is passing as expected?
I solved #1581 which should fix the issue here...

2022-08-30 15:54 UTC, kircher1 commented
Thanks for taking a look @HarelM. Synced with main just now.

2022-08-30 18:02 UTC, merged