Basic sky implementation
maplibre/maplibre-gl-js pull request #1713
Opened 2022-10-07 08:42 UTC by prozessor13

Based on BAschl's [work](https://github.com/BAschl/maplibre-gl-js/commit/c7883390c23dbb04cc224980431fe68249844a82) i created a simple Sky implementation.

Sky can be setted via stylesheet or via `map.setSky` method. Currently the following prameters are supported:
* sky-color
* fog-color
* horizon-blend

I thougt further about fog, and my conclusio for a simple implementation would be:
* allow fog only in terrain-3d maps, because for fog the depth-buffer is needed, and this only exists in 3d.
* add a setting (to terrain or sky, i dont know) `fog-blend` with a value from `0` to `1` which defines where the fog starts. 0 is the map-center, 1 is the far-clipping-plane.
* Pitch value also would effect the fog intensity. I think a constant would be sufficent.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Write tests for all new functionality.
 - [x] Document any changes to public APIs.
 - [x] Manually test the debug page.
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-10-07 11:19 UTC, HarelM commented
Can you share some visuals of how this would look?

2022-10-07 11:59 UTC, prozessor13 commented
also played with fog.
![fog](https://user-images.githubusercontent.com/45103/194547978-c213becc-1681-4378-8caa-1d3726308d51.png)

2022-10-09 12:03 UTC, prozessor13 commented
Implemented fog, which was really frustrating to understand the not linear z value of the depthbuffer. So created a separate fogMatrix which creates more useable z-values. As already sayed, fog only works in terrain, and i will not port this to 2d. This is because, for me, the benefit is very very low, and it is a lot of work. Every single shader has to be extended with the fog logic.

2022-10-09 12:05 UTC, prozessor13 commented
Fog with default-values:
![fog-osm](https://user-images.githubusercontent.com/45103/194755878-31b5333c-8709-4478-9aec-5d92e0056c83.png)

2022-10-09 13:28 UTC, wipfli commented
Looks nice...

2022-12-02 06:41 UTC, prozessor13 commented on src/shaders/terrain_depth.fragment.glsl
> +    highp vec4 comp = fract((value * 0.5 + 0.5) * bitSh);
I think the [0, 1.0] range is a left over from the implementation without the fog_matrix. So i think it can be reverted??

2022-12-02 06:43 UTC, prozessor13 commented on src/style/sky.ts
> +        if (pitch < 70) return (pitch - 60) / 10; // fade in
That's right. The numbers are evaluated by trial/error. And its working ok-ish.

2022-12-02 06:49 UTC, prozessor13 commented on src/style/sky.ts
> +        this.segments = SegmentVector.simpleSegment(0, 0, vertexArray.length, indexArray.length);
After a very quick lookup i did not find such a vertex-buffer ([-1, 1] extent). Every draw call is based on tiles, even the background-layer.

2022-12-02 06:54 UTC, prozessor13 commented on src/shaders/sky.vertex.glsl
> +    gl_Position = vec4(a_pos, 0.99999, 1.0);
This value is from https://github.com/BAschl/maplibre-gl-js/blob/c7883390c23dbb04cc224980431fe68249844a82/src/shaders/sky.vertex.glsl#L12 . In this implementation you need the z-index because sky currently is drawn at the final step. But this should changed in any case, so that the sky will be drawn first. Otherwise/currently symbol-layers are overwritten by the sky.

2022-12-02 06:58 UTC, prozessor13 commented on src/shaders/terrain.fragment.glsl
> +        gl_FragColor = mix(color, u_fog_color, pow(a * u_fog_blend_opacity, 2.0));
That's definitely a great example, but because of the lack of any experience in sky/fog and time i kept it simple.

2022-12-02 07:01 UTC, prozessor13 commented on src/shaders/sky.fragment.glsl
> +            gl_FragColor = mix(u_sky_color, u_fog_color, pow(1.0 - blend / u_horizon_blend, 2.0));
BAchl had implemented a gradient, mapbox in the current [setFog](https://docs.mapbox.com/mapbox-gl-js/style-spec/fog/#color) method dont. So to reduce complexibility i removed this feature.

2022-12-02 07:05 UTC, prozessor13 commented
@JannikGM thanks for you review! But i have to say, that currently i do no longer have resources to work on maplibre. May in the next weeks i have time to:
* remove the [0, 1] extent in depth-buffer
* draw sky at the very beginning, and remove the 0.99999 hack in z-direction.

Regards. Max.

2022-12-02 09:49 UTC, prozessor13 commented on src/style/sky.ts
> +        if (pitch < 70) return (pitch - 60) / 10; // fade in
Yep, will do that as well.

2022-12-02 09:52 UTC, prozessor13 commented on src/style/sky.ts
> +        this.segments = SegmentVector.simpleSegment(0, 0, vertexArray.length, indexArray.length);
Ah, heatmap. right! I basically agree with you, but to reuse this code some refacturing has to be done. If someone is willed doing it, a separate PR would be better i think.

2022-12-02 09:57 UTC, prozessor13 commented on src/shaders/sky.vertex.glsl
> +    gl_Position = vec4(a_pos, 0.99999, 1.0);
I think it is better to fix this hack and put drawing Sky before drawing everything else. This is may a small performance drawback, but with the benefit that the symbols are drawn correct above the horizon.

Idealy the sky, the symbols and the far-clipping-plane has their defined positions in z-direction (depthbuffer), but currently i dont think this is implemented (at least i do not know where). So, same here, if someone willed, then separate PR...

2022-12-02 10:09 UTC, prozessor13 commented on src/shaders/terrain_depth.fragment.glsl
> +    highp vec4 comp = fract((value * 0.5 + 0.5) * bitSh);
Thx, i will keep this in mind. Currently i have to re-dive into my own code to understand it in detail, completely lost all my thoughts when wrote it :D

2022-12-05 11:13 UTC, prozessor13 commented on src/style/sky.ts
> +        if (pitch < 70) return (pitch - 60) / 10; // fade in
appended documentation

2022-12-05 11:13 UTC, prozessor13 commented on src/style-spec/reference/v8.json
> +      "doc": "Tho map sky.",
fixed

2022-12-05 11:14 UTC, prozessor13 commented on src/shaders/sky.vertex.glsl
> +    gl_Position = vec4(a_pos, 0.99999, 1.0);
Setted to `1.0` and it worked as expected. Dont know why BAchl used `0.99999`. Additionally the sky is drawn before symbols, so symbol visibility is working correct now.

2022-12-10 14:22 UTC, klokan commented
This looks amazing - would be a great addition to 3.0 release.

2022-12-10 17:38 UTC, HarelM commented
This still needs to be well defined in terms of spec and properties, but 3.0 is not urgent and I believe we can wait with it until this is fully implemented.

2023-02-08 14:05 UTC, prozessor13 commented
From code-side i think this PR is complete, and i already implemented Jannik's comments. Furthermore this code is well tested in our company and already productive.
Would be grateful, if someone else will create tests.

2023-02-08 14:30 UTC, HarelM commented
Thanks for the update. I'll see what I can do, maybe we can talk about it in the TSC meeting today and see if anyone would like to push this forward.

2023-05-12 11:57 UTC, birkskyum commented
@wipfli , is the result of the code sprint to be found anywhere? is that work still ongoing, and by who?

2023-05-13 15:23 UTC, birkskyum commented
It's only render tests that can be done here, right?

2023-05-13 15:42 UTC, birkskyum requested changes
Had a look at this.

The SkySpecification has to become part of the [style spec repo](https://github.com/maplibre/maplibre-style-spec), before it can be implemented here.

2023-05-13 15:57 UTC, birkskyum commented
> This still needs to be well defined in terms of spec and properties, but 3.0 is not urgent and I believe we can wait with it until this is fully implemented.

If there is discussion around the definition, let's have it in this [Style Spec Design Proposal](https://github.com/maplibre/maplibre-style-spec/issues/163).

2023-05-15 05:36 UTC, ambientlight commented
> is the result of the code sprint to be found anywhere? is that work still ongoing, and by who?

@birkskyum: should be @jonathanlurie

2024-01-11 11:39 UTC, HarelM commented
@prozessor13 as discussed in the meeting, once you create a new PR, please close this one.
THANKS!!!

2024-01-30 08:58 UTC, closed without merging