Use resizeObserver instead of window resize events, fix and clean tests
maplibre/maplibre-gl-js pull request #2157
Opened 2023-02-09 22:02 UTC by HarelM

This adds the relevant unit test.
Cleans the other tests that has duplicate code in every before function.
Clear some test that did not need some methods.

@rotu Feel free to review :-)

Replaces #2013

2023-02-09 23:00 UTC, rotu commented on test/integration/render/mock_browser_for_node.ts
> +global.ResizeObserver = function (callback) {
This doesn't emulate a resize observer. In particular, in the real thing, there's no guarantee that callback is ever called (and especially not synchronously!).

If the idea is (as I think it is) not to mock anything but to prevent the program from crashing in unrelated tests, then it's worth a comment to that effect.

2023-02-09 23:01 UTC, HarelM commented
This is strange... Why would only a small part of the render test fail? Why are they affected from the resize mechanism change?

2023-02-09 23:03 UTC, HarelM commented on test/integration/render/mock_browser_for_node.ts
> +global.ResizeObserver = function (callback) {
Well... Not calling the callback causes some tests to fail. It might need a timeout in theory and maybe a different implantation, but generally speaking, it needs something.

2023-02-09 23:08 UTC, rotu commented on src/ui/map.ts
>          if (typeof window !== 'undefined') {
This might not be the PR to address it, but this line bugs me. If `window` is `undefined` then we should be failing very loudly, not silently ignoring it!

2023-02-09 23:11 UTC, rotu commented on src/ui/map.ts
>          if (typeof window !== 'undefined') {
It would also allow _resizeObserver to be definitely assigned, so later `this._resizeObserver?.disconnect()` could get rid of the `?`

2023-02-10 06:45 UTC, HarelM commented on test/integration/render/mock_browser_for_node.ts
> +global.ResizeObserver = function (callback) {
Looks like you were right...

2023-02-10 06:49 UTC, HarelM commented on src/ui/map.ts
>          if (typeof window !== 'undefined') {
I don't have hard feelings for this `if` in general. From my point of view, it can be removed completely.
In what scenario `window` is not defined?

2023-02-10 12:09 UTC, wipfli commented on src/ui/handler/mouse_handler_interface.test.ts
> -beforeEach(() => {
Did we add them here with no reason?

2023-02-10 12:10 UTC, wipfli commented on src/ui/handler/one_finger_touch_drag_handler_interface.test.ts
> -beforeEach(() => {
Did we add them here unnecessarily?

2023-02-10 12:15 UTC, wipfli commented on src/ui/map.test.ts
> +            let observerCb = null;
Can you add a type to observeCb? Rename to observeCallback

2023-02-10 12:16 UTC, wipfli commented on src/ui/map.test.ts
> +            let observerCb = null;
Or observerCallback...

2023-02-10 12:19 UTC, HarelM commented on src/ui/map.test.ts
> +            let observerCb = null;
I have taught you well, young padawan.

2023-02-10 12:19 UTC, HarelM commented on src/ui/handler/one_finger_touch_drag_handler_interface.test.ts
> -beforeEach(() => {
Yes.

2023-02-10 12:20 UTC, HarelM commented on src/ui/handler/mouse_handler_interface.test.ts
> -beforeEach(() => {
I believe they were there, but are not needed.

2023-02-10 12:21 UTC, HarelM commented on src/ui/map.test.ts
> +            let observerCb = null;
Done.

2023-02-10 12:26 UTC, wipfli commented on src/source/vector_tile_worker_source.test.ts
> -        originalGetEntriesByName = window.performance.getEntriesByName;
Do you remeber why we had the mark stuff?

2023-02-10 12:27 UTC, HarelM commented on test/integration/render/mock_browser_for_node.ts
> +} as any;
Sure.

2023-02-10 12:31 UTC, HarelM commented on src/source/vector_tile_worker_source.test.ts
> -        originalGetEntriesByName = window.performance.getEntriesByName;
I think I added a comment in a code review that this is needed in order to revert back to original state. but other tests don't do it, so there's no real value in keeping it. either we do it in all test or not. and since the tests are passing and not interfering to one another, there's no reason to keep it.

2023-02-10 12:34 UTC, wipfli commented on src/ui/map.ts
> +            this._resizeObserver = new ResizeObserver((entries) => {
What are the entries?

2023-02-10 12:40 UTC, wipfli requested changes
Looks good to me in general, thanks! I think since the behavior for resizing containers has changes, we should treat this as a breaking change with associated changelog remark. Please also add a test where you only resize the map container but not the window.

2023-02-10 12:46 UTC, HarelM commented on src/ui/map.ts
> +            this._resizeObserver = new ResizeObserver((entries) => {
This is the ResizerObserver API entries, I did not check what's in them.

2023-02-10 12:50 UTC, HarelM commented
The unit tests are covering the resize functionality without knowing if the window or the container were resized.
What did you have in mind in terms of testing?

2023-02-10 12:58 UTC, wipfli commented
Ah OK I thought the test simulate resizing of the window and then  check that our code gets called. But if the tests already resizing from container, we do not need more tests.

2023-02-10 12:59 UTC, wipfli approved these changes
Looking forward to use this new behavior. Thanks!

2023-02-10 13:30 UTC, HarelM commented
I added 2 browser tests, just in case...

2023-02-10 14:00 UTC, merged