WIP Typescript updates to gl-matrix
maplibre/maplibre-gl-js pull request #219
Opened 2021-07-22 16:59 UTC by chippieTV

## Launch Checklist

 - [x] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] briefly describe the changes in this PR

Some types seem to be Float32Array when it seems they should often be gl-matrix types and constructors.
Because we are in the middle of porting to Typescript it is hard to confirm that this doesn't break more than it fixes, however for my fork at the time of the MR the errors in tsx went from `615` down to `597`.

The PR is WIP, please comment and I'll do my best to fix.

 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

2021-07-23 05:29 UTC, HarelM requested changes
I think this is good, but I have a feeling some of the changes here are a bit risky currently.
I would say that I want everything working in terms of typescript and maplibre before introducing this change in order to know that this is not breaking anything.
Sorry if this is not what you have expected to read... :-(

2021-07-23 05:29 UTC, HarelM commented on src/geo/transform.ts
> +    customLayerMatrix(): mat4 { // Array<number> {
No need to keep the comment I believe...

2021-07-23 05:29 UTC, HarelM commented on src/render/uniform_binding.ts
> +const emptyMat4 = mat4.create();
This seems to be different if you said that `creates` is returning an identity matrix and not zeroed one...?

2021-07-23 05:29 UTC, HarelM commented on src/style/style_layer.ts
> +      pixelPosMatrix: mat4 // Float32Array
Same here with the comment.

2021-07-23 05:29 UTC, HarelM commented on src/style/style_layer/circle_style_layer.ts
> +                const projectedCenter = vec4.transformMat4(vec4.create(), [point.x, point.y, 0, 1], pixelPosMatrix);
We need to understand if this is a performance penalty here since we are not longer using `[]`... I don't have the answers though...

2021-07-23 05:29 UTC, HarelM commented on src/style/style_layer/circle_style_layer.ts
> +    const point = vec4.transformMat4(vec4.create(), [p.x, p.y, 0, 1], pixelPosMatrix);
Same here regarding performance.

2021-07-23 05:29 UTC, HarelM commented on src/style/style_layer/fill_extrusion_style_layer.ts
> +        const v: vec4 = [p.x, p.y, z, 1];
`vec4.fromValues(...)` ?

2021-07-23 05:29 UTC, HarelM commented on src/symbol/collision_index.ts
> +        const p = [x, y, 0, 1] as vec4;
`fromValues()`?

2021-07-23 05:29 UTC, HarelM commented on src/symbol/collision_index.ts
> +        const m = mat4.identity(mat4.create());
Wouldn't `create()` be enough here?

2021-07-23 07:28 UTC, chippieTV commented on src/render/uniform_binding.ts
> +const emptyMat4 = mat4.create();
yeh it's weird, I was surprised too.. but seems to be so
https://github.com/toji/gl-matrix/blob/master/src/mat4.js#L13

```javascript
/**
 * Creates a new identity mat4
 *
 * @returns {mat4} a new 4x4 matrix
 */
export function create() {
  let out = new glMatrix.ARRAY_TYPE(16);
  if (glMatrix.ARRAY_TYPE != Float32Array) {
    out[1] = 0;
    out[2] = 0;
    out[3] = 0;
    out[4] = 0;
    out[6] = 0;
    out[7] = 0;
    out[8] = 0;
    out[9] = 0;
    out[11] = 0;
    out[12] = 0;
    out[13] = 0;
    out[14] = 0;
  }
  out[0] = 1;
  out[5] = 1;
  out[10] = 1;
  out[15] = 1;
  return out;
}

// ...

/**
 * Set a mat4 to the identity matrix
 *
 * @param {mat4} out the receiving matrix
 * @returns {mat4} out
 */
export function identity(out) {
  out[0] = 1;
  out[1] = 0;
  out[2] = 0;
  out[3] = 0;
  out[4] = 0;
  out[5] = 1;
  out[6] = 0;
  out[7] = 0;
  out[8] = 0;
  out[9] = 0;
  out[10] = 1;
  out[11] = 0;
  out[12] = 0;
  out[13] = 0;
  out[14] = 0;
  out[15] = 1;
  return out;
}
```

2021-07-23 07:29 UTC, chippieTV commented on src/render/uniform_binding.ts
> +const emptyMat4 = mat4.create();
but yes you are right about that line being a bit shady, I should check if it needs zeroing out too..

2021-07-23 07:34 UTC, chippieTV commented on src/symbol/collision_index.ts
> +        const m = mat4.identity(mat4.create());
yeh sorry I did this in stages as I got to understand it and was going through when we said it'd be good to push so you can see it in progress. I agree some stuff contradicts other parts.. I'll fix!

2021-07-23 07:52 UTC, chippieTV commented on src/style/style_layer/circle_style_layer.ts
> +                const projectedCenter = vec4.transformMat4(vec4.create(), [point.x, point.y, 0, 1], pixelPosMatrix);
I guess first question is how often it runs and is the penalty if there is one, something to be concerned about. I know when we spoke yesterday I voiced this exact concern about it.

Skimming over the code in gl-matrix, it looks like it will use a `Float32Array` if the browser has it, and if it does not it will fall back to standard Array (i.e. prefers it). `create()` will assign the initial values to 0 if it's not `Float32Array` for 12 of the 16 elements of a `mat4` as `new Array(16)` returns undefined for all elements in the array, while the TypedArray is packed/aligned whichever.

It leads me to believe that actually it should be faster to create the TypedArray than an empty one which because it's of no fixed length, may need to be grown or can't be expected to know how long it should be or what is going into it.

That said, it seems of course it's more complex than that, and maybe the JS engine does something clever.. [this post about Array vs Typed arrays](https://www.alibabacloud.com/blog/exploration-and-practice-of-frontend-memory-optimization_597639) is super interesting and I think I will read through it again a bit more carefully later

2021-07-23 09:02 UTC, chippieTV commented on src/geo/transform.ts
> +    customLayerMatrix(): mat4 { // Array<number> {
fixed

2021-07-23 09:02 UTC, chippieTV commented on src/style/style_layer.ts
> +      pixelPosMatrix: mat4 // Float32Array
fixed

2021-07-23 09:03 UTC, chippieTV commented on src/style/style_layer/circle_style_layer.ts
> +    const point = vec4.transformMat4(vec4.create(), [p.x, p.y, 0, 1], pixelPosMatrix);
for performance, same as above.

also updated second arg to `transformMat4()` to `vec4.fromValues()`

2021-07-23 09:04 UTC, chippieTV commented on src/symbol/collision_index.ts
> +        const m = mat4.identity(mat4.create());
updated

2021-07-23 09:06 UTC, chippieTV commented
> I think this is good, but I have a feeling some of the changes here are a bit risky currently.
I would say that I want everything working in terms of typescript and maplibre before introducing this change in order to know that this is not breaking anything.
Sorry if this is not what you have expected to read... :-(

no problem. I'm more than happy for this stuff to sit and wait for there to be a way to test it properly, or merge and squash so we can revert at some point in the future if it turns out to be bad.

Is there any way we should title these PRs to keep them all together? like `TYPESCRIPT: issue description...` or tag perhaps? maybe there already is

2021-07-23 09:10 UTC, HarelM commented
Typescript prefix sounds good.

2021-07-23 09:12 UTC, chippieTV commented on src/render/uniform_binding.ts
> -    readonly set: (v: T) => void;
sorry this kinda crept in here. Removing this from `class Uniform<T>` stops the other extended classes complaining about their `set` methods.

There's maybe a better way, I'm not really so very familiar with current OOP TS Class type stuff, my day to day is more React where we basically avoid classes at all costs or refactor them out ASAP.

2021-07-26 01:35 UTC, chippieTV commented on src/render/uniform_binding.ts
> -    readonly set: (v: T) => void;
You fixed this in the latest with abstract instead which is better. I was looking for that but missed it

2021-07-26 08:21 UTC, HarelM commented on src/geo/transform.ts
> +        let m = mat4.create();
Can we use this the same as below? i.e. run the create inside the call and use the return value?

2021-07-26 08:23 UTC, HarelM commented on src/render/draw_symbol.ts
> +const identityMat4 = mat4.create();
We need to be absolutely sure that this creates an identity matrix and not an empty one in all possible cases...

2021-07-26 08:59 UTC, HarelM commented on src/symbol/collision_index.ts
> +        const m = mat4.create();
Same as above about readability.

2021-07-26 10:18 UTC, chippieTV commented on src/render/draw_symbol.ts
> +const identityMat4 = mat4.create();
'identity()' resets an existing mat4, 'create()' creates a new one with identity

https://github.com/maplibre/maplibre-gl-js/pull/219#discussion_r675359111

2021-07-26 10:21 UTC, chippieTV commented on src/geo/transform.ts
> +        let m = mat4.create();
'm' is used later in the function so we need access to it

2021-07-26 10:32 UTC, HarelM commented on src/symbol/projection.ts
> +        const symbol = placedSymbols.get(s);
I don't think this is relevant here...?

2021-07-26 10:33 UTC, chippieTV commented on src/render/draw_symbol.ts
> +const identityMat4 = mat4.create();
it's maybe minor but create() _should_ be faster too, well at least it's running a few less operations.. it appears to me the following:

- **new Float32Array(16)** will init a typed array of 16 fixed size elements each initialized to 0
- **identity()** will set all 16 elements of an array (typed or not) no matter what they contain

- **[]** will create a normal JS Array which is more flexible and slower as the elements are not aligned to the same set size (my understanding) allowing Array to hold any mixed kinds of elements.

- **create()** checks if it can create a Float32Array (browser support) and if so will jump to just initializing the Float32Array(16) and since it knows it will be all zeros, it only sets 4 1's on the diagonal

2021-07-26 10:34 UTC, HarelM commented on src/render/draw_symbol.ts
> +const identityMat4 = mat4.create();
Ahh, then never mind... Maybe a comment then?

2021-07-26 10:35 UTC, chippieTV commented on src/symbol/projection.ts
> +        const symbol = placedSymbols.get(s);
I think it crept in with other fixes, not gl-matrix related no

2021-07-26 10:35 UTC, HarelM commented
Ok, I reviewed all the code. I had minor corrections. Let's hope this won't create any performance issues...
Let's continue forward with merging this...

2021-07-26 10:42 UTC, chippieTV commented on src/symbol/projection.ts
> +        const symbol = placedSymbols.get(s);
remove from the PR?

2021-07-26 10:43 UTC, chippieTV commented on src/render/draw_symbol.ts
> +const identityMat4 = mat4.create();
I also moved it out of the imports which was a weird place for it to be honest

2021-07-26 10:55 UTC, chippieTV commented
sorry I force pushed because I want it to be easy to revert if it's wrong so it's a single commit. it might depend on the git workflow whether that's actually helpful or not.. what's better for you? I should check first

2021-07-26 11:18 UTC, HarelM commented on src/geo/transform.ts
> +        let m = mat4.create();
I mean something like let m = ... (mat.create(), ...

2021-07-26 11:22 UTC, HarelM commented on src/symbol/projection.ts
> +        const symbol = placedSymbols.get(s);
No, never mind...

2021-07-26 11:24 UTC, HarelM commented on src/geo/transform.ts
> +        let m = mat4.create();
Never mind, it's not important enough...

2021-07-26 11:24 UTC, HarelM approved these changes

2021-07-26 11:25 UTC, merged

2021-07-26 11:27 UTC, HarelM commented
I'm squashing the commit, so it doesn't really matter how the commit in the branch are... I think...