Add helpful guideline for contributors
maplibre/maplibre-gl-js pull request #2212
Opened 2023-02-20 20:51 UTC by ZeLonewolf

This PR updates the contributor's guide with recommendations interacting with the team, based on [Slack discussions](https://osmus.slack.com/archives/C01G3D28DAB/p1676846211248879).

2023-02-20 21:21 UTC, louwers commented
If these are to apply to multiple repositories, maybe maplibre/maplibre is a better place to add it.

With a link from the respective repositories.

2023-02-20 21:25 UTC, ZeLonewolf commented
Some of the instructions I added are specific to gl-js / npm, so it's not a perfect copy/paste.

2023-02-20 21:27 UTC, louwers commented
@ZeLonewolf Yes now I read it a bit more closely, we work with design proposals for significant changes as well for MapLibre GL Native.

2023-02-20 21:28 UTC, louwers commented on CONTRIBUTING.md
> +Maplibre welcomes contributions from community! This codebase is large and complex, and following these best practices will assist the maintainer team in reviewing your contribution. A good place to
I think GitHub Discussions are vastly suprior to Slack when it comes to discussions of importance, because discussions on Slack have a tendency to get lost or burried.

2023-02-20 21:30 UTC, louwers commented on CONTRIBUTING.md
> +For more complex proposed features that require deeper discussion, you may be invited to a [Technical Steering Committee](https://maplibre.org/categories/steering-committee/) meeting for a video disc
Should probably be reformulated to make it more clear that anyone that takes an interest is welcome to join these meetings.

2023-02-20 21:39 UTC, ZeLonewolf commented on CONTRIBUTING.md
> +For more complex proposed features that require deeper discussion, you may be invited to a [Technical Steering Committee](https://maplibre.org/categories/steering-committee/) meeting for a video disc
Proposed add:

"The Technical Steering Committee meetings are open to any contributors who want to get involved in the technical direction of the project. These meetings offer a chance for discussion and collaboration on various technical topics. We welcome you to join the meetings if you're interested in getting involved."

2023-02-20 21:45 UTC, ZeLonewolf commented on CONTRIBUTING.md
> +Maplibre welcomes contributions from community! This codebase is large and complex, and following these best practices will assist the maintainer team in reviewing your contribution. A good place to
Proposed:


Maplibre welcomes contributions from community! This codebase is large and complex, and following these best practices will assist the maintainer team in reviewing your contribution. In general, the project values discussion and communication over process and documentation. However, due to the size and complexity of the code, below are some best practices that have aided contributors.

It is a good idea to discuss proposed changes before proceeding to an issue ticket or PR. The project team is active in the following forums:
* For informal chat discussions, visit the project's [Slack Channel](https://osmus.slack.com/archives/C01G3D28DAB).
* For discussions of importance, consider opening a GitHub Discussions ticket so that other community members can collaborate in proposed solutions.

2023-02-20 21:47 UTC, louwers commented on CONTRIBUTING.md
> +For more complex proposed features that require deeper discussion, you may be invited to a [Technical Steering Committee](https://maplibre.org/categories/steering-committee/) meeting for a video disc
Also open to non-contributors. ;-)

2023-02-20 21:50 UTC, ZeLonewolf commented on CONTRIBUTING.md
> +For more complex proposed features that require deeper discussion, you may be invited to a [Technical Steering Committee](https://maplibre.org/categories/steering-committee/) meeting for a video disc
hah, okay "anyone"

2023-02-22 10:10 UTC, louwers commented on CONTRIBUTING.md
> +Maplibre welcomes contributions from community! This codebase is large and complex, and following these best practices will assist the maintainer team in reviewing your contribution. A good place to
```
For discussions whose output and outcomes should not be ephemeral, consider starting a thread on [GitHub Discussions](https://github.com/maplibre/maplibre-gl-js/discussions). This makes it easier to find and reference the discussion in the future. 
```

2023-02-22 10:12 UTC, louwers requested changes
Almost there.

2023-02-22 10:13 UTC, louwers commented on CONTRIBUTING.md
> +For more complex proposed features that require deeper discussion, you may be invited to a [Technical Steering Committee](https://maplibre.org/categories/steering-committee/) meeting for a video disc
Correct, anyone that takes an interest! Could be someone that may want to contribute in the future, a non-technical product manager from a geospatial company or a high school student interested in maps. They're really quite open as I understand it.

2023-03-01 12:15 UTC, HarelM commented
@ZeLonewolf can you please resolve the latest comments so this can be merged?
THANKS!

2023-03-01 17:09 UTC, ZeLonewolf commented
Updated per discussion.

2023-03-01 20:34 UTC, louwers commented on CONTRIBUTING.md
> +For new features, it is usually a good idea to start with an issue ticket. If the feature requires changes to the style specification, an issue ticket should be created in the [style specification gi
```suggestion
For new features, it is usually a good idea to start with an issue ticket. If the feature requires changes to the style specification, an issue ticket should be created in the [style specification GitHub repository](https://github.com/maplibre/maplibre-gl-style-spec). Style specification changes are hard to change later, so there will be particularly close scrutiny on changes to the specification.
```

2023-03-01 20:35 UTC, louwers commented on CONTRIBUTING.md
> +Maplibre welcomes contributions from community! This codebase is large and complex, and following these best practices will assist the maintainer team in reviewing your contribution. In general, the
```suggestion
MapLibre welcomes contributions from community! This codebase is large and complex, and following these best practices will assist the maintainer team in reviewing your contribution. In general, the project values discussion and communication over process and documentation. However, due to the size and complexity of the code, below are some best practices that have aided contributors.
```

2023-03-01 20:35 UTC, louwers commented on CONTRIBUTING.md
> +Maplibre software relies heavily on automated testing, and the project includes a suite of unit and integration tests. For both new features and bugfixes, contributions should update or add test case
```suggestion
MapLibre software relies heavily on automated testing, and the project includes a suite of unit and integration tests. For both new features and bugfixes, contributions should update or add test cases to prevent regressions.
```

2023-03-01 20:36 UTC, louwers approved these changes
Maplibre is stylized as MapLibre. Comitted some changes.

Otherwise LGTM. I don't have write permissions in the repo, so another approval is needed (or an invite 😉 ).

2023-03-02 10:47 UTC, HarelM commented on CONTRIBUTING.md
> +For more complex proposed features that require deeper discussion, you may be invited to a [Technical Steering Committee](https://maplibre.org/categories/steering-committee/) meeting for a video disc
```suggestion
For more complex proposed features that require deeper discussion, you should consider bringing it up in the [Technical Steering Committee](https://maplibre.org/categories/steering-committee/) meeting for a video discussion with the team about the proposed change. We find that sometimes it's easier to have a focused, face-to-face discussion for more consequential decisions.
```

2023-03-02 10:50 UTC, HarelM approved these changes

2023-03-02 14:01 UTC, merged