remove mapbox-gl-supported module
maplibre/maplibre-gl-js pull request #2451
Opened 2023-04-26 18:59 UTC by zhangyiatmicrosoft

## Launch Checklist

 - [ ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

2023-04-27 05:58 UTC, HarelM commented on src/ui/map.ts
> +        const webGLContextAttributes = {
This assumes we are using modern browsers, doesn't it?
Is there an easy why to check web gl supported features without using mapbox-gl-supported?

2023-04-27 05:59 UTC, HarelM commented
I generally think this is a good direction, I don't like stale libraries, but we need to make sure we cover the relevant cases.

2023-04-27 08:42 UTC, IvanSanchez commented on src/ui/map.ts
> +        const webGLContextAttributes = {
No, this just mimicks the behaviour of `@mapbox/mapbox-gl-supported`. No effort is made to detect support of `antialias`, `alpha`, `stencil` and `depth` (rather, see https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#browser_compatibility - only Safari is a problem)

2023-04-27 08:44 UTC, IvanSanchez requested changes

2023-04-27 08:44 UTC, IvanSanchez commented on src/ui/map.ts
> +        const attributes = extend({}, webGLContextAttributes, {
I'd rather get rid of `extend()` and use a single object literal, something like

```
const attributes = {
            alpha: true,
            stencil: true,
            depth: true,
            failIfMajorPerformanceCaveat: this._failIfMajorPerformanceCaveat,
            preserveDrawingBuffer: this._preserveDrawingBuffer,
            antialias: this._antialias ?? false
};
```

2023-04-27 08:45 UTC, HarelM commented on src/ui/map.ts
> +        const attributes = extend({}, webGLContextAttributes, {
I don't like `extend` either, super hard to understand what you'll get back after using it...

2023-04-27 17:44 UTC, zhangyiatmicrosoft commented on src/ui/map.ts
> +        const webGLContextAttributes = {
yes

2023-04-27 17:44 UTC, zhangyiatmicrosoft commented on src/ui/map.ts
> +        const attributes = extend({}, webGLContextAttributes, {
AGREE!

2023-04-27 18:51 UTC, HarelM approved these changes

2023-04-27 18:52 UTC, merged

2023-04-28 16:06 UTC, pramilk commented
@HarelM, @zhangyiatmicrosoft 
Does this documention need to be updated?
https://maplibre.org/maplibre-gl-js-docs/api/properties/#supported

2023-04-28 17:16 UTC, HarelM commented
I guess the example is either not relevant anymore or needs to be updated, I hope the supported will be removed automatically once the docs will be generated for version 3.
In any case, both issues should be addressed in the docs repo for now (until we move it here).

2023-06-06 11:00 UTC, ambientlight commented
@HarelM, @zhangyiatmicrosoft: should we fork the `@mapbox/mapbox-gl-supported`? since per webgl2 by default we would need to check for the existence of `webgl2` I guess now?