Add codecov badge
maplibre/maplibre-gl-js pull request #2647
Opened 2023-06-07 12:26 UTC by HarelM

I've added the codecov badge in the readme which links to the codecov project.

2023-06-07 12:30 UTC, birkskyum approved these changes

2023-06-07 12:42 UTC, louwers approved these changes

2023-06-07 12:43 UTC, louwers requested changes
See comment.

2023-06-10 06:12 UTC, HarelM commented
Done.

2023-06-10 06:12 UTC, merged