fix #334 add esm export
maplibre/maplibre-gl-js pull request #368
Opened 2021-09-20 09:06 UTC by lhapaipai

in order to continue the discussion #334

In my opinion, there is an issue with the default export of the package.
According to the `package.json` 
```json
{
  "main": "dist/maplibre-gl.js",
  "type": "module",
}
```
The maplibre-gl package is using the ESM modules but the output is an UMD file.

If I build an app who follows the esm specification and who wants to import maplibre-gl
The application will apply the [esm resolver algorithm](https://nodejs.org/api/esm.html#esm_resolver_algorithm)
```
ESM_FORMAT(url)

  Assert: url corresponds to an existing file.
  Let pjson be the result of READ_PACKAGE_SCOPE(url).
  If url ends in ".mjs", then
      Return "module".
  If url ends in ".cjs", then
      Return "commonjs".
  If pjson?.type exists and is "module", then
      If url ends in ".js", then
          Return "module".
      Throw an Unsupported File Extension error.
  Otherwise,
      Throw an Unsupported File Extension error.
```
the application will retrieve the `dist/maplibre-gl.js` file but will consider it to be an esm file.
I suggest adding a module entry in the `package.json` who provides a esm export. By keeping the current main entry, we have a way to easily implement maplibre and with the module entry we allow bundlers (like ViteJS) following the esm specification to find the right export format.

What do you think about that ?

I'm not talking about the isomorphic side dealt with at the end of the discussion #334  which is another discussion.

2021-09-20 09:26 UTC, HarelM commented
Can you please add a change log entry about this?
I have no objections, I'm lost when it comes to all the mess related to importing stuff in js.
If this commit is the standard in the industry I'm all for it...

2021-09-20 10:49 UTC, HarelM requested changes
Snall nitpicking...

2021-09-20 10:49 UTC, HarelM commented on rollup.config.js
>  const outputFile =
If this is not the full file name please change the variable name as well - outpuFilePrefix, or outpitFileWithoitExtension

2021-09-20 10:49 UTC, HarelM commented on CHANGELOG.md
> +- Add module entrypoint for ESM (#334)
Wring place, should be one line upwards.

2021-09-20 11:48 UTC, lhapaipai commented
this has been fixed.
But, there is still an issue.
We do not have the named exports when we import Maplibre GL with ESM.

2021-09-20 12:41 UTC, lhapaipai commented
With CommonJS syntax, we can default export an object and its properties are found in the named exports.
Actually
```js
// src/index.ts
const exported = {
    Map,
    NavigationControl,
    //...
};
export default exported;
```
with rollup became
```js
// dist/maplibre-gl.js
module.exports = {
    Map,
    NavigationControl,
    // ...
};
```
in your app
```js
import maplibregl from "maplibre-gl"; // ok
import { Map } from "maplibre-gl"; // ok
```

with ESM we must explicitly define the named export
something like this should be done in `index.ts`.
```js
// src/index.ts
export { Map } from './ui/map';
export { NavigationControl } from './ui/control/navigation_control';
export default { Map, NavigationControl };
//...
```
```js
import maplibregl from "maplibre-gl"; // ok
import { Map } from "maplibre-gl"; // ok
```
I unfortunately do not really know how to operate with the getters setters in `src/index.ts`.
I'm not very comfortable with these compatibility issues either...
Someone would have any idea ?

2021-11-03 16:23 UTC, anajavi commented
The ```"module": "dist/maplibre-gl.module.js"``` is only recognized by bundlers like webpack.

[When importing with node an "exports" field should be added](https://nodejs.org/api/packages.html#conditional-exports). Something like this:
```json
  "main": "./dist/maplibre-gl.cjs",
  "exports": {
    "import": "./dist/maplibre-gl.module.js",
    "require": "./dist/maplibre-gl.cjs"
  },
```

2021-11-03 16:53 UTC, lhapaipai commented
I totally agree with you @anajavi.
Your solution allows you to obtain a default export but like mine it does not allow named exports with a bundler like Vite and creates 2 almost totally similar files.

2021-11-11 19:10 UTC, lhapaipai commented
I think that by explicitly specifying an esm export without named exports you lose flexibility. I therefore close this request and propose a simpler alternative #635.

2021-11-11 19:10 UTC, closed without merging

2021-11-18 14:37 UTC, HarelM commented
Can you guys check my poposed fixed in the following comment:
https://github.com/maplibre/maplibre-gl-js/issues/370#issuecomment-972923342
I think it's a very simple fix that doesn't require a lot of changes...