Update codegen build scripts
maplibre/maplibre-gl-js pull request #438
Opened 2021-10-04 23:17 UTC by drwestco

Update the generate-foo build scripts to TS, and modify output templates to generate TS files instead of Flow-typed JS. Requires addition of ts-node npm package to compile TS modules on-demand during codegen build step.

Fixes #266 

## Launch Checklist

 - [X] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] briefly describe the changes in this PR
 - [X] manually test the debug page

2021-10-05 05:01 UTC, HarelM commented
This is great progress!
Can you explain why there are js import statements? Can't we keep everything in ts? I.e. Import ... some-file and not import ... some-file.js?

2021-10-05 08:11 UTC, HarelM requested changes
This is great to see how the files are created very similar to how they were defined before and to see that I have made some conversion mistakes that are now fixed. :-)
Thanks for pushing this forward! the comments I added here are relatively small and should not be hard to fix, I hope.

2021-10-05 08:11 UTC, HarelM commented on build/tsconfig.json
> +  "compilerOptions": {
Do we really need this file? Isn't the base file enough?

2021-10-05 08:11 UTC, HarelM commented on src/data/bucket/circle_attributes.ts
> +import {createLayout} from '../../util/struct_array.js';
Why are these changes to the import are needed? Can we add a flag to codegen node call to support this? I think this is done in other node calls, something with experimental...

2021-10-05 08:11 UTC, HarelM commented on src/style/style_layer/layer_properties.js.ejs
> +// This file is generated. Edit build/generate-style-code.ts, then run `npm run codegen`.
Can we move this file to be in the build folder along side the other script that generate code? Or maybe even in their own folder, feels weird that this is here to me...

2021-10-05 08:11 UTC, HarelM commented on src/util/struct_array.js.ejs
> -<%  } -%>
Same for this file - move to build folder

2021-10-05 14:42 UTC, drwestco commented on build/generate-struct-arrays.ts
> +import type {ViewType, StructArrayLayout} from '../src/util/struct_array.js';
Ah, I should have linked this issue, explaining the limitations of node+ts-node's ESM support. The config and import statement changes were all following the recommendations here: https://github.com/TypeStrong/ts-node/issues/1007

The short answer for the .js extension here is that node will reject the import without it. Typescript allows the import with or without the .js extension, and uses the matching .ts module in either case. So the .js is just a little ugliness to keep node happy here.

2021-10-05 14:44 UTC, drwestco commented on build/generate-style-code.ts
> +function flowType(property) {
How about nativeType?

2021-10-05 14:50 UTC, drwestco commented on build/generate-style-spec.ts
> +const spec = JSON.parse(fs.readFileSync('src/style-spec/reference/v8.json', 'utf8'));
That's what it was doing, but stopped working when I switched to TS. It compiled and ran without error, but spec kept coming back as undefined.

2021-10-05 14:52 UTC, drwestco commented on build/generate-style-code.ts
> +global.runtimeType = runtimeType;
Sticking then in global makes them available to the .ejs scripts. The previous generate- .js was doing the same, but I needed to split up the function declaration from global property assignment to keep TS happy.

2021-10-05 14:54 UTC, drwestco commented on build/generate-style-spec.ts
> +    return `export type ${key} = ${flowObject(properties, '')};`;
Some weird flow syntax where it was inserting pipes after opening curlies in object definitions.

2021-10-05 14:55 UTC, drwestco commented on src/style/style_layer/layer_properties.js.ejs
> +// This file is generated. Edit build/generate-style-code.ts, then run `npm run codegen`.
Yeah, I was wondering why they weren't in the build folder.

2021-10-05 15:20 UTC, drwestco commented on build/tsconfig.json
> +  "compilerOptions": {
Looks like the settings I used here converged with those in the base file, and this is no longer needed. Deleted.

2021-10-05 15:23 UTC, drwestco commented on src/data/bucket/circle_attributes.ts
> +import {createLayout} from '../../util/struct_array.js';
Ah, cool. `--experimental-specifier-resolution=node` works here, instead of adding explicit extensions.

2021-10-05 15:25 UTC, drwestco commented on build/generate-struct-arrays.ts
> +import type {ViewType, StructArrayLayout} from '../src/util/struct_array.js';
Per other convo, `--experimental-specifier-resolution=node` works, so .js extension workaround is not actually needed.

2021-10-05 15:33 UTC, HarelM commented on build/generate-style-code.ts
> +function flowType(property) {
`getType`? nativeType also works for me.

2021-10-05 15:35 UTC, HarelM commented on build/generate-style-code.ts
> +global.runtimeType = runtimeType;
Do we have to use the ejs files? Can't we simply use string manipulation with backticks?

2021-10-05 15:42 UTC, drwestco commented on package.json
> +    "codegen": "node --loader ts-node/esm build/generate-style-code.ts && node --loader ts-node/esm build/generate-struct-arrays.ts"
Any idea why generate-style-spec to create style-spec/types.ts isn't included in the codegen step? Should it be?

2021-10-05 16:01 UTC, HarelM commented on package.json
> +    "codegen": "node --loader ts-node/esm build/generate-style-code.ts && node --loader ts-node/esm build/generate-struct-arrays.ts"
No clue, probably for no good reason. This repo has a lot of things to order...

2021-10-05 16:30 UTC, drwestco commented on build/generate-style-spec.ts
> +const spec = JSON.parse(fs.readFileSync('src/style-spec/reference/v8.json', 'utf8'));
Either had a typo before, or the --experimental switch helped here. It's working as an import now.

2021-10-05 16:34 UTC, HarelM commented on build/generate-style-spec.ts
> +const spec = JSON.parse(fs.readFileSync('src/style-spec/reference/v8.json', 'utf8'));
You need another flag, something with json. Check the package.json, it's there...

2021-10-05 19:56 UTC, HarelM commented
The changes look great! Thanks!
One last request, and sorry for being anal, can you please add a readme.md file inside the build folder and say a few words about how this is working, what it should do and when to use it.
It seems that this repo has readme files in a lot of strategic places and I think this should also be one of them.
There's a lot of code in the build folder which does all kind of things like this generation and other stuff that I think we should document, not part of this PR of course.
I'll add to it once added all the build steps that the main code is running through too.
Thanks again!!

2021-10-06 05:43 UTC, HarelM approved these changes

2021-10-06 05:46 UTC, merged