Camera Roll
maplibre/maplibre-gl-js pull request #4780
Opened 2024-09-30 15:16 UTC by NathanMOlson

Reopening accidentally closed PR: https://github.com/maplibre/maplibre-gl-js/pull/4771

This is the first part of https://github.com/maplibre/maplibre-gl-js/issues/4717: adding camera roll.

In this PR, roll is defined as rotation about the camera boresight. Rotation order is bearing, pitch, roll. easeTo() and flyTo() are implemented using linear interpolation of Euler angles.

You can play with this feature here, using the controls in the top right corner: https://nathanmolson.github.io/camera_roll

There is some weirdness near +/- 90 degrees roll, but I'd like to get https://github.com/maplibre/maplibre-gl-js/pull/4750 merged before attempting to address it.

2024-10-03 03:02 UTC, ssokol commented
I'm not qualified to comment on the details of the code, but in terms of meeting the requirements for the bounty, this is spot on. As far as I am concerned, the requirement is met.

2024-10-05 15:53 UTC, HarelM commented on src/geo/projection/mercator_transform.ts
> +        const zfov = this._helper._fov * (Math.abs(Math.cos(this._helper._roll)) * this._helper._height + Math.abs(Math.sin(this._helper._roll)) * this._helper._width) / this._helper._height;
Can this use getters instead of underscore fields?

2024-10-05 15:56 UTC, HarelM commented on src/geo/transform_helper.ts
> +        this._roll = thatI.roll * Math.PI / 180;
This is strange, for other fields as well, not just roll... I would expect a straight assignment without angle conversion...

2024-10-05 16:05 UTC, HarelM commented
Overall looks good! 
Can you add a render test that shows both straight text and tilted horizon?

2024-10-05 16:09 UTC, NathanMOlson commented on src/geo/projection/mercator_transform.ts
> +        const zfov = this._helper._fov * (Math.abs(Math.cos(this._helper._roll)) * this._helper._height + Math.abs(Math.sin(this._helper._roll)) * this._helper._width) / this._helper._height;
Sure, I'll do that.

Getters are in degrees, underscore fields are in radians.

I was following a patter I saw in other places in the code where underscore fields are used for trig functions, presumably to avoid a call to `degreesToRadians()`.

2024-10-05 16:11 UTC, NathanMOlson commented on src/geo/transform_helper.ts
> +        this._roll = thatI.roll * Math.PI / 180;
Getters are in degrees, underscore fields are in radians. I haven't changed that in this PR, but it sure introduces a lot of places for units errors.

2024-10-05 16:12 UTC, NathanMOlson commented
> Overall looks good! Can you add a render test that shows both straight text and tilted horizon?

Will do.

2024-10-05 16:18 UTC, NathanMOlson commented on src/geo/projection/mercator_transform.ts
> +        mat4.rotateZ(m, m, -this._helper._roll);
@HarelM Do you want this changed to use a getter also? what about the following 2 unchanged lines?

2024-10-05 17:08 UTC, HarelM commented on src/geo/projection/mercator_transform.ts
> +        mat4.rotateZ(m, m, -this._helper._roll);
I honestly don't know. 
Maybe the internal fields should be renamed to rollInRadians so that we'd know from reading the code what to expect? 
The public API doesn't need to change to facilitate that...

2024-10-05 17:09 UTC, HarelM commented on src/geo/projection/mercator_transform.ts
> +        mat4.rotateZ(m, m, -this._helper._roll);
Or we can add getters only that are without the conversation? IDK...
I don't like all this undocumented know how...

2024-10-05 17:32 UTC, NathanMOlson commented on src/geo/projection/mercator_transform.ts
> +        const zfov = this._helper._fov * (Math.abs(Math.cos(this._helper._roll)) * this._helper._height + Math.abs(Math.sin(this._helper._roll)) * this._helper._width) / this._helper._height;
Done, in this particular spot.

2024-10-05 17:33 UTC, NathanMOlson commented on src/geo/projection/mercator_transform.ts
> +        mat4.rotateZ(m, m, -this._helper._roll);
Let me know. I can change the internal field names if that's what you want, but if I don't know what to do my strategy is "don't change it" :)

2024-10-10 01:42 UTC, NathanMOlson commented on src/geo/projection/mercator_transform.ts
> +        mat4.rotateZ(m, m, -this._helper._roll);
OK, I changed the private fields from `_roll`, `_pitch`, ... to `_rollInRadians`, ....
I added direct getters for these fields in the `TransformHelper`, as well as in the `TransformInterface`.
I changed uses of these fields to use the getter instead of going though `_helper` or converting from degrees.
I replaced the ambiguous field `_angle` with `_bearingInRadians`, which is its negative.

2024-10-10 09:24 UTC, HarelM commented
CC: @louwers - note that there are tests here that are related to roll which is not supported in native and might cause problems with parity testing. Can you suggest a way to void it? Should all new tests be in a partent folder called `roll` or something?

@NathanMOlson I see that the style that is used in the render test has a `roll` property in the root of the object.
This is in continue to the monthly meeting yerterday.
Do you think it should be added to the root style spec object:
https://maplibre.org/maplibre-style-spec/root/
I would expect that adding it to the root object in the style.json file as you did, without changing the style spec validation, should fail, shouldn't it?

2024-10-10 09:30 UTC, HarelM commented on src/geo/projection/mercator_camera_helper.ts
> +            if (!quat.equals(startRotation, endRotation)) {
Is this code identical to the code in globe_camera_helper.ts?
Can we extract it to somewhere if so?

2024-10-10 09:33 UTC, HarelM commented on src/geo/projection/mercator_transform.ts
> +            angleCos = Math.cos(this.bearingInRadians), angleSin = Math.sin(-this.bearingInRadians),
Missing a "-" here for the first `cos` method or is it OK since it's a `cos` method?

2024-10-10 09:36 UTC, HarelM commented on src/render/program/sky_program.ts
> +    const cosRoll = Math.cos(transform.roll * Math.PI / 180.0);
Can this use the `InRadians` getter?

2024-10-10 11:08 UTC, HarelM commented on src/symbol/projection.ts
> +    const cosRoll = Math.cos(degreesToRadians(transform.roll));
Can we use `rollInRadians`?

2024-10-10 11:10 UTC, HarelM commented on src/symbol/projection.ts
> +    return skew;
Consider returning two vectors instead of a mat2, as I don't think the mat2 is used as is, and returning 2 vectors might be a bit more readable.

2024-10-10 12:54 UTC, louwers requested changes
Changes to the Style Specification should first go through a [design proposal process](https://github.com/maplibre/maplibre-style-spec/issues/new?assignees=&labels=&projects=&template=design_proposal.md&title=) in the MapLibre Style Spec repo.

2024-10-10 14:11 UTC, NathanMOlson commented
> @NathanMOlson I see that the style that is used in the render test has a `roll` property in the root of the object.
> This is in continue to the monthly meeting yerterday.
> Do you think it should be added to the root style spec object:
> https://maplibre.org/maplibre-style-spec/root/

I do not require roll in the root style spec object, as I will be continuously setting `roll` using `map.jumpTo()`. However, it is needed for tests, and pitch and bearing are in the root style spec object, so I guess it makes sense for roll to join them. I'll make a design proposal.

> I would expect that adding it to the root object in the style.json file as you did, without changing the style spec validation, should fail, shouldn't it?

I believe it works due to this magic section of code (map.ts line 719):

```
        this.on('style.load', () => {
            if (this.transform.unmodified) {
                this.jumpTo(this.style.stylesheet as any);
            }
        });

2024-10-10 14:21 UTC, NathanMOlson commented on src/geo/projection/mercator_transform.ts
> +            angleCos = Math.cos(this.bearingInRadians), angleSin = Math.sin(-this.bearingInRadians),
`cos()` is symmetric: `cos(x) === cos(-x)`

2024-10-10 14:23 UTC, NathanMOlson commented on src/symbol/projection.ts
> +    const cosRoll = Math.cos(degreesToRadians(transform.roll));
Done.

2024-10-10 14:23 UTC, NathanMOlson commented on src/render/program/sky_program.ts
> +    const cosRoll = Math.cos(transform.roll * Math.PI / 180.0);
Done.

2024-10-10 14:29 UTC, NathanMOlson commented on src/symbol/projection.ts
> +    return skew;
This is used as a `mat2` in projection.ts line 102.

2024-10-10 14:50 UTC, NathanMOlson commented on src/geo/projection/mercator_camera_helper.ts
> +            if (!quat.equals(startRotation, endRotation)) {
Yes. Done.

2024-10-10 17:41 UTC, louwers submitted a review, later dismissed

2024-10-10 17:42 UTC, louwers commented
Understood!

2024-10-10 17:42 UTC, louwers reviewed
Understood!

2024-10-15 06:37 UTC, HarelM commented
We should change the above code you mention to be a lot more specific, this `as any` is a bad idea, we should create a obejct with the relevant parameters from the stylespec instance, this way setting roll would not be possible without a spec change.

2024-10-15 06:38 UTC, HarelM commented on src/geo/projection/mercator_camera_helper.ts
> +            if (!quat.equals(startRotation, endRotation)) {
Did you forget to push a commit?

2024-10-15 06:40 UTC, HarelM commented on src/symbol/projection.ts
> +    return skew;
I think you use this in two different places in a different way.
I think a two points vector is a better API to understand what is happening here and the mat2 can be constructed in the relevant place.

2024-10-15 06:55 UTC, HarelM commented
Another thing I just thought about is a dedicated control for this.
All other viewport possible changes can be updated using the `NavigationControl`.
I think there should be some options to allow changing the roll from a dedicated button in the navigation control if the user sets it to true, like the visualize pitch and show compass.
See here:
https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/NavigationControlOptions/
Also, there is a non-interactive map flag that need to support this as well in case there is a control, I think, not sure.

Otherwise, after adding the roll to the spec, updating the spec package here and addressing the above, I think this can be merged.

2024-10-15 16:10 UTC, NathanMOlson commented on src/geo/projection/mercator_camera_helper.ts
> +            if (!quat.equals(startRotation, endRotation)) {
I don't think so. I moved the spherical interpolation code into `updateRotation()`, which is called on the next line.

```if (!quat.equals(startRotation, endRotation))```

is still duplicated but I don't think it's a good candidate for extracting.

2024-10-15 16:25 UTC, NathanMOlson commented on src/symbol/projection.ts
> +    return skew;
Done.

2024-10-15 16:48 UTC, NathanMOlson commented
> Otherwise, after adding the roll to the spec, updating the spec package here and addressing the above, I think this can be merged.

@HarelM Is the NavigationControl update required to merge this? I don't intend to ever use the NavigationControl.

2024-10-15 17:18 UTC, HarelM commented
I believe so, also an example page with this new functionality, preferably with a control the users can interact with.

2024-10-16 00:17 UTC, NathanMOlson commented
OK, Here's a demo of the updated NavigationControl. https://nathanmolson.github.io/camera_roll

1. The compass icon now indicates the roll angle (when `visualizeRoll` is `true`).
2. The user can control the roll angle by pressing `Ctrl` and right-click and dragging.

@HarelM if this is acceptable I will add unit tests and an example page. Or I can extend an existing example (maybe `navigation`, `3d-terrain`, or `set-perspective`?)

2024-10-16 11:46 UTC, HarelM commented on src/ui/control/navigation_control.ts
> +    visualizeRoll: true
Should probably be `false` by default...?

2024-10-16 11:48 UTC, HarelM commented on src/ui/control/navigation_control.ts
> +        if (this.options.visualizePitch) {
consider using if statement and return to reduce indentation and complexity:
```ts
if (this.options.visualizePitch && this.options.visualizeRoll) { 
   ...
   return;
}
if (something else) {
   ...
   return;
}
```

2024-10-16 11:51 UTC, HarelM commented on src/ui/handler/mouse.ts
> +            ({rollDelta: (point.x - lastPoint.x) * rollDegreesPerPixelMoved}),
According to what I tested, I think this needs to be in the opposite direction - i.e. when moving the mouse right I expect the right part to be "lowered".
Not sure if it's exactly here or not.

2024-10-16 11:53 UTC, HarelM commented
I think the demo look.
I've added a few minor comments.
Please make sure to merge main and resolve conflicts.
I think the [navigation](https://maplibre.org/maplibre-gl-js/docs/examples/navigation/) example should be altered to add pitch and roll visualization and enable roll there as well.

2024-10-16 11:56 UTC, HarelM commented
Please also see if you can update the style-spec package that was just released and remove the `as any` we talked about.

2024-10-16 15:18 UTC, NathanMOlson commented on src/ui/control/navigation_control.ts
> +    visualizeRoll: true
When pitch = 0, roll and bearing are identical. If `visualizeRoll` is false, the compass icon might display differently when the map is displayed exactly the same, but the internal  representation is different. (For example, `pitch=0, bearing=0, roll=45` would show the same map view as `pitch=0, bearing=45, roll=0`, but would show a different compass icon if `visualizeRoll` is false).

For this reason, I think the default value should be `true`. In a typical use case, where roll never deviates from 0, `visualizeRoll` has no impact.

2024-10-16 15:22 UTC, NathanMOlson commented on src/ui/handler/mouse.ts
> +            ({rollDelta: (point.x - lastPoint.x) * rollDegreesPerPixelMoved}),
I do not think the behavior should change. As currently implemented, at pitch = 0, roll and bearing are the same, and roll control behaves the same as bearing control. Your proposed change would cause identical mouse movements to move bearing and roll in opposite directions, which seems unexpected and confusing.

2024-10-16 15:35 UTC, NathanMOlson commented on src/ui/control/navigation_control.ts
> +        if (this.options.visualizePitch) {
Done.

2024-10-16 22:30 UTC, HarelM commented on src/ui/handler/mouse.ts
> +            ({rollDelta: (point.x - lastPoint.x) * rollDegreesPerPixelMoved}),
I see what you mean about mouse movement for bearing.
If you are looking at the map from the top then dragging above the center of the map behaves "opposite", as if the gesture is expecting to be done below the center of the map to feel intuitive.
This is not the case for mobile as you have two fingers which defines the rotation better.
I believe both roll and bearing mouse gestures needs to be changed to be "better".
Something like taking into consideration the point where the gesture started and calculating the angle from the map center or view center for the rotation.
Here's a movie I made, I was not aware that this is the case, it doesn't make any sense...

https://github.com/user-attachments/assets/1b35b4e3-cf90-4b78-819e-b4186a850e84

I don't know if this is out of scope for this PR, but I wouldn't like to pile up on the "bad" behavior.
Since we are still in 5.x pre-release, this can be a breaking change that can be introduced at this point.

2024-10-16 22:35 UTC, HarelM commented on src/ui/map.ts
> +                const coercedOptions = pick(this.style.stylesheet, ['center', 'zoom', 'bearing', 'pitch', 'roll']) as CameraOptions;
Is it possible to make this a bit more strict somehow?
Maybe by creating an object of type `CameraOptions`?
Something like:
```ts
const coercedOptions: CameraOptions = {
  center: this.style.stylesheet.center,
  ...
}
```

2024-10-16 22:36 UTC, HarelM commented on src/ui/control/navigation_control.ts
> +    visualizeRoll: true
I guess since roll is disabled by default then this won't be a problem, right?

2024-10-16 22:39 UTC, HarelM commented
Last two comments hopefully before this can get merged.
Thanks a lot for answering my annoying code review comments, I know this can be irritating and I appreciate your openness and patience.

2024-10-17 00:01 UTC, NathanMOlson commented on src/ui/map.ts
> +                const coercedOptions = pick(this.style.stylesheet, ['center', 'zoom', 'bearing', 'pitch', 'roll']) as CameraOptions;
That's what I tried at first. I got a ton of unit test failures and I don't understand how they are related, so I copied a working example from `camera.ts`.

Here's an example of what happens using your approach (there are other failed test suites as well):

```
                const coercedOptions: CameraOptions = {
                    center: new LngLat(this.style.stylesheet.center[0], this.style.stylesheet.center[1]),
                    zoom: this.style.stylesheet.zoom,
                    bearing: this.style.stylesheet.bearing,
                    pitch: this.style.stylesheet.pitch,
                    roll: this.style.stylesheet.roll
                };
```
                
=>

npx jest src/ui/map_tests/map_layer.test.ts --reporters=default
 FAIL   unit  src/ui/map_tests/map_layer.test.ts (75.728 s)
  ✕ #moveLayer (5003 ms)
  ✕ #getLayer (5001 ms)
  ✕ #removeLayer restores Map#loaded() to true (5003 ms)
  #getLayersOrder
    ✕ returns ids of layers in the correct order (5003 ms)
  #setLayoutProperty
    ✕ sets property (5001 ms)
    ✓ throw before loaded (8 ms)
    ✕ fires an error if layer not found (5002 ms)
    ✕ fires a data event (5002 ms)
    ✕ sets visibility on background layer (5002 ms)
    ✕ sets visibility on raster layer (5004 ms)
    ✕ sets visibility on video layer (5004 ms)
    ✕ sets visibility on image layer (5004 ms)
  #getLayoutProperty
    ✕ fires an error if layer not found (5003 ms)
  #setPaintProperty
    ✕ sets property (5002 ms)
    ✕ #3373 paint property should be synchronized with an update (5001 ms)
    ✓ throw before loaded (5 ms)
    ✕ fires an error if layer not found (5002 ms)

  ● #moveLayer

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      17 | });
      18 |
    > 19 | test('#moveLayer', async () => {
         | ^
      20 |     const map = createMap({
      21 |         style: extend(createStyle(), {
      22 |             sources: {

      at Object.<anonymous> (src/ui/map_tests/map_layer.test.ts:19:1)

2024-10-17 00:02 UTC, NathanMOlson commented on src/ui/handler/mouse.ts
> +            ({rollDelta: (point.x - lastPoint.x) * rollDegreesPerPixelMoved}),
I think that's out of scope fir this PR.

2024-10-17 00:12 UTC, NathanMOlson commented on src/ui/map.ts
> +                const coercedOptions = pick(this.style.stylesheet, ['center', 'zoom', 'bearing', 'pitch', 'roll']) as CameraOptions;
@HarelM this works: 
```
                let coercedOptions: CameraOptions = {}
                if (this.style.stylesheet.center != undefined) {
                    coercedOptions.center = new LngLat(this.style.stylesheet.center[0], this.style.stylesheet.center[1]);
                }
                if (this.style.stylesheet.zoom != undefined) {
                    coercedOptions.zoom = this.style.stylesheet.zoom;
                }
                if (this.style.stylesheet.bearing != undefined) {
                    coercedOptions.bearing = this.style.stylesheet.bearing;
                }
                if (this.style.stylesheet.pitch != undefined) {
                    coercedOptions.pitch = this.style.stylesheet.pitch;
                }
                if (this.style.stylesheet.roll != undefined) {
                    coercedOptions.roll = this.style.stylesheet.roll;
                }
```

Do you like this better than the current `pick()`? Or do you have any idea how to turn this into something prettier?

2024-10-17 00:14 UTC, NathanMOlson commented on src/ui/control/navigation_control.ts
> +    visualizeRoll: true
Correct.

2024-10-17 11:54 UTC, HarelM commented on src/ui/map.ts
> +                const coercedOptions = pick(this.style.stylesheet, ['center', 'zoom', 'bearing', 'pitch', 'roll']) as CameraOptions;
I've looked into it.
I think pick is doing these if in a shorter why and is typesafe enough.
I would like the `CameraOptions` to be defined before the `pick` but I see the Stylespec's `center` is defined as a `number[]` and the `CameraOptions` is expecting `center` to be `[number, number]`.
I think this might be solvable by adjusting the style-spec package exported types.
What do you think?

2024-10-17 11:55 UTC, HarelM commented on src/ui/map.ts
> +                const coercedOptions = pick(this.style.stylesheet, ['center', 'zoom', 'bearing', 'pitch', 'roll']) as CameraOptions;
In any case, this is not a showstopper for this PR, this is nit picking in the nice-to-have realm.
If you feel like improving this bit feel free to open a PR etc.

2024-10-17 11:57 UTC, HarelM approved these changes

2024-10-17 12:08 UTC, merged

2024-10-17 15:53 UTC, NathanMOlson commented on src/ui/map.ts
> +                const coercedOptions = pick(this.style.stylesheet, ['center', 'zoom', 'bearing', 'pitch', 'roll']) as CameraOptions;
We should probably figure out what to do about center-point elevation before changing the style-spec package exported types. https://github.com/maplibre/maplibre-style-spec/issues/851

2024-10-17 17:42 UTC, HarelM commented on src/ui/map.ts
> +                const coercedOptions = pick(this.style.stylesheet, ['center', 'zoom', 'bearing', 'pitch', 'roll']) as CameraOptions;
These doesn't have to be tied together, we can improve the style spec typings to supports current implementation and change that when needed in the future.