[Jest] Migrate `camera.test.js`
maplibre/maplibre-gl-js pull request #654
Opened 2021-11-21 13:07 UTC by wipfli

2021-11-21 13:08 UTC, wipfli commented
I solved the `0 !== -0` issue with `expect(x).toBeCloseTo(0)`. Hope that is fine.

2021-11-21 16:47 UTC, HarelM commented
@astridx defined a different way I believe...?

2021-11-21 16:56 UTC, HarelM requested changes

2021-11-21 16:56 UTC, HarelM commented on src/ui/camera.test.ts
> +class TestCamera extends Camera {
CameraMock instead of TestCamera

2021-11-21 16:56 UTC, HarelM commented on src/ui/camera.test.ts
> +function createCamera(options) {
Make this optional parameter and remove undefined in all places.

2021-11-21 17:35 UTC, astridx commented
> @astridx defined a different way I believe...?

At the beginn of the migration I thought that it might be good to have a similar way to handle the zero null. That is why I added it here: https://github.com/maplibre/maplibre-gl-js/issues/458 in point 4.

Now I am not sure if we need a consistent way.

2021-11-21 20:44 UTC, wipfli commented on src/ui/camera.test.ts
> +class TestCamera extends Camera {
Thanks, sounds better indeed.

2021-11-22 02:16 UTC, HarelM approved these changes

2021-11-22 02:24 UTC, merged

2021-11-22 07:42 UTC, astridx commented on src/ui/camera.test.ts
> +    test('sets center', done => {
I have not yet fully understood the done thing. Why do we need this here?

2021-11-22 08:18 UTC, HarelM commented on src/ui/camera.test.ts
> +    test('sets center', done => {
You are right, it's not needed here, and in some other tests, I missed that...