Type signatures for grid_index, symbol_layout
maplibre/maplibre-gl-js pull request #658
Opened 2021-11-23 00:47 UTC by drwestco

## Launch Checklist

Splitting out the type signature/code cleanup changes from #347 for ease of review.

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [X] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2021-11-23 06:49 UTC, HarelM requested changes
This is great! I've added a few minor comments.

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +            return result;
Why was this changed? Do we not use predicate in any place?

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +    private _queryCircle(x: number, y: number, radius: number, predicate?: (key: T) => boolean) {
Can you elaborate on this change?

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +    private _query(x1: number, y1: number, x2: number, y2: number, hitTest: boolean, predicate?: (key: T) => boolean) {
Add return value so that there won't be a need to cast the results of this method

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
>                  return true;
Can we change this instead of returning two types of objects - i.e. return an empty list in case of no results...

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +    private _queryCircle(x: number, y: number, radius: number, predicate?: (key: T) => boolean) {
Also add return value

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +        return this._query(x1, y1, x2, y2, false, null) as Array<QueryResult<T>>;
Remove `as something` and add return value to method. preferably return only one type of object.

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +    private _queryCellCircle(x1: number, y1: number, x2: number, y2: number, cellIndex: number, result: Array<boolean>, queryArgs: QueryArgs, predicate?: (key:T) => boolean) {
Add return value

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +        arg2?: any,
Isn't `arg2` here is of type `QueryArgs`? Do we know what `arg1` type is?

2021-11-23 06:49 UTC, HarelM commented on src/symbol/grid_index.ts
> +        arg2?: any,
Can we have `arg1` to be of a generic type? i.e. `_forEachCell<TArg>(... arg1: TArg...)`

2021-11-23 06:49 UTC, HarelM commented on src/symbol/collision_index.ts
> +export type FeatureKey = {
This is great!

2021-11-23 14:58 UTC, drwestco commented on src/symbol/grid_index.ts
> +            return result;
Yeah, the non-hitTest path via the public query() method never uses predicate.

2021-11-23 15:20 UTC, drwestco commented on src/symbol/grid_index.ts
> +        arg2?: any,
good!

2021-11-24 07:36 UTC, HarelM commented on src/symbol/grid_index.ts
> +    private _queryCell(x1: number, y1: number, x2: number, y2: number, cellIndex: number, result: Array<QueryResult<T>>, queryArgs: QueryArgs, predicate?: (key: T) => boolean): boolean {
I don't think the return value of this method is used, right? If it's not in use then just return in case of hit test, if it is used I guess there's a need to `return false` at the end...

2021-11-24 07:38 UTC, HarelM commented on src/symbol/symbol_layout.ts
> +            horizontal: {} as any,
`as Record<TextJustify, Shaping>`?

2021-11-24 07:39 UTC, HarelM commented on src/symbol/symbol_layout.ts
> +    } as any;
How come this `as any` didn't exist in the previous code?

2021-11-24 07:40 UTC, HarelM commented
LGTM besides the last few nits... Thanks!

2021-11-24 15:07 UTC, drwestco commented on src/symbol/grid_index.ts
> +    private _queryCell(x1: number, y1: number, x2: number, y2: number, cellIndex: number, result: Array<QueryResult<T>>, queryArgs: QueryArgs, predicate?: (key: T) => boolean): boolean {
Yeah, it's used to stop the _forEachCell when the first collision has been found in the hitTest case. Surprised tsc/eslint didn't complain about the lack of explicit return at the end.

2021-11-24 15:11 UTC, drwestco commented on src/symbol/symbol_layout.ts
> +    } as any;
I guess I can do `as Sizes` here. Previous code was a generic property bag; Sizes has required properties, so some cast is needed.

2021-11-24 15:47 UTC, merged