Fix MapDataEvent#isSourceLoaded being true in GeoJSONSource "dataloading" event handlers (#694)
maplibre/maplibre-gl-js pull request #695
Opened 2021-12-03 15:41 UTC by vanilla-lake

<changelog>Fix MapDataEvent#isSourceLoaded being true in GeoJSONSource "dataloading" event handlers (#694)</changelog>

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Write tests for all new functionality.
 - [x] Manually test the debug page.
 - [x] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2021-12-03 20:41 UTC, HarelM requested changes
Overall very nice refactoring of duplicated code, thanks!

2021-12-03 20:41 UTC, HarelM commented on test/unit/source/geojson_source.test.js
> +    t.test('marks source as loaded when "dataloading" event handler throws', (t) => {
I'm not sure this is the expected behavior, I'm also not sure we should try catch around event handles - if we do we are obligated to do it everywhere in the code, which will create very defensive and verbose code.
I tend to say that developers should make sure the callbacks are not throwing errors...

2021-12-03 20:41 UTC, HarelM commented on src/source/geojson_source.ts
> +        try {
The comment on the test is related to this code mainly.

2021-12-03 20:41 UTC, HarelM commented on src/source/geojson_source.ts
> +    _updateWorkerData(sourceDataType: string) {
Can we have better typing here - event data type instead of string?

2021-12-03 20:41 UTC, HarelM commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
Better typing - I.e. Don't use any

2021-12-03 20:52 UTC, vanilla-lake commented on test/unit/source/geojson_source.test.js
> +    t.test('marks source as loaded when "dataloading" event handler throws', (t) => {
Agreed.

2021-12-03 21:03 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +    _updateWorkerData(sourceDataType: string) {
I think we could pass a `MapDataEvent`.

2021-12-03 21:06 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
If we go for https://github.com/maplibre/maplibre-gl-js/pull/695#discussion_r762257727, I think we'll need to add a `resourceTiming` property to the `MapDataEvent` type. Does that sound OK?

2021-12-03 21:07 UTC, vanilla-lake commented
Thanks and no problem! 😄

2021-12-03 21:18 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +    _updateWorkerData(sourceDataType: string) {
Or to be more precise, maybe a `MapSourceDataEvent`...

2021-12-03 21:19 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
Or to the `MapSourceDataEvent` interface...

2021-12-03 21:39 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +    _updateWorkerData(sourceDataType: string) {
How about `sourceDataType: 'content' | 'metadata'`? Otherwise, do you mean having callers pass a prebuilt `Event` object?

2021-12-03 21:41 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
Would it be okay to do something like:
```typescript
const data = {dataType: 'source', sourceDataType};
if (this._collectResourceTiming && resourceTiming && resourceTiming.length > 0)
    extend(data, {resourceTiming});
```

2021-12-03 21:57 UTC, HarelM commented on src/source/geojson_source.ts
> +    _updateWorkerData(sourceDataType: string) {
`sourceDataType: 'content' | 'metadata'` is one possible solution, the other is using the type the event is using (which is hopefully typed well).
I don't mean pass an event object, just see if in the code there's somewhere that defines `export type SourceDataType = 'content' | 'metadata'` and use that definition, if you can't find one, you might probably need to add it to the event definition and use it here...

2021-12-03 21:59 UTC, HarelM commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
Checkout `MapSourceDataEvent` for this comment and the previous one. we should be able to use it...?

2021-12-03 22:07 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
Wouldn't the callers need to have suitable values for all the `MapSourceDataEvent` properties?

2021-12-03 22:31 UTC, HarelM commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
I guess, but the code fires this event, doesn't it? maybe the event is not typed well and some values are optional, but I think the code fires this event so using this type would be an improvement I think...

2021-12-06 12:45 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
I don't think they are optional. It's just that they are added dynamically in `Evented.fire`: https://github.com/maplibre/maplibre-gl-js/blob/ddc348fe5892db8ec4884c2da37d4c3fe15f3c5d/src/util/evented.ts#L129-L132

`Style` sets the missing properties at: https://github.com/maplibre/maplibre-gl-js/blob/ddc348fe5892db8ec4884c2da37d4c3fe15f3c5d/src/style/style.ts#L574-L578

The `resourceTiming` property in the above snippet is also set dynamically.

2021-12-06 21:06 UTC, HarelM commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
I see what you mean, they are not optional but they are not set when creating the object. I'm not sure how this should be typed, but I tend to say that it should be typed better... :-/

2021-12-06 21:19 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
I agree. However, it'd probably warrant a broader refactoring. For this particular PR, I was thinking of extracting a `MapSourceDataType` union type and having the `sourceDataType` parameter be of that type instead of a string.

2021-12-06 21:28 UTC, HarelM commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
Sure, you are right, it might be too much for this PR...

2021-12-07 12:45 UTC, vanilla-lake commented on src/source/geojson_source.ts
> +            const data: any = {dataType: 'source', sourceDataType};
I just pushed a commit with the change.

2021-12-08 13:23 UTC, HarelM approved these changes

2021-12-08 13:24 UTC, merged