Fix start-debug to watch ts files
maplibre/maplibre-gl-js pull request #704
Opened 2021-12-10 16:21 UTC by jazzzz

This PR fixes `start-debug` and the `watch` scripts.

The drawback is that the minified `maplibre-gl.js` is slightly bigger : 688KB before this PR vs 690KB after (+0.3%), I don't know why.

## Launch Checklist

 -  [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2021-12-10 20:30 UTC, HarelM commented
It's great that you managed to make the  typescript rollup plugin work, I came across some nasty errors when I did the typescript migration.
Note that some typescript configuration in the tsconfig are needed for the types generating and not the tsc command itself, so make sure the bundled typings are mostly the same.
I think the rollup_typescript code should be in the rollup plugins file like the rest of the plugin configuration, wouldn't it be cleaner?
Other than that, great direction!

2021-12-10 20:42 UTC, jazzzz commented
> It's great that you managed to make the typescript rollup plugin work, I came across some nasty errors when I did the typescript migration.
> Note that some typescript configuration in the tsconfig are needed for the types generating and not the tsc command itself, so make sure the bundled typings are mostly the same.

`maplibre-gl.d.ts` did not change, did you think about something else.

> I think the rollup_typescript code should be in the rollup plugins file like the rest of the plugin configuration, wouldn't it be cleaner?

I did it first, but I extracted it to use it for `build-type-spec` that does not use the rollup plugins file, but I could make it use this file.

2021-12-10 20:53 UTC, HarelM commented
Yes, I meant maplibre-gl.d.ts. Did you delete the dist folder to make sure it's generated? Sorry for nagging, I just fought with it a lot to make it run so I'm surprised all these configurations are not actually needed...

Also note that I let the tests run and some are failing, you'll need to investigate why, might be related to the bundle size change as some things broke... IDK...
Thanks again!!

2021-12-10 21:02 UTC, jazzzz commented
> Yes, I meant maplibre-gl.d.ts. Did you delete the dist folder to make sure it's generated? Sorry for nagging, I just fought with it a lot to make it run so I'm surprised all these configurations are not actually needed...

Yes I moved the folder between each commit to make sure to compare them. In fact it's still `dts-bundle-generator` that builds the types bundle, this explains that it is exactly the same, and I don't build it in the `watch` script because I don't think it is useful in this mode.

> Also note that I let the tests run and some are failing, you'll need to investigate why, might be related to the bundle size change as some things broke... IDK... Thanks again!!

I'm still not that familiar with all the tests,, but I'm investigating to make all the tests pass. Thanks for the support!

2021-12-16 17:58 UTC, jazzzz commented
I changed my approach, now the build are nearly the same as before, thus the generated bundles are exactly the same, I only use the typescript rollup plugin in watch mode.

2021-12-16 18:25 UTC, HarelM commented
Thanks for looking into it! Very much appreciated!
Doesn't this mean that the output of the watch is not valid?
If it is valid we can use it instead of the current build, can't we?, If it's not valid then what is the use case?

2021-12-16 18:35 UTC, jazzzz commented
> Doesn't this mean that the output of the watch is not valid?
> If it is valid we can use it instead of the current build, can't we?, If it's not valid then what is the use case?

The output is valid, but many tests use the intermediate js files that the watch do not generate. One way would be to use ts files in the tests, but I could not make it work.

2021-12-16 18:38 UTC, wipfli commented
We are migrating the unit tests to Jest, which can parse the TypeScript files directly. Or are you talking about different tests?

2021-12-16 18:41 UTC, HarelM commented
But I saw that the build tests failed, which I think indicates that something is a bit off with the output...?
I think that if the build can use the typescript rollup plugin it's better then now, but we should finish the migration of the tests before that.
IDK, maybe we can use this PR as a starting point for using the rollup plugin.

2021-12-17 11:06 UTC, jazzzz commented
> We are migrating the unit tests to Jest, which can parse the TypeScript files directly. Or are you talking about different tests?

Tap can parse TypeScript files, but I had issues when mixing js and ts files. I could solve it for some tests by converting them fully to TypeScript, but some tests like [`style-spec.test.js`](https://github.com/maplibre/maplibre-gl-js/blob/d00f75420c8b15f75e53d0ee13f5c9171adb34f0/test/build/style-spec.test.js) include files that cannot be converted to TypeScript. Also browser tests needs some files (like `map.ts`) to be transpiled to run them in the browser, and I could not make them work.

> But I saw that the build tests failed, which I think indicates that something is a bit off with the output...?

Maybe you saw the tests of an old push, now the tests succeed, or maybe you are talking about something else?

2021-12-17 15:25 UTC, HarelM commented
Any chance you can create another PR with the typescript rollup plugin "always on" so we can look at the failing tests to make sure they are only related to js tap tests and not the output of the rollup build (i.e. the build tests)?

2021-12-17 15:32 UTC, jazzzz commented
> Any chance you can create another PR with the typescript rollup plugin "always on" so we can look at the failing tests to make sure they are only related to js tap tests and not the output of the rollup build (i.e. the build tests)?

If you want, but most tests won't even start because they try to import js files in `rollup/build/tsc` that are not generated with the typescript rollup plugin.

2021-12-17 15:45 UTC, HarelM commented
I know, I know, that's fine...

2021-12-17 15:53 UTC, jazzzz commented
> Any chance you can create another PR with the typescript rollup plugin "always on" so we can look at the failing tests to make sure they are only related to js tap tests and not the output of the rollup build (i.e. the build tests)?

PR #720.

2021-12-20 11:34 UTC, HarelM requested changes
nits...

2021-12-20 11:34 UTC, HarelM commented on build/rollup_plugins.js
> +        include: ['**/*.[jt]s'],
I this added to avoid unassert for glsl files?

2021-12-20 11:34 UTC, HarelM commented on tsconfig.json
> +    "declarationDir": "rollup/build/maplibregl",
Why was this changed?
It might be that after the changes I made using dts-bundler there's no need to spit the declarations.

2021-12-20 11:34 UTC, HarelM commented on build/glsl_to_js.js
> +export default function (code, minify) {
better to have a function name when exporting a function, just for the sake of readability.

2021-12-21 11:05 UTC, jazzzz commented on build/rollup_plugins.js
> +        include: ['**/*.[jt]s'],
No, to enable it on ts files: by default `unassert` only applies on js files files. Maybe I should just include `**/*`?

2021-12-21 11:10 UTC, jazzzz commented on tsconfig.json
> +    "declarationDir": "rollup/build/maplibregl",
Because Rollup Typescript plugins requires this directory to be inside the Rollup output directory.

2021-12-21 11:16 UTC, jazzzz commented on build/rollup_plugins.js
> +        include: ['**/*.[jt]s'],
I replaced it with `**/*` and added a comment to explain it.

2021-12-21 13:59 UTC, HarelM commented on tsconfig.json
> +    "declarationDir": "rollup/build/maplibregl",
Can we remove the generation of declaration files altogether?

2021-12-21 14:19 UTC, jazzzz commented on tsconfig.json
> +    "declarationDir": "rollup/build/maplibregl",
Yes you are right, I removed it.

2021-12-21 20:29 UTC, HarelM commented
Let's merge this. Hopefully we'll be able to fully integrate typescript into rollup later on, but right now this at least fixes the watch scripts.
Truly appreciate all the time invested in this @jazzzz!

2021-12-21 20:29 UTC, HarelM approved these changes

2021-12-21 20:30 UTC, merged