[Jest] Migrate `map.test.js`
maplibre/maplibre-gl-js pull request #723
Opened 2021-12-17 19:25 UTC by wipfli

- Move and rename
- Comment out `t.error()`, it breaks jscodeshift
- Run jscodeshift
- Run custom codemods and lint
- Manual edits

## Launch Checklist

Fixed TypeScript errors on 560 out of 2097 lines. Super happy to finally have reached this file :)

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2021-12-20 19:31 UTC, wipfli commented
This is ready ,@HarelM, for review.

2021-12-20 20:20 UTC, HarelM requested changes
Amazing work! well done! some minor comments...

2021-12-20 20:20 UTC, HarelM commented on src/ui/map.test.ts
> +    jest.spyOn(global, 'XMLHttpRequest').mockReturnValue({
You have sinon for that, it's better to use it as it has all the required mocking.
I think I converted a test that uses this, I don't remember right now which one.

2021-12-20 20:20 UTC, HarelM commented on src/ui/map.test.ts
> +        function pass() { done(); }
Can't we simply call done instead of creating this method?

2021-12-20 20:20 UTC, HarelM commented on src/ui/map.test.ts
> +                    if (e.dataType === 'source' && (e as any).sourceDataType === 'metadata') {
Cast to `MapDataEvent` or something similar (this type was introduced recently)

2021-12-20 20:20 UTC, HarelM commented on src/ui/map.test.ts
> +                map.style.sourceCaches.geojson._tiles[fakeTileId.key] = new Tile(fakeTileId, undefined);
Probably not the best way to test this as it uses internal members, but this wasn't introduced here so I don't expect it to be fixed, unless you have the time and will to do so :-)

2021-12-20 20:20 UTC, HarelM commented on src/ui/map.test.ts
>          expect(map._controls).toHaveLength(1);
again, not the best condition as it uses internal fields...

2021-12-20 20:20 UTC, HarelM commented on src/ui/map.test.ts
> +                (map as any).setMaxBounds([-130.4297, 50.0642], [-61.52344, 24.20688]);
is this `as any` really needed? I see that in the previous test you didn't use as any... same for two lines below.

2021-12-20 20:20 UTC, HarelM commented on src/ui/map.test.ts
> +                expect((map as any)._frameId).toBeFalsy();
Same here - `_frameId`...

2021-12-20 20:26 UTC, wipfli commented on src/ui/map.test.ts
> +                (map as any).setMaxBounds([-130.4297, 50.0642], [-61.52344, 24.20688]);
It is. TypeScript prevents invalid arguments, which is what is being tested here.

2021-12-20 20:28 UTC, HarelM commented on src/ui/map.test.ts
> +                (map as any).setMaxBounds([-130.4297, 50.0642], [-61.52344, 24.20688]);
Didn't we agreed to remove tests of invalid input?

2021-12-20 20:38 UTC, wipfli commented on src/ui/map.test.ts
> +        function pass() { done(); }
We can't. `map.on()` invokes the callback with an argument. 

https://github.com/maplibre/maplibre-gl-js/blob/e1c94dccdd7f52c90e2c3ec5de3bd48fcb75ab9f/src/util/evented.ts#L117-L119

Invoking `done()` with an argument fails the test.

2021-12-20 20:44 UTC, HarelM commented on src/ui/map.test.ts
> +        function pass() { done(); }
Use lambda then: `() => done()`

2021-12-20 20:59 UTC, wipfli commented on src/ui/map.test.ts
> +                map.style.sourceCaches.geojson._tiles[fakeTileId.key] = new Tile(fakeTileId, undefined);
Leaving private members for another time.

2021-12-20 20:59 UTC, wipfli commented on src/ui/map.test.ts
>          expect(map._controls).toHaveLength(1);
Leaving private members for another time.

2021-12-20 20:59 UTC, wipfli commented on src/ui/map.test.ts
> +                expect((map as any)._frameId).toBeFalsy();
Leaving private members for another time.

2021-12-20 21:03 UTC, wipfli commented
Off-topic: Don't you find it also strange how the source code documentation works? For example, function parameters have to be declared optional both in the docs comments and in the actual function signature. Isn't there a better way to do this?

2021-12-20 21:04 UTC, wipfli commented
Docs and code are out of sync for example here:

https://github.com/maplibre/maplibre-gl-js/blob/ea7db4d3942cf17ac65b91f7339ed5e22b9e3afb/src/ui/events.ts#L288-L311

2021-12-20 21:08 UTC, wipfli commented
Thanks for the review. I'm really happy that you always make these excellent code reviews. I think I addressed all comments. Please close conversations where you are OK with the answer.

2021-12-21 05:33 UTC, HarelM commented on src/ui/events.ts
> +import {Coordinates} from '../source/image_source';
Import type

2021-12-21 05:40 UTC, HarelM commented on src/ui/events.ts
> +  source?: Object;
These members are part of mapsourcedataevent I believe...?

2021-12-21 05:42 UTC, HarelM commented
Yea, I agree that docs sync is annoying.
Maybe the type should not be part of the docs just the explanation of the parameter? IDK...

2021-12-25 22:27 UTC, wipfli commented on src/ui/events.ts
> +  source?: Object;
Yes. You added `MapSourceDataEvent` when [fixing the typings generated by TypeScript](https://github.com/maplibre/maplibre-gl-js/commit/ddf69421c6ae34c808afefec309a5beecdb7500e#diff-b8d6a5f83861b40661fd2ac4ae7a12b899d83ba7d4cdc522288936db93e743b0). I don't know what to do now. Should I update the docs comment or change the code?

2021-12-26 06:19 UTC, HarelM commented on src/ui/events.ts
> +  source?: Object;
Ahh, I now see the mismatch. I had a discussion somewhere (related to geojson events data) in one of the PRs about exactly this.
I'm not sure which is the right one. As far as I understand, but I might be wrong, these parameters are not optional in the data source event and there isn't an event that fires something with just type and datatype. But I'm not 100% sure. Feel free to investigate :-)

2021-12-26 13:54 UTC, HarelM commented on src/ui/events.ts
> +  source?: Object;
See the following PR: #695 - last resolved conversation is talking about this more or less.
@vanilla-lake can you add your input here too as well, I think you know this better than I do.

2021-12-26 14:30 UTC, wipfli commented
I rebased onto main to include the new tests from #727. Commits you might want to look at @HarelM are the last three:

https://github.com/maplibre/maplibre-gl-js/pull/723/commits/31f16e357c103de448f0c4e00efb8894544227ce
https://github.com/maplibre/maplibre-gl-js/pull/723/commits/0cbf5139b0dd45078438945216c55d57e2520e75
https://github.com/maplibre/maplibre-gl-js/pull/723/commits/9e96a3808431bdaff843140ed180eeb82897f28b

2021-12-26 14:41 UTC, HarelM commented
Reviewed, no new comments. The only item left to reconcile is the above conversation, let's wait for @vanilla-lake 's response.

2022-01-07 13:30 UTC, vanilla-lake commented on src/ui/events.ts
> +  source?: Object;
As far as I can tell, @HarelM is right: those properties will only get a value in the case of source data events.

2022-01-08 10:25 UTC, wipfli commented on src/ui/events.ts
> +  source?: Object;
Thanks @vanilla-lake

2022-01-08 11:56 UTC, HarelM commented on src/ui/events.ts
> +  sourceDataType: string;
Should be of type `MapSourceDataType`?

2022-01-08 20:00 UTC, wipfli commented on src/ui/events.ts
> +  sourceDataType: string;
Correct, thanks!

2022-01-09 20:50 UTC, HarelM approved these changes

2022-01-09 20:58 UTC, merged