[Jest] Migrate `image_source.test.js`
maplibre/maplibre-gl-js pull request #732
Opened 2021-12-27 16:52 UTC by wipfli

- Move and rename
- Run jscodeshift
- Run custom codemods and lint
- Manual edits

Hints on how to properly mock non-string XHR responses are welcome.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-01-22 13:07 UTC, birkskyum commented
I think it's reasonable for us to use fetch at this point, if it makes it simpler in any way.

https://medium.com/swlh/how-to-mock-a-fetch-api-request-with-jest-and-typescript-bb6adf673a00
https://medium.com/swlh/mocking-xhr-request-with-jest-93875ed83dda

2022-01-22 13:33 UTC, birkskyum commented
I meant both actually, and I also think we should keep it without using the network. I have tried to get the current "fires dataloading event" test to work, but for some reason the image isn't bound to the source.image, and it seems to be related to replacing window.useFakeXMLHttpRequest(); with our custom mock function.

2022-01-22 13:35 UTC, birkskyum commented
I can see we still use sinon in the migrated style.test.ts, so it might also be an option to keep it.

2022-01-23 15:22 UTC, wipfli commented
I got some inspiration from `load_glyph_range.test.ts`, still fails, but it feels closer.

2022-01-23 15:35 UTC, wipfli commented
@HarelM do you think we need some `Object.defineProperty(global.Image.prototype, 'src'` stuff here, too?

2022-01-23 15:36 UTC, HarelM commented
I haven't looked at it. It you want me to try and hack it, let me know...

2022-01-23 17:02 UTC, wipfli commented
Please try and hack it, @HarelM :)

2022-01-23 17:32 UTC, wipfli commented
Found something that works.

2022-01-23 17:37 UTC, birkskyum commented
Awesome! And same approach as the style, glyph and ajax to keep things consistent :)

2022-01-23 17:39 UTC, birkskyum commented
So is it ready for review?

2022-01-23 17:39 UTC, wipfli commented
Thanks for looking at this. I will clean up and ping you when ready for review.

2022-01-23 17:56 UTC, wipfli commented
This is the last pull request that migrates a unit test from tap to jest :) Thanks @HarelM, @astridx, @chippieTV, and @birkskyum for all the contributions :)

2022-01-23 18:07 UTC, HarelM requested changes
Great work!! Small nits...

2022-01-23 18:07 UTC, HarelM commented on src/source/image_source.test.ts
> +    global.createImageBitmap = undefined;
Consider moving this code to utils or even better - stub ajax getImage method.

2022-01-23 18:07 UTC, HarelM commented on src/source/image_source.test.ts
> +    jest.spyOn(browser, 'getImageData').mockImplementation(() => new ArrayBuffer(1) as any as ImageData);
I don't think this is needed. Browser is not used by image source anymore...

2022-01-23 18:07 UTC, HarelM commented on src/source/image_source.test.ts
> +        source.onAdd(getStubMap());
I would keep it as it was as you are replacing a method with a single line of code. I would do `new MapStub...` as it was before.

2022-01-23 19:17 UTC, wipfli commented on src/source/image_source.test.ts
> +    global.createImageBitmap = undefined;
Thanks for reviewing. Did you think of something like https://github.com/maplibre/maplibre-gl-js/pull/732/commits/2a6bc1df7a351aedc69c7a5390039a55571b6d7f ?

2022-01-23 19:35 UTC, HarelM commented on src/source/image_source.test.ts
> +    global.createImageBitmap = undefined;
This is good. Moving it to another file to be used by ajax would be better.
Stubbing ajax's getImage would be ideal :-)

2022-01-23 20:58 UTC, HarelM approved these changes

2022-01-23 20:58 UTC, merged