[Jest] Migrate `source_cache.test.js`
maplibre/maplibre-gl-js pull request #746
Opened 2022-01-02 13:31 UTC by wipfli

- Move and rename
- Uncomment line that makes jscodeshift fail
- Run jscodeshift
- Run custom codemods and lint
- Manual edits
- Wrap in describe

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-01-02 16:18 UTC, HarelM requested changes

2022-01-02 16:18 UTC, HarelM commented on src/source/source_cache.test.ts
> +    }, options), /* dispatcher */ {} as Dispatcher);
Remove comment of type.

2022-01-02 16:18 UTC, HarelM commented on src/source/source_cache.test.ts
> +        ], 10, tr as any as boolean)).toEqual([]);
This is strange... Casting to Boolean...?

2022-01-02 16:18 UTC, HarelM commented on src/source/source_cache.test.ts
> +        id: any;
Move this class out of the function and only initit in the function. Also add typings to the function parameter.

2022-01-02 17:04 UTC, wipfli commented on src/source/source_cache.test.ts
> +        ], 10, tr as any as boolean)).toEqual([]);
Right. Really strange I agree. Since `tr` is an object, I guess this will always cast to `true`.

2022-01-04 12:57 UTC, HarelM approved these changes

2022-01-04 12:57 UTC, merged