[Jest] Migrate `style.test.js`
maplibre/maplibre-gl-js pull request #753
Opened 2022-01-02 17:00 UTC by wipfli

- Move and rename
- Run jscodeshift
- Run custom codemods and lint
- Manual edits

## Launch Checklist

This pull request continues the work of @astridx's #733. I added 1 commit (see https://github.com/wipfli/maplibre-gl-js/commit/a26b7a17a931e5355d9b73040daa81b9bbcf10f1) to make the tests pass.
Then I rebased the different manual commits after the automatic ones for easier review. Thanks Astrid for contributing the migration of this test!

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Manually test the debug page.
 - [ ] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [ ] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.

2022-01-02 17:20 UTC, HarelM commented on src/style/style.test.ts
> +                done.fail();
We said this doesn't work, right?

2022-01-02 17:24 UTC, wipfli commented on src/style/style.test.ts
> +                done.fail();
Yes. Fixed.

2022-01-02 18:49 UTC, astridx commented
Thank you for taking over my branch. 

When I uploaded it, I was sure about the enabled code parts. At the moment I am unsure in parts. 

In the test "validates filter by default" it should be "havebeencalledtimes(1)". (line 1645) 

And while correcting I noticed that I forgot done in line 101 (test "loads plugin immediately if already registered").  

That's where I was currently stuck in my brunch. 

I'm sorry for making a mess here again.

2022-01-02 20:43 UTC, HarelM requested changes
Very hard to review due to compare misalignment... :-(

2022-01-09 21:43 UTC, wipfli commented
#764

2022-01-09 21:43 UTC, closed without merging