Release automation
maplibre/maplibre-gl-js pull request #95
Opened 2021-03-11 22:03 UTC by petr-pokorny-1

## GitHub workflow for releasing new versions

The logic is split in two jobs
* First jobs perform tests. It runs on Windows runner since Linux runners don't have GPU, which is required by many tests.
* Second job creates builds minified library, creates github release, uploads release assets, updates version in npm package and submits package in the npm registry.

## Workflow Description

The workflow is triggered when a tag is pushed or It can also be triggered manually.
After the workflow starts it searches for the most recent version tag (that is a tag with `v*.*.*` format) and uses the version from this tag for the next processing. The version must follow [semantic versioning rules](https://classic.yarnpkg.com/en/docs/dependency-versions#toc-semantic-versioning).

There can be regular version (i.e. 1.13.0) or pre-release (i.e. 1.13.0-rc.1).

In case of regular version the action parses `CHANGELOG.md` and creates release notes based on current and last version. Release notes are not generated for pre-release versions. In case of pre-release versions the github release is marked as pre-release accordingly.

The changelog should be updated on every PR - there is a placeholder at the top of the document - and heading should be renamed to the same version which is going to be set in the version tag during release.

## Workflow Setup

The workflow expects there is `NODE_AUTH_TOKEN` secret in the repo settings which is used for pushing to npm registry.

There are no tags in the maplibre-gl-js repo currently. Initial tags can be setup as follows:

```bash
git tag -a v1.13.0 f87090b -m "version 1.13.0"                                                
git tag -a v1.13.1 -m "version 1.13.1"                                                        
git push --tags 
```

2021-03-11 22:17 UTC, nyurik commented
looks awesome, thanks!  A few minor things:
* there is a number of linting issues, as shown in the files changed tab
* I think we should validate the tag for consistency, e.g. verify that it starts with a `v`, and that the number is valid, and that the changelog has a section dedicated to that version (the changelog would have the same version but without v?). The changelog requirement might be different for beta/rc releases (TBD).

2021-03-11 22:37 UTC, nyurik requested changes

2021-03-11 22:37 UTC, nyurik commented on package.json
> +}
missing eol?
```suggestion
}

```

2021-03-11 22:37 UTC, nyurik commented on test/ignores.json
> +}
eol (many editors can add these automatically)
```suggestion
}

```

2021-03-11 22:37 UTC, nyurik commented on build/version-utils.js
> +        console.log('Unknown command.');
```suggestion
        console.log('Unknown command.');
        break;
```

just in case someone adds another case after default, better keep it safe :)

2021-03-11 22:37 UTC, nyurik commented on build/version-utils.js
> +        .replace('v', '');
this could replace `v` in any position, not just first -- is that intended?

2021-03-11 22:37 UTC, nyurik commented on build/version-utils.js
> +            tag = tag.replace('v', '').trim();
removing `v` in any position?

2021-03-11 22:37 UTC, nyurik commented on build/version-utils.js
> +            return tag && /v*.*.*/.test('tag')
this line doesn't make sense to me:
* `v*` means zero or more of `v`s
* `.*.*` is the same as `.*`
* `test('tag')` is always true because the string "tag" will always match the regex

2021-03-12 07:30 UTC, petr-pokorny-1 commented on build/version-utils.js
> +            return tag && /v*.*.*/.test('tag')
resolved in https://github.com/maplibre/maplibre-gl-js/pull/95/commits/6c315b316e31c408436ceea3503594105a0563f4

2021-03-12 07:30 UTC, petr-pokorny-1 commented on build/version-utils.js
> +            tag = tag.replace('v', '').trim();
resolved in https://github.com/maplibre/maplibre-gl-js/pull/95/commits/6c315b316e31c408436ceea3503594105a0563f4

2021-03-12 07:30 UTC, petr-pokorny-1 commented on build/version-utils.js
> +        .replace('v', '');
resolved in https://github.com/maplibre/maplibre-gl-js/pull/95/commits/6c315b316e31c408436ceea3503594105a0563f4

2021-03-12 07:42 UTC, petr-pokorny-1 commented
>    I think we should validate the tag for consistency, e.g. verify that it starts with a `v`, and that the number is valid

This should be addressed here https://github.com/maplibre/maplibre-gl-js/blob/6c315b316e31c408436ceea3503594105a0563f4/build/version-utils.js#L57
The tag format should be ensured by regular expressions. One more validation there checks if the new version tag is greater than the previous one (using semver library)

> and that the changelog has a section dedicated to that version (the changelog would have the same version but without v?). 

The test is here:
https://github.com/maplibre/maplibre-gl-js/blob/6c315b316e31c408436ceea3503594105a0563f4/build/release-notes.js#L54
The explanation how the relevant parts of changelog is matched is here:
https://github.com/maplibre/maplibre-gl-js/blob/6c315b316e31c408436ceea3503594105a0563f4/build/release-notes.js#L26
(this is original code from Mapbox)

> The changelog requirement might be different for beta/rc releases (TBD).

The workflow has one variant for beta/rc releases and second for regular releases. For beta/rc releases, no release notes are produced. I would suggest to come up with solution for beta release notes in another PR if they are needed.

2021-03-13 06:59 UTC, nyurik reviewed
a few more minor suggestions - I think it is better to rely on semver library for all parsing/testing, than to use regex - except to test that the semver begins with a `v` -- because semver automatically removes it.  `tags.map(v => v.trim()).filter(v => /^v\d/.test(v)).map(v => semver.validate(v)).filter(v => v)` should work (or something similar). 

Agree with your point about beta/release notes.

2021-03-13 06:59 UTC, nyurik commented on build/version-utils.js
> +            return tag && /v\d+.\d+.\d+/.test(tag)
the `.` here is "any symbol".  In other words, your regex would match `abcv33a1b099foo`.  I think a better path would be to test if the tag name matches `/^v\d/`, and if so, remove the starting `v`, and pass the rest to the semver library. If the library can parse it, treat it as valid.  Ah, and one more unrelated thing -- i think its better to use arrow functions everywhere -- makes your code easier to read.

2021-03-13 06:59 UTC, nyurik commented on build/version-utils.js
> +            tag = tag.replace(/^v/, '').trim();
I think semver library automatically removes the `v` - might as well just do this:

```
.map(semver.clean)
```

or to make it a bit clearer for readers:

```
.map(tag => semver.clean(tag))
```

2021-03-13 07:01 UTC, nyurik commented on build/version-utils.js
> +            tag = tag.replace(/^v/, '').trim();
P.S. not sure about the `clean()` function - might be safer to use `validate(tag.trim())` ?  I'm no expert in semver lib though, might be wrong.

2021-03-15 21:35 UTC, petr-pokorny-1 commented on build/version-utils.js
> +            return tag && /v\d+.\d+.\d+/.test(tag)
Resolved in https://github.com/maplibre/maplibre-gl-js/pull/95/commits/1a6b3bcb9bfbe7c4a97b03d57b199ac292af911e

2021-03-15 21:35 UTC, petr-pokorny-1 commented on build/version-utils.js
> +            tag = tag.replace(/^v/, '').trim();
Resolved in https://github.com/maplibre/maplibre-gl-js/pull/95/commits/1a6b3bcb9bfbe7c4a97b03d57b199ac292af911e

2021-03-24 10:39 UTC, klokan commented
NODE_AUTH_TOKEN token is configured now.

2021-03-24 13:24 UTC, merged

2021-03-24 15:51 UTC, klokan commented
Please no beta / rc and other pre-releases. Just semver - and increments - as soon as the release cycle is fixed.

2021-03-24 15:57 UTC, nyurik commented
@klokan any reason not to automate publishing to NPM for rc/beta versions?