Move bench under `test` folder
maplibre/maplibre-gl-js pull request #979
Opened 2022-02-10 15:23 UTC by HarelM

## Launch Checklist

This PR moves `bench` folder under `test` where I believe it should be.
I've ran the bench locally but I'm not 100% sure it is working as expected.
@wipfli @birkskyum can you guys make sure I didn't break anything here?

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.

2022-02-10 15:38 UTC, birkskyum commented
It fits better there for sure. I upload-benchmarks.yml github workflow needs to get paths updated as well.

2022-02-10 15:46 UTC, birkskyum requested changes
LGTM. Only the paths in git workflow (upload-benchmarks.yml) left to update.

2022-02-10 16:48 UTC, wipfli commented on test/bench/README.md
> +To run all benchmarks, open [the benchmark page, `http://localhost:9966/test/bench/versions`](http://localhost:9966/bench/versions).
http://localhost:9966/bench/versions -> http://localhost:9966/test/bench/versions

2022-02-10 16:52 UTC, wipfli commented
Tested running benchmarks locally and they worked the same way as they used to. Please fix link in readme. Other than that, looks good to me.

2022-02-10 16:53 UTC, wipfli commented
> When I opened the browser I saw some errors related to source_cache and some warning about a missing icon.
> Is this expected?

I don't know. Checkout main and compare how it was before.

2022-02-10 16:56 UTC, birkskyum requested changes
![benchmarks-paths](https://user-images.githubusercontent.com/74932975/153456908-62a2039a-a7c8-4f45-94ee-e847f89e71ac.png)

Found these paths as well that I think needs attention

2022-02-10 17:41 UTC, wipfli commented
Please also make sure that `npm run benchmark` completes all benchmarks successfully.

2022-02-10 17:51 UTC, HarelM commented
I definitely don't like the backward compatibility need here. This is counter productive when talking about refactoring and moving files and other things around.
The fact that we use code that is not address agnostic is just bad practice.
I don't know how to properly solve this, but it's just another sign (besides the need to upload js files for every version) that this is poorly written... :-(
I'll open an issue about it...

2022-02-10 17:56 UTC, birkskyum commented
I agree, it's really annoying... tripped me the other day with the es modules as well, and I'm thinking it might be more reasonable for us to upload the maplibre-gl.js build instead of the benchmarks build, because do we even need a such.

2022-02-10 18:05 UTC, birkskyum commented
We have all the old versions here already: [https://cdn.skypack.dev/maplibre-gl@^1.3](https://cdn.skypack.dev/maplibre-gl@%5E1.3), so we could use the releases, and then the current branch, and forget about "main" in the comparisons...

2022-02-11 07:38 UTC, HarelM commented
I added a start-server-at-test to fix the issue with the relative path, but now the css file is not available since dist folder is not part of this server. I can hack that too I guess, but I don't know if this is the right direction as I said before.
We also have a css from mapbox that we are loading as part of the benchmarks with I believe we should stop using:
`<link href='https://www.mapbox.com/base/latest/base.css' rel='stylesheet' />`
I'm not sure what it does, but it is used in the styles benchmark.

2022-02-11 08:14 UTC, birkskyum commented
How about just using this url for the css? https://unpkg.com/maplibre-gl@2.1.1/dist/maplibre-gl.css

2022-02-11 08:31 UTC, HarelM commented
Seems like the tests are running without loading the css, so I tend to say that it's redundant...
I need to see if removing the mapbox css is possible too.

2022-02-11 08:33 UTC, birkskyum commented
Sure, the gl-stats.ts pull in the css from /dist/ , so that still works

2022-02-11 09:05 UTC, HarelM commented
I don't see that gl-stat uses css, it pull the code and replaces that when running, but that's a different story.
In any case, I think this PR is read.
I'm not super exited about it, but it's better than what it used to be I believe.
I don't think it breaks anything as far as I tested.
Feel free to test this too as I'm not super familiar with the benchmarks usage...

2022-02-11 09:39 UTC, birkskyum commented
Great! I'm almost through the whole benchmarks.

2022-02-11 09:50 UTC, birkskyum approved these changes
Same performance as main, so it lgtm!
![benchmarks-cli](https://user-images.githubusercontent.com/74932975/153570326-256da02a-1c5a-4ea2-8dd8-9d364c91202f.png)

2022-02-11 09:53 UTC, merged

2022-03-10 10:15 UTC, xabbu42 commented
Sorry to be this late with the remark, but I think the benchmark documentation at https://github.com/maplibre/maplibre-gl-js/blob/main/test/bench/README.md still needs to be updated to match this changes.